### ISSUE TITLE
Allow scheduling major compactions

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2028]
Ghost issue, real issue is [here](https://github.com/scylladb/scylla-manager-enterprise/issues/2028).

**Comment by tzach** [comment]
This depends on a Scylla Feature (API) for major compaction  https://github.com/scylladb/scylla-enterprise/issues/1427 which was not yet implemented.

**Comment by bhalevy** [comment]
> This depends on a Scylla Feature (API) for major compaction [scylladb/scylla-enterprise#1427](https://github.com/scylladb/scylla-enterprise/issues/1427) which was not yet implemented.

Why?  Can't scylla-manager / siren issue major compaction periodically using the existing API?
