### ISSUE TITLE
sctool: small table flag setting

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2805]
This flag is not documented, and it should be an int expressed in MiB as everywhere else. Internally it is kept in bytes.

--small-table-threshold string enable small table optimization for tables of size lower than given threshold. Supported units [B, MiB, GiB, TiB] (default "1GiB")

**Comment by karol-kokoszka** [comment]
Repair is going to be revisited in Scylla-Manager 3.2.
Closing this issue.
