### ISSUE TITLE
CQL query ping opens at least 4 connections while it should open just one

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2808]
Commit d33fa2b contains a test.
Run make pkg-integration-test PKG=./pkg/ping/cqlping/ RUN=Leak to see results

Typically it opens 4 TCP connections

```
    09:44:29.663    INFO    DialContext     {"network": "tcp", "addr": "192.168.100.11:9042"}
    09:44:29.667    INFO    Close
    09:44:29.667    INFO    DialContext     {"network": "tcp", "addr": "192.168.100.11:9042"}
    09:44:29.674    INFO    DialContext     {"network": "tcp", "addr": "192.168.100.11:9042"}
    09:44:29.680    INFO    DialContext     {"network": "tcp", "addr": "192.168.100.11:9042"}
    09:44:29.682    INFO    Close
    09:44:29.682    INFO    Close
```

We should just open a "Control connection" and use that, needs driver infrastructure to be exposed.

**Comment by slivne** [comment]
in case we are connecting to a scylla node with 64 shards - will the current version attempt to open 64 connections or not ?

If it does we need to fix that in existing releases as well.

We should not allow shardawrness in this case (we can use protocol version 3 - that will disable that if I recall correctly)
