### ISSUE TITLE
DOCS: sctool missing options

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-manager#2816]
SM 2.3: https://manager.docs.scylladb.com/branch-2.3/sctool/task.html
SM 2.4: https://manager.docs.scylladb.com/stable/sctool/task.html

Problem
Our documentation for the sctool task command is either missing options or pointing to invalid options. Most notably, the task progress, task start and task stop sections.

Suggest a fix
task progress section must include the --run <string> parameter, to retrieve progress of a specific run, the --keyspace <list> option to filter for specific keyspaces, and the --hosts <string> option to filter for specific hosts.

Shows a task progress

Command docs: https://scylladb.github.io/scylla-manager/2.3/sctool/task#task-progress

Usage:
  sctool task progress <type/task-id> [flags]

Flags:
      --details         show detailed progress
  -h, --help            help for progress
      --host strings    a comma-separated list of host glob patterns, e.g. '1.1.1.*,!1.2.*.4
  -K, --keyspace list   a comma-separated list of keyspace/tables glob patterns, e.g. 'keyspace,!keyspace.table_prefix_*'
      --run string      show progress of a particular run, see sctool task history

Global Flags:
      --api-cert-file path   path to HTTPS client certificate to access Scylla Manager server
      --api-key-file path    path to HTTPS client key to access Scylla Manager server
      --api-url URL          URL of Scylla Manager server (default "http://127.0.0.1:5080/api/v1")
  -c, --cluster name         Specifies the target cluster name or ID
task start section needs to update the --continue option to --no-continue. The default is to resume the task at the point where it got stopped:

Starts executing a task

Command docs: https://scylladb.github.io/scylla-manager/2.3/sctool/task#task-start

Usage:
  sctool task start <type/task-id> [flags]

Flags:
  -h, --help          help for start
      --no-continue   do not resume last run

Global Flags:
      --api-cert-file path   path to HTTPS client certificate to access Scylla Manager server
      --api-key-file path    path to HTTPS client key to access Scylla Manager server
      --api-url URL          URL of Scylla Manager server (default "http://127.0.0.1:5080/api/v1")
  -c, --cluster name         Specifies the target cluster name or ID
task stop section must include the --disable option to disable the task in addition to stopping it:

Stops the currently running task instance

Command docs: https://scylladb.github.io/scylla-manager/2.3/sctool/task#task-stop

Usage:
  sctool task stop <type/task-id> [flags]

Flags:
      --disable   do not run in future
  -h, --help      help for stop

Global Flags:
      --api-cert-file path   path to HTTPS client certificate to access Scylla Manager server
      --api-key-file path    path to HTTPS client key to access Scylla Manager server
      --api-url URL          URL of Scylla Manager server (default "http://127.0.0.1:5080/api/v1")
  -c, --cluster name         Specifies the target cluster name or ID

**Comment by karol-kokoszka** [comment]
These documentation changes are addressed starting from 3.0 release.
https://manager.docs.scylladb.com/branch-3.0/sctool/stop.html
https://manager.docs.scylladb.com/branch-3.0/sctool/progress.html
https://manager.docs.scylladb.com/branch-3.0/sctool/start.html
