### ISSUE TITLE
Prometheus endpoint hangs and ends up causing FD starvation

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla-manager#2843]
**Scylla Manager version**: 2.4.0-0.20210629.e62d606f
**Issue**: Queries to Scylla Manager metrics endpoint (`curl http://127.0.0.1:56090/metrics`) are hangs forever (i.e: keeps waiting for ~8 minutes and nothing is ever returned). As a side-effect, Scylla Manager may run out of file descriptors when the metrics endpoint is queried frequently.

Restarting the service does not help. For context, this is a large deployment with 12 clusters and ~180 nodes in total.
`lsof` output shows around 20K socket files opened, which seem around too much and may or not be related:

```
grep sock lsof_10783 | wc -l
19892
```

Deployment details (lsof output, `scylla_manager.cluster`, `scylla_manager.repair_run`, `scylla-manager.yaml`, and scylla manager logs) may be found under UUID `04245fd1-4bc6-4e03-9868-05b5aa8a053d`

**Comment by rjeczalik** [comment]
> As a side-effect, Scylla Manager may run out of file descriptors when the metrics endpoint is queried frequently.

It means the /metrics endpoint is leaking TCP connections.

**Comment by rjeczalik** [comment]
@fee-mendes If you or the party, on behalf which you created this issue, add `Connection: close` header to their HTTP client, it would fix the file descriptors issue (a workaround for now).

**Comment by fee-mendes** [comment]
> @fee-mendes If you or the party, on behalf which you created this issue, add `Connection: close` header to their HTTP client, it would fix the file descriptors issue (a workaround for now).

Thanks @rjeczalik. Do you have any other data we may need to gather in order to determine the culprit, though? There are only 9 connections opened on 56909 as per `lsof` output, which is low and shouldn't really hang. Out of these 9, only 1 is actually ESTABLISHED:

```
$ grep 56090 lsof_10783 | grep -v LISTEN | wc -l
9
$ grep 56090 lsof_10783 | grep ESTABLISHED | wc -l
1
```

**Comment by rjeczalik** [comment]
@fee-mendes I don't understand, if you say frequent calling /metrics causes "out of file descriptors" then the leak is the culprit, software bug which we need to fix.

If you now say there are no leaks and "out of file descriptors" happens regardless, then I have no idea what is the culprit and it is rather irrelevant in this issue.

**Comment by fee-mendes** [comment]
> @fee-mendes I don't understand, if you say frequent calling /metrics causes "out of file descriptors" then the leak is the culprit, software bug which we need to fix.
> 
> If you now say there are no leaks and "out of file descriptors" happens regardless, then I have no idea what is the culprit and it is rather irrelevant in this issue.

Any call to `/metrics` cause it to hang at any point in time. What was done in-between to avoid FD accumulating was simply to disable clients from trying to hit that endpoint. BTW, how will `Connection: close` help in that case, as the server is never returning a response back?

**Comment by rjeczalik** [comment]
On Mon 16. Aug 2021 at 18:03, fee-mendes ***@***.***> wrote:

> @fee-mendes <https://github.com/fee-mendes> I don't understand, if you
> say frequent calling /metrics causes "out of file descriptors" then the
> leak is the culprit, software bug which we need to fix.
>
> If you now say there are no leaks and "out of file descriptors" happens
> regardless, then I have no idea what is the culprit and it is rather
> irrelevant in this issue.
>
> Any call to /metrics cause it to hang at any point in time. What was done
> in-between to avoid FD accumulating was simply to disable clients from
> trying to hit that endpoint. BTW, how will Connection: close help in that
> case, as the server is never returning a response back?
>
If the server does not have write timeouts configured correctly, it won’t
work. It is worth to give it a try though.

**Comment by fee-mendes** [comment]
@rjeczalik - it looks like we can't explicitly configure custom headers on Prometheus, which is part of the Scylla Monitoring Stack. 
Therefore, the suggested `Connection: close` workaround won't help in that context. For the time being, we've disabled Prometheus from trying to scrape at Scylla Manager's endpoint.

Is there any other data you need or suggestion you have for us to identify the problem's cause?

**Comment by fee-mendes** [comment]
It is confirmed that disabling scraping on Scylla Manager `/metrics` endpoint has stopped FDs from accumulating. 

So it seems that Scylla Manager keeps a connection open even after the client gives up. Now we need to figure out what is causing the `/metrics` endpoint to get hung forever. :-)

**Comment by zimnx** [comment]
I'm not able to reproduce it locally using 2.4. I only see a single hanging connection between Prometheus and Scylla Manager. 
```
$ sudo lsof -p 186945 | grep 5090
scylla-ma 186945 maciej   12u     IPv6            1721977      0t0     TCP *:5090 (LISTEN)
scylla-ma 186945 maciej   13u     IPv6            1743804      0t0     TCP localhost:5090->localhost:48048 (ESTABLISHED)
```
Manually checking metrics using `curl` also doesn't add any FD. Maybe it reproduces when there're some network issues and new connections needs to be established, although these case should be handled by keepalives which are enabled. 

Can you reproduce it and collect goroutine dump? We would know where all these connections hangs.
By default Scylla Manager exposed debug (pprof) server on 127.0.0.1:5112 (configurable in SM config). 
Once you reproduce it simply use:
```
$ curl "http://127.0.0.1:5112/debug/pprof/goroutine?debug=2" --output goroutine.dump
```
and share the output file with us.

**Comment by fee-mendes** [comment]
@zimnx 

Available at `7fa4bb6b-e2e0-48df-9472-20ddf78f6f72`

**Comment by zimnx** [comment]
Thanks, looks like there're lots of goroutines gathering metrics originating from http server, and they compete on same RWLock with our [healthcheck job](https://github.com/scylladb/scylla-manager/blob/c240d9da45cf511a02520aa4e4771e2a63686eab/pkg/service/healthcheck/runner.go#L113) which clears metrics for hosts which left clusters. 

Still investigating though.

**Comment by zimnx** [comment]
@fee-mendes  Are you able to provide another goroutine dump? This time using:
```
$ curl "http://127.0.0.1:5112/debug/pprof/goroutine?debug=1" --output goroutine1.dump
```

**Comment by Pawel-Kr** [comment]
@zimnx collecting in progress.

**Comment by zimnx** [comment]
I found the deadlock:
```
goroutine 562120 [chan send, 2560 minutes]:
github.com/prometheus/client_golang/prometheus.(*metricMap).Collect(0xc000706c90, 0xc024488900)
	github.com/prometheus/client_golang@v1.8.0/prometheus/vec.go:312 +0x138
github.com/prometheus/client_golang/prometheus.(*MetricVec).Collect(...)
	github.com/prometheus/client_golang@v1.8.0/prometheus/vec.go:109
github.com/scylladb/scylla-manager/pkg/service/healthcheck.collect.func1(0xc000206220, 0xc024488900)
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/metrics.go:151 +0x3b
created by github.com/scylladb/scylla-manager/pkg/service/healthcheck.collect
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/metrics.go:150 +0x67
```
This goroutoine is trying to send to buffered channel while keeping RLock, while the reader of the channel is trying to take WLock:
```
goroutine 561437 [semacquire, 2560 minutes]:
sync.runtime_SemacquireMutex(0xc000706c98, 0x0, 0x0)
	runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc000706c90)
	sync/rwmutex.go:103 +0x85
github.com/prometheus/client_golang/prometheus.(*metricMap).deleteByHashWithLabels(0xc000706c90, 0xe6133ecd43047988, 0xc03f36f320, 0x0, 0x0, 0x0, 0xc01f982400)
	github.com/prometheus/client_golang@v1.8.0/prometheus/vec.go:362 +0x5a
github.com/prometheus/client_golang/prometheus.(*MetricVec).Delete(0xc000706c60, 0xc03f36f320, 0x18e3f30)
	github.com/prometheus/client_golang@v1.8.0/prometheus/vec.go:99 +0x90
github.com/scylladb/scylla-manager/pkg/service/healthcheck.Runner.removeMetricsForMissingHosts.func1(0xc000f5bec0, 0x24, 0x0, 0x0, 0xc000615fe0, 0xa, 0x0, 0x0, 0x3ff0000000000000)
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/runner.go:131 +0x212
github.com/scylladb/scylla-manager/pkg/service/healthcheck.apply(0xc024488900, 0xc05b395c00)
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/metrics.go:144 +0x3a3
github.com/scylladb/scylla-manager/pkg/service/healthcheck.Runner.removeMetricsForMissingHosts(0xc000d16d70, 0xc00119c770, 0xc0004ad940, 0xc00119c780, 0x54fc127cc33aed0, 0x9133e6b1b35dc7ab, 0xc0156d8400, 0x11, 0x20)
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/runner.go:119 +0x2b3
github.com/scylladb/scylla-manager/pkg/service/healthcheck.Runner.Run(0xc000d16d70, 0xc00119c770, 0xc0004ad940, 0xc00119c780, 0x1b78c80, 0xc055a141c0, 0x54fc127cc33aed0, 0x9133e6b1b35dc7ab, 0x1458d777a724b00, 0x5953b2d393230096, ...)
	github.com/scylladb/scylla-manager/pkg/service/healthcheck/runner.go:53 +0x2fa
github.com/scylladb/scylla-manager/pkg/service/scheduler.(*Service).run.func3(0xc055916180, 0xc000abbe00, 0xc02bf71860, 0xc0557f7460, 0xc055a0afc0, 0xc04633f76a, 0x2, 0x2)
	github.com/scylladb/scylla-manager/pkg/service/scheduler/service.go:463 +0x102
created by github.com/scylladb/scylla-manager/pkg/service/scheduler.(*Service).run
	github.com/scylladb/scylla-manager/pkg/service/scheduler/service.go:462 +0xabb
```

This happens when number of metrics exceeds the buffered channel length.

Working on the fix
