### ISSUE TITLE
Sctool suspend/resume improvements suggestion.

### ISSUE THREAD

**Issue by Pawel-Kr** [scylladb/scylla-manager#2849]
There's a suggestion that UX on the Manager 2.5 can be improved - when using `sctool suspend/resume`, the commands should not return an error if the cluster is already suspended/resumed. Here's an example:
```
$ sctool resume -c cluster_name; echo $?
0
$ sctool resume -c cluster_name; echo $?
Error: resume: cluster is not suspended
Trace ID: MAzxt1F1T6et_d01XHMJag (grep in scylla-manager logs)

1
```
Reasoning and expectation on commands that trigger a change of state is that they should be idempotent. In addition, there is no variance in the return code `sctool` provides (1), so it's impossible to differentiate between a strong error and an "already done error".

@mmatczuk please take a look. Thanks.

**Comment by mmatczuk** [comment]
I agree.
