### ISSUE TITLE
Agent service depends on scylla-server, is it needed?

### ISSUE THREAD

**Issue by carlosms** [scylladb/scylla-manager#2856]
Hi,

`scylla-manager-agent` service depends on `scylla-server`
https://github.com/scylladb/scylla-manager/blob/7a84ff1674b6a53bbf0b7f5764af5f4256db04f3/dist/systemd/scylla-manager-agent.service#L3

Is this actually needed, or could this dependency be dropped?

In the cloud we found out that our code assumed the manager agent could be installed independently, but it broke our Add DC automation because the agent was also starting scylla server before we could start it explicitly.

For now we will update the code to not install the agents until we have started scylla. But it's a kind of surprising side effect, and it can happen to us in the future again.

I imagine this could be a potential problem for other users too.

**Comment by karol-kokoszka** [comment]
Scylla-manager-agent depends on scylla service and it joins the scylla-server slice to follow the limits defined here.
