### ISSUE TITLE
Mgmt Backup timeout 

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla-manager#2860]
This issue is the same as #2690 but I can't reopen it.
The issue reproduces when using latest  manager versions.

agent  version: scylla-manager-agent version 666.dev-0.20210518.f85e9296
server version: 2.6-dev-0.20210829.7a84ff1674b

Test Job: longevity-200gb-48h (https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/135/)

@ShlomiBalalis please own this ticket and add any other required information.

Maybe related to: https://github.com/scylladb/scylla/issues/9192
(But in any case even if we had coredump, I think that the task should have  reached a final state).

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis is the issue still valid ? Can you check ?

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis is the issue still valid ? Can you check ?

I checked in master (though it's been a long time since we ran it there) 2022.2 and 2023.1 and didn't see a single manager backup timeout or failure. Closing.
