### ISSUE TITLE
need to add support of scylla-manager-agent to SLES15

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-manager#2887]
Following this commit (https://github.com/scylladb/scylla/commit/bcd41cb32d68d57140c310763bffa6b1befd301a), support to SLES 15 was added to Scylla.

here more info about its current status:
https://github.com/scylladb/scylla/issues/9458

and see here for more info:
https://github.com/scylladb/scylla-cluster-tests/pull/4018#issuecomment-939783833

**Comment by mmatczuk** [comment]
As far as I'm concerned it consumes RPM packages. If that is true it's to be taken care of @yaronkaikov in [scylla-pkg](https://github.com/scylladb/scylla-pkg) repo.

**Comment by yaronkaikov** [comment]
@fgelcer @roydahan Is it a new thing to support SLES15?  is it also for promotion?

**Comment by fgelcer** [comment]
> @fgelcer @roydahan Is it a new thing to support SLES15? is it also for promotion?

you can find more information about it here (https://github.com/scylladb/scylla/commit/bcd41cb32d68d57140c310763bffa6b1befd301a)

**Comment by roydahan** [comment]
> @roydahan , for now we can merge [scylladb/scylla-cluster-tests#4018](https://github.com/scylladb/scylla-cluster-tests/pull/4018) until support to manager agent on SLES 15 will be added, so we don't have to disable the job

Not needed, just disable this job.
