### ISSUE TITLE
docs: generate the sctool docs from command spec

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2930]
In the PR #2929 the sctool docs have been ported to the command itself and a new command `sctool doc` was added to get a yaml description of the command.

Example output of the command [3439750986.zip](https://github.com/scylladb/scylla-manager/files/7582139/3439750986.zip).

In this task we want to write and run a tool that based on the YAML files would recreate the `docs/source/sctool` directory.

Requirements:
* Let's try to preserve the look and feel we have unless we have a better idea, i.e. let's not bucher the docs we want them to look nice.
* We must have command, subcommand and command flag links

**Comment by mmatczuk** [comment]
Related to #2799

@dgarcia360 please take a look.

**Comment by tzach** [comment]
@mmatczuk do usage.yaml have all the relevant info?
Is this a standard format for docs?

**Comment by mmatczuk** [comment]
Check the attached example zip file 3439750986.zip.

**Comment by tzach** [comment]
My question: are this doc in yaml a known Go lib, or something you come up with?
If its the first, we can look for a sphinx extension
If the second, we can build one

**Comment by mmatczuk** [comment]
The file I'm using are a mix of 2 things in a single file:
* The cobra library Command struct and it's field names
* The command flag names thrown into it (to the top level)

Basically this is a map or dict if you like kept in a file.
I doubt you need a formal specification for those things.

**Comment by tzach** [comment]
Thanks. @dgarcia360 I see a (popular) open source Sphinx extension in your future ;)

**Comment by dgarcia360** [comment]
Thanks @mmatczuk!

- Does the command allow to specify the directory where the ``yaml`` files are generated?

- Do you plan to keep the generated ``yaml`` files tracked in the GitHub repo?
   
    If so, we need an additional command option``sctool doc --verify`` to check the yaml files in the remote repository matches the latest version. This command would be run by GitHub Actions on push or PR against the default branch.
    
    In any case, we would need to install ``sctool`` as a dependency to build or verify the command docs. The only benefit in comparison to using [sphinxcontrib-commandoutput](https://github.com/scylladb/scylla-manager/issues/2799#issuecomment-964646649) is that we can customize a bit more how the output would look like.

**Comment by dgarcia360** [comment]
Talking with @tzach, we have commented that:

- The generated ``yaml`` files will live in a folder within the repository.
- To start, we will not verify with GitHub Actions if the files within the folder match the latest sctool version. This is an enhancement we can add in the future (`sctool doc --verify command`).
- I'll submit a PR using the extension https://sphinx-jsonschema.readthedocs.io/en/latest/index.html to turn JSON / YAML files into HTML using a Sphinx directive. If the extension does not fully fit the projects' needs, we will evaluate if we can customize it or create a custom extension.

**Comment by dgarcia360** [comment]
I've been testing the extension https://github.com/sphinx-contrib/datatemplates. Like sphinx-json schema, it lets us import data in different formats (including YAML) and generates HTML. Moreover, it also allows customizing the output using **template files**.

For example, using the following **template for commands**:

**command.tmpl**

``` python
.. -*- mode: rst -*-

{{ data['name'] }}
{{ '=' * data['name']|length  }}

{{ data['description'] }}

Syntax
......

.. code-block:: none

    {{ data['usage'] }}

Options
.......

{{ make_list_table_from_mappings(
    [('Name', 'name'), ('Shorthand', 'shorthand'), ('Default value', 'default_value'), ('Usage', 'usage')],
    data['options'],
    title=''
    ) }}

Inherited options
.................
{{ make_list_table_from_mappings(
    [('Name', 'name'), ('Shorthand', 'shorthand'), ('Default value', 'default_value'), ('Usage', 'usage')],
    data['inherited_options'],
    title=''
    ) }}
```

And, the following directive in an rst file:

**docs/source/sctool/version.rst**

```
.. datatemplate:yaml:: partials/sctool_version.yaml
   :template: command.tmpl
```

The resulting HTML looks like:

![image](https://user-images.githubusercontent.com/9107969/145167426-66f31d3c-4916-43d9-99a1-f38f266c423d.png)

Next, I'll submit a PR with an improved version of the template. It will also add the directive ``datatemplate:yaml`` to every other command-related ``rst`` page.

@mmatczuk  Could you please generate the ``yaml`` files with the command ``sctool doc`` under the folder``docs/source/sctool/partials``, and upload them to the remote repo? The command ``sctool doc`` might need an extra option to define a relative path where the resulting ``yaml`` files are generated. For example:

``sctool doc --output ./docs/source/sctool/partials``

Thanks!

**Comment by tzach** [comment]
> @mmatczuk Could you please generate the yaml files with the command sctool doc under the folderdocs/source/sctool/partials, and upload them to the remote repo? The command sctool doc might need an extra option to define a relative path where the resulting yaml files are generated. For example:
> 
> sctool doc --output ./docs/source/sctool/partials

@dgarcia360 why do we need this? what remote repo?

**Comment by dgarcia360** [comment]
> why do we need this?

Every time the command ``sctool doc`` runs, it generates the ``yaml`` files under a folder with a different name based on the current timestamp (e.g. ``3439750986``). The extension needs at least the folder name to be static (to not change) to be able to reference the files with the directive   `.. datatemplate:yaml:: path/to/a/known/file.yaml`.

> what remote repo?

remote repo != local repo. In short, the version of the repo hosted on GitHub.
This would mean tracking the generated `yaml` files and send a PR with them.

**Comment by tzach** [comment]
Aha
I was under the impression yaml files are part of the source, not the output of sctool
@mmatczuk is it the case? if so, running sctool do need to be apart of the doc build.

**Comment by mmatczuk** [comment]
The docs are of course generated by the command. @dgarcia360 asks to persist the output in git.

**Comment by mmatczuk** [comment]
Generating from YAML makes the most sense in a general case.

A requirement from my end is to have the command parameter name anchor, so that it's possible to send a link that goes directly to a flag.

I'll add the generated files to master shortly.

**Comment by mmatczuk** [comment]
The --output flag is added and the generated files are persisted in master branch in #2959.

**Comment by dgarcia360** [comment]
Thanks @mmatczuk!! 

While trying to render the command's documentation from the YAML files, I noticed the following:

- The commands defined in [Sctool > Task docs](https://manager.docs.scylladb.com/stable/sctool/task.html) do not match the autogenerated YAML files. For example, there is a file  ``sctool_progress.yaml`` for the command ``sctool progress``, but in the docs this command is defined as ``sctool task progress``. Which form is the correct? Is the ``sctool docs`` command not generating the expected YAML files for the task commands, or are the tasks docs outdated?

- The extension we are using to turn the YAML into HTML has issues rendering content within tables when the value has multiple lines. For example:

![image](https://user-images.githubusercontent.com/9107969/146518323-65a2bad1-273e-4a01-ae98-090ec995d9e0.png)

![image](https://user-images.githubusercontent.com/9107969/146518236-a7ba1e06-3340-4390-b4ad-35f8335c6eb7.png)





However, if the YAML value uses this other symbol ">", they render as expected:

![image](https://user-images.githubusercontent.com/9107969/146518449-545cdbc0-a297-4b7b-86c8-f44cf6ff0176.png)

![image](https://user-images.githubusercontent.com/9107969/146518547-5ee12a54-217d-469b-b3b6-46d63c3ec20f.png)

Would it be possible to edit the generator to use ">" instead of "|" for multiline values that fall under the keys ``options`` and ``inherited_options``? Many thanks!

**Comment by mmatczuk** [comment]
The commands were deprecated and moved / changed between 2.X and master.

This is interesting 

```
Scalar content can be written in block notation, using a literal style (indicated by “|”) where all line breaks are significant. Alternatively, they can be written with the folded style (denoted by “>”) where each line break is folded to a space unless it ends an empty or a more-indented line.
```

As this is generated by the tool I guess I cannot change it unless I rewrite them post generation.

I think it makes more sense to replace `: |` with `: >` prior generation in your script.

**Comment by dgarcia360** [comment]
> I think it makes more sense to replace : | with : > prior generation in your script.

Solved! Now I'm using a different template that's not raising these warnings.
