### ISSUE TITLE
docs: update python packages

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#2964]
@dgarcia360 please update the python stack, the versions used happen to have know vulnerabilities.
See https://github.com/scylladb/scylla-manager/security/dependabot for details.

**Comment by tzach** [comment]
@mmatczuk  https://github.com/scylladb/scylla-manager/security/dependabot link is not working
Please send us relevant info over email

**Comment by mmatczuk** [comment]
I closed them in the dashboard because SM is not really affected by it should be fixed anyways.
Here's the working link https://github.com/scylladb/scylla-manager/security/dependabot?q=is%3Aclosed
