### ISSUE TITLE
"sctool cluster list" command fails with "gocql: no response received from cassandra within timeout period" error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-manager#2978]
_Installation details_ 
Kernel version: `5.11.0-1023-gcp` 
Scylla version (or git commit hash): `4.7.dev-0.20211215.3ac622bdd with build-id c19c7740f10f82f554c1b67da69f82fc48f9386f` 
Cluster size: 6 nodes (i3.4xlarge) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos-7 `7091148157460162159` (gcp: us-east1)

Scylla running with shards number (live nodes): 
longevity-10gb-3h-master-db-node-e79c455f-0-1 (104.196.189.45 | 10.142.0.7): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-3 (34.75.56.162 | 10.142.0.35): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-4 (34.139.143.201 | 10.142.0.55): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-5 (34.139.25.79 | 10.142.0.153): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-8 (34.138.206.244 | 10.142.0.30): 16 shards
longevity-10gb-3h-master-db-node-e79c455f-0-9 (34.75.229.123 | 10.142.0.107): 16 shards

Terminated nodes:
longevity-10gb-3h-master-db-node-e79c455f-0-2	(34.139.75.117 | 10.142.0.16): 16 shards, terminated at 2021-12-15 10:37:17.942850
longevity-10gb-3h-master-db-node-e79c455f-0-6	(34.138.78.99 | 10.142.0.156): 16 shards, terminated at 2021-12-15 11:28:20.562269
longevity-10gb-3h-master-db-node-e79c455f-0-7	(34.73.16.92 | 10.142.0.76): 16 shards, terminated at 2021-12-15 11:45:35.004150

Test: `longevity-10gb-3h-gce-test` Test name: `longevity_test.LongevityTest.test_custom_time` Test config file(s):

* [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c5564161c573430b1ee2042445a66c775f8ce483/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description** 
One single run twice failed (MgmtRepairCli and MgmtBackup nemesis) to run `sudo sctool cluster list` command with the following error:
```
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: Ei4lBZz0TECMXV6ftAW0pg (grep in scylla-manager logs)
```

```
Command: 'sudo sctool cluster list'
Exit code: 1
Stdout:
Stderr:
Error: list clusters: gocql: no response received from cassandra within timeout period
Trace ID: wnLnTqcsTCaWy1YAJ5Ck6A (grep in scylla-manager logs)
```

Manager version: `3.0-dev-0.20211214.d2dce13a92c-SNAPSHOT-d2dce13a92c`
Agent version: `3.0-dev-0.20211214.d2dce13a92c-SNAPSHOT-d2dce13a92c`

Restore Monitor Stack command: `$ hydra investigate show-monitor e79c455f-5ba7-4d17-a163-72c141f2c9c0` 
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e79c455f-5ba7-4d17-a163-72c141f2c9c0) 
Show all stored logs command: `$ hydra investigate show-logs e79c455f-5ba7-4d17-a163-72c141f2c9c0`

Test id: `e79c455f-5ba7-4d17-a163-72c141f2c9c0`

Logs: 
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/db-cluster-e79c455f.tar.gz 
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/loader-set-e79c455f.tar.gz 
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/monitor-set-e79c455f.tar.gz 
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/e79c455f-5ba7-4d17-a163-72c141f2c9c0/20211215_131604/sct-runner-e79c455f.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-10gb-3h-gce-test/105)

**Comment by fgelcer** [comment]
@mmatczuk , could it be the same as #2888 ?

**Comment by karol-kokoszka** [comment]
Closing in favor of #2888
