### ISSUE TITLE
sctool not available in docker image when running latest | 2.5.4

### ISSUE THREAD

**Issue by tuddman** [scylladb/scylla-manager#2989]
Following this guide:  https://manager.docs.scylladb.com/stable/docker/index.html

step 6:
```
sctool cluster add --name test --host=scylla --auth-token=token

bash sctool not found
```

downgrading to set the image in the `docker-compose.yml` to  `scylla-manager:2.5.3`  (rather than the default `latest`) resolved the issue.

**Comment by mmatczuk** [comment]
Latest is probably not 2.5 but 2.6.

Related to #2897

**Comment by tuddman** [comment]
It is now. Confirming `2.6` docker image contains `sctool` and works as expected. The cluster was joined automatically. So maybe need to update the docs to reflect the new behavior.
