### ISSUE TITLE
docs: sctool, do not add Inherited options to every command

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3007]
The sctool docs are littered by `Inherited options` that really are what we have in `Global flags and variables`.

I suggest we update the Global flags and variables section with the new data, and remove the Inherited options from the template.

**Comment by mmatczuk** [comment]
@dgarcia360 PTAL

**Comment by dgarcia360** [comment]
I'm  considering [adding a collapsible component](https://github.com/scylladb/sphinx-scylladb-theme/issues/276) to hide "inherited options". What do you think?

**Comment by mmatczuk** [comment]
That could work, you can then remove the Global flags section IMO.

This is a more flexible approach.
