### ISSUE TITLE
docs: sctool, update docstrings

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-manager#3009]
## Motivation

Originally posted in https://github.com/scylladb/scylla-manager/pull/2987

We could modify the sctool docstrings to help Sphinx render the content nicely.

## Proposal

1. Sphinx needs a special character to detect lists. For example:

```
    '*' - matches any number of any characters including none
    '?' - matches any single character
    '[abc]' - matches one character given in the bracket
    '[a-z]' - matches one character from the range given in the bracket
```

Must be:

```
    * '*' - matches any number of any characters including none
    * '?' - matches any single character
    * '[abc]' - matches one character given in the bracket
    * '[a-z]' - matches one character from the range given in the bracket
```

2. To highlight inline-code (e.g. ``abc``), replace the single quotes as follows ``'abc'`` -> ` ``[abc]`` `.

## Implementation

@mmatczuk With your help, I'm happy to take this issue.

**Comment by mmatczuk** [comment]
The thing is that this is also command help as printed in terminal so it's more natural to use - for instance.

Having said that:
* The `*` are preserved in the command yaml (the original) and there is text processing to remove them
* Single quotes have been introduced recently to replace double `, it can be easily reverted

**Comment by mmatczuk** [comment]
I'd update the input files.
