### ISSUE TITLE
rpm: manager 2.6 package doesn't allow 'scylla-manager' user to write to '/var/lib/scylla-manager'

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3014]
Seems that RPM for scylla-manager-2.6 doesn't allow 'scylla-manager' write access to '/var/lib/scylla-manager' folder. 
In cloud, we use this folder to store certificates here.
Manager 2.6 won't start without this permission.

I understand this as a bug, and will keep this issue as a blocker for "support for Manager 2.6 in cloud".

**Comment by mmatczuk** [comment]
I can confirm that in docker centos image

```
[root@9d91ad3830c1 release]# ls -al /var/lib/scylla-manager
total 24
drwxr-xr-x 2 root           root           4096 Jan 31 14:05 .
drwxr-xr-x 1 root           root           4096 Jan 31 14:12 ..
-rw-r--r-- 1 scylla-manager scylla-manager   18 Jan 12  2021 .bash_logout
-rw-r--r-- 1 scylla-manager scylla-manager  141 Jan 12  2021 .bash_profile
-rw-r--r-- 1 scylla-manager scylla-manager  376 Jan 12  2021 .bashrc
```

The directory is added with `/usr/sbin/useradd -g scylla-manager -d /var/lib/scylla-manager -m -s /usr/sbin/nologin -r scylla-manager > /dev/null`

**Comment by mmatczuk** [comment]
It looks like there is a change in `useradd` command parameter handling.

Below examples come from CentOS 9

```
[root@9d91ad3830c1 release]# ls -al /var/lib/scylla-manager*
/var/lib/scylla-manager:
total 24
drwxr-xr-x 2 root           root           4096 Jan 31 14:05 .
drwxr-xr-x 1 root           root           4096 Jan 31 14:18 ..
-rw-r--r-- 1 scylla-manager scylla-manager   18 Jan 12  2021 .bash_logout
-rw-r--r-- 1 scylla-manager scylla-manager  141 Jan 12  2021 .bash_profile
-rw-r--r-- 1 scylla-manager scylla-manager  376 Jan 12  2021 .bashrc
```

With `-b` instead of `-d` in `useradd -g scylla-manager -b /var/lib -m -s /usr/sbin/nologin -r scylla-manager1` we see that the directories have correct ownership. 

```
/var/lib/scylla-manager1:
total 24
drwx------ 2 scylla-manager1 scylla-manager 4096 Jan 31 14:18 .
drwxr-xr-x 1 root            root           4096 Jan 31 14:18 ..
-rw-r--r-- 1 scylla-manager1 scylla-manager   18 Jan 12  2021 .bash_logout
-rw-r--r-- 1 scylla-manager1 scylla-manager  141 Jan 12  2021 .bash_profile
-rw-r--r-- 1 scylla-manager1 scylla-manager  376 Jan 12  2021 .bashrc
```

@karol-kokoszka note that this has no impact on the upgrade workflow, if user exists the useradd command is not invoked.

**Comment by karol-kokoszka** [comment]
@mmatczuk I saw the change is merger to 2.6 branch but is there a chance to regenerate RPMs from http://downloads.scylladb.com/downloads/scylla-manager/rpm/centos/scylladb-manager-2.6/ ?
We still can't progress with adding support for this version in cloud without it.
