### ISSUE TITLE
backup: restore, generate template input file to restore ansible script

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3015]
The purpose of this task is making `scylla-manager-agent download-files` generate restore script input files, namely
* hosts ([example](https://github.com/scylladb/scylla-manager/blob/master/ansible/restore/hosts.example))
* vars ([example](https://github.com/scylladb/scylla-manager/blob/master/ansible/restore/vars.yaml.example))

Input for the new functionality is backup location and snapshot tag. The snapshot tag can specified declaratively as latest snapshot before date X.

It can work in two modes:
* Offline
* Online

In offline mode we generate only `vars.yaml` template, providing location, snapshot tag and source host without specifying target hosts.

In online mode we extend vars with the actual host mapping and we generate the hosts listing.
The source of information about the new cluster is the Scylla instance API.

If the new cluster has different nr of nodes than what we have in snapshot manifests error is reported.

**Comment by karol-kokoszka** [comment]
We do not want to invest our effort into the ansible script.
Restore should be made directly through the manager since 3.1 release.
