### ISSUE TITLE
dist: fix docker building

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3052]
The docker builds fail now due to 

```
 > [4/4] RUN dpkg -i scylla-manager-agent*.deb && rm /scylla-manager-agent*.deb:
```

This is caused by building for multiple architectures.
It needs to be adjusted see the docs https://goreleaser.com/customization/docker/.

@yaronkaikov how come this is not an issue in our release pipeline.

**Comment by karol-kokoszka** [comment]
@yaronkaikov is this issue still valid ? Do you encounter any error building the docker for scylla-manager-agent ?

**Comment by yaronkaikov** [comment]
I don't think it's valid anymore. Closing
