### ISSUE TITLE
Unable to get repair task to work / 502 bad gateway

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla-manager#3059]
This is a recent new install of Scylla Manager 2.6 and Scylla 5.0 rc1 on arm64 instances.

I've followed all the install guides as best I can, and I have the Manager health checks and a daily backup task to S3 working ok.

However when I try to get the repair task to start, it errors out, with messages in /var/log/syslog where it is receiving 502 Bad Gateway from a metrics URL. The messages look like this:

> Feb 24 21:10:17 ip-172-31-112-5 scylla-manager[19437]: {"L":"INFO","T":"2022-02-
> 24T21:10:17.254-0500","N":"cluster.client","M":"HTTP","host":"172.31.128.6:10001
> ","method":"GET","uri":"/metrics?name=database_total_writes","duration":"0ms","s
> tatus":502,"bytes":0,"dump":"HTTP/1.1 502 Bad Gateway\r\nDate: Fri, 25 Feb 2022
> 02:10:17 GMT\r\nContent-Length: 0\r\n\r\n","_trace_id":"bVmh4smsTA--oU825_d4ow"}

I can't tell if this is a bug, or if I have something misconfigured? I did recently setup a different superuser account on the cluster and deleted the cassandra user, but I did update the Manager config to have the new superuser username/password info. Connections to port 10001 on the Scylla nodes are reachable, I have verified with curl and also as I mentioned the sctool healthcheck and backup tasks work ok.

**Comment by mmatczuk** [comment]
Bad Gateway is a proxy error, check the agent logs, most likely the SM agent cannot access the Scylla prometheus IP / port.

**Comment by A-Posthuman** [comment]
Thanks for the info, I am a newbie with Scylla and Manager, so this was helpful. I tracked down via some curl probing that from each Scylla node they were able to reach port 9180 via their AWS private IP, but not via 127.0.0.1. This is despite what I read in the Scylla monitoring docs that it is not necessary to define the Prometheus ports to listen to in scylla.yaml, because by default it should listen on all available IPs?

Nevertheless after adding lines to scylla.yaml on each node:

prometheus_port: 9180
prometheus_address: 0.0.0.0

then I could access 9180 via curl to 127.0.0.1, and also Manger's repair task was able to work normally.

Perhaps this is a bug in the documentation here:

https://docs.scylladb.com/operating-scylla/monitoring/2.3/monitoring-apis/

Although I don't even find mention of these prometheus config options in the default scylla.yaml file or here:

https://docs.scylladb.com/operating-scylla/scylla-yaml/

So these config options seem a bit obscure and hard to know about. Would it be better if the Manager agents would try to access the Prometheus port via the node's local IP instead of 127.0.0.1 ?

**Comment by mmatczuk** [comment]
The address is taken from Scylla API on Manager Agent start.
