### ISSUE TITLE
Cannot update automatically created repair: `Error: accepts at most 1 arg(s), received 2`

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3066]
Manager build: http://downloads.scylladb.com/manager/relocatable/unstable/branch-3.0/2022-03-05T21:57:56Z/scylla-manager_3.0-dev-0.20220305.e0ef361ca85.linux_x86_64.tar.gz

When trying to update the automatically created repair task (specifically disable it) the command fails with the following:
```
sctool --api-url http://127.0.67.1:5080/api/v1 repair update repair/all-weekly --enabled false --cluster 7f393bae-5893-4b86-9ab3-7220a9014b54

Error: accepts at most 1 arg(s), received 2
```
Is this the correct syntax?

**Comment by kevinbarbour** [comment]
Because the `--enabled` flag does not take an argument it is taking `false` to be an additional argument to the update action. It works when using `--enabled=false`.

**Comment by ShlomiBalalis** [comment]
`--enabled false` worked (and still works) on manager 2.6

**Comment by rjeczalik** [comment]
@ShlomiBalalis `--enabled=false`

**Comment by kevinbarbour** [comment]
As discussed in the manager status meeting this morning - this change in behaviour is due to changing which library we use to parse command line flags. This will be the case for all such boolean toggle flags used in the manager.
