### ISSUE TITLE
backup: add optimization for fully replicated data

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3070]
Given a keyspace with RF=n and n nodes i.e. if all nodes contain all tokens, we could backup only a single node per DC.

This should be opt-in with a flag to backup.

**Comment by mmatczuk** [comment]
cc @tzach

**Comment by mmatczuk** [comment]
How would a token deduplication work?

**Comment by karol-kokoszka** [comment]
Closing as `wont-fix`.

> Once we move to strong consistency with Raft, we can revisit the backup, even introduce point in time backup.

to be discussed on planning
