### ISSUE TITLE
Attempting to create a task with a reverse time window (end first, start after) does not result in a failure

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3073]
Client version: 3.0-dev-0.20220305.e0ef361ca85

Trying to execute `sctool repair --window 11:09,11:06 --cluster a68d36f0-7860-4417-b35b-642590b8a161`, i.e. with an impossible time window, should end in failure. But instead the task is created normally.

**Comment by kevinbarbour** [comment]
@ShlomiBalalis 

Can you share the exact command you are using when you try to create a task with an odd number of window indicators which succeeds? I receive the following failure and the task does not get created:

```
➜  scylla-manager git:(master) sctool repair --window 11:27,11:24,11:23 --cluster my-cluster
Error: malformed request: window: number of points must be even
Trace ID: Z887ofZMSDaLgrx-817ruQ (grep in scylla-manager logs)
```

**Comment by kevinbarbour** [comment]
The start time being after the end time is actually a valid window.

Say for example you want to run something only in the evenings between 23:00 and 02:00, your window can be `23:00,02:00`.

Your example, though probably not a window anyone would want to use, is still valid. It will begin the execution window at 11:09 each day and end the window at 11:06 the following day.

**Comment by ShlomiBalalis** [comment]
I see. Makes sense!
