### ISSUE TITLE
Sctool fails when updating healthcheck task: unknown shorthand flag: 'c' in -c

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3084]
Manager version: 3.0-dev-0.20220402.bd72c550f37
When trying to update the default (cql) healthcheck, I run into the following error:
`sctool --api-url http://127.0.74.1:5080/api/v1 healthcheck update healthcheck/cql -c 0af16e55-08fe-4ada-a235-a01ec2e5d3c2 --num-retries=2`
`Error: unknown shorthand flag: 'c' in -c`

I tried using the full flag to see if the issue is specific to the shorthand, but it yielded the same result:
`sctool --api-url http://127.0.73.1:5080/api/v1 healthcheck update healthcheck/cql --cluster 98fd34ba-6015-44e4-99b9-7748cdc0a2c5 --num-retries=2`
`Error: unknown flag: --cluster`

I also tried to execute the command without the cluster specification at all, just to see if it will be able to handle it, but then it doesn't recognize the num retries flag at all:
`sctool --api-url http://127.0.58.1:5080/api/v1 healthcheck update healthcheck/cql --num-retries=2`
`Error: unknown flag: --num-retries`

Am I doing something wrong with the command?

**Comment by kevinbarbour** [comment]
`healthcheck` is not a command recognised by sctool. 

```
➜  scylla-manager git:(branch-3.0) ✗ ./sctool help
[...]
Available Commands:
  backup      Schedule a backup (ad-hoc or scheduled)
  cluster     Add or delete clusters
  completion  Generate shell completion
  help        Help about any command
  info        Show task parameters and history
  progress    Show the task progress
  repair      Schedule a repair (ad-hoc or scheduled)
  resume      Undo suspend
  start       Start executing a task
  status      Show status of clusters
  stop        Stop executing a task
  suspend     Stop execution of all tasks
  tasks       Show active tasks and their last run status
  version     Show version information
```

Is this something you were able to do pre-3.0?

**Comment by ShlomiBalalis** [comment]
Before 3.0 I used to update it with `task update`, but since this command was changed to require the type of the task instead of the word `task` (like `sctool backup update`) I figured the same was true about healthcheck

**Comment by kevinbarbour** [comment]
Since this is a rather rare use case we are not adding an additional command for creating/updating healthchecks, but you can continue to use the deprecated `task update` command for situations where this is needed.

**Comment by ShlomiBalalis** [comment]
If the ability to update and creating a healthcheck task is gone, we won't test for it by force. I just need to make sure that if we remove it it is done intentionally

**Comment by kevinbarbour** [comment]
Got it. Yes in this case it was removed intentionally.

**Comment by ShlomiBalalis** [comment]
BTW, not having the healthcheck command is perfectly fine, but I think the error message should be a bit more clear. It should refer to the lack of `healthcheck` command, not the -c flag
