### ISSUE TITLE
scheduler: use generics

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3117]
Both [Key and Properties](https://github.com/scylladb/scylla-manager/blob/660630e9125e5c712f336e04bd17d6b2faf41d7d/pkg/scheduler/scheduler.go#L16) were designed to be replaced by a generic type.

**Comment by Michal-Leszczynski** [comment]
```go
func (s *Scheduler[K, P]) newRunContextLocked(a Activation[K, P]) *RunContext[K, P] {
	var p P
	if a.Properties != nil {
		p = a.Properties
	} else {
		p = s.details[a.Key].Properties
	}
```
Do you happen to know whether perhaps this `if` is only an optimization and we could always set `p` as in the `else` branch?
Are there cases when `s.details[a.Key].Properties` is not set and `a.Properties` is set?

If that's not true, then is replacing comparison to `nil` with `reflect.IsZero()` acceptable approach? By looking at the code I can't tell in which cases `properties` are for sure set and where they are not initialized. This approach should work just fine with the initial type `json.RawMessage`, but of course it could fail in different cases.

Another idea would be to hold additional boolean variable in the struct, but then keeping it up to date might be an issue.

**Comment by Michal-Leszczynski** [comment]
@mmatczuk
