### ISSUE TITLE
scyllaclient: add metrics on retry

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3125]
We need to add a metric that would allow to see endpoint HTTP status codes.
I'm interested in understanding retry causes.

**Comment by karol-kokoszka** [comment]
Seems we are just logging these codes now https://github.com/scylladb/scylla-manager/issues/3451
Let's change the log level for these API calls to DEBUG and just log ERROR.

HTTP status codes to be visualized in metric.

**Comment by mykaul** [comment]
I thought it is already supposed to be in DEBUG level, by default (unless there's a 400 or above error level) - looking at https://github.com/scylladb/scylla-manager/blob/c40041e783ebdb6e2f71f3e9f9f7f79ab8825f17/pkg/scyllaclient/log.go#L27 (perhaps I'm looking at the wrong location?)
