### ISSUE TITLE
scylla-manager docker image 2.5.4 doesn't have sctool

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-manager#3147]
`Scylla-manager` docker image with `2.5.4` tag has no `sctool` binary:

```
$ docker run -d scylladb/scylla-manager:2.5.4
74abe7b65baac185640e8dce9e7cb8d2e280a28e77d8d27afea4589d1c62701f

$ docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS              PORTS     NAMES
74abe7b65baa   scylladb/scylla-manager:2.5.4   "/usr/bin/scylla-man…"   4 seconds ago        Up 3 seconds                  sweet_meitner

$ docker exec -it 74abe7b65baa /bin/bash     
scylla-manager@74abe7b65baa:/$ sctool
bash: sctool: command not found
```

Also, the image of that version is much smaller than previous `2.5.x` versions:

![2022-05-05--scylla-manager-2-5-4-no-sctool](https://user-images.githubusercontent.com/3796058/166952595-858c9f2f-5418-4e52-9e3f-989758699042.png)

In version `2.5.3` the `sctool` binary has following size:

```
$ ls -lah /usr/bin/sctool
-rwxr-xr-x 1 root root 31M Nov 24 09:04 /usr/bin/sctool
```

So, either this version should be removed from the dockerhub or newer fixed one must be released for the 2.5.x branch

**Comment by karol-kokoszka** [comment]
Closing as "wont-fix".

2.5.4 is the old version of scylla-manager.
The latest release is 3.1.1.

This kind of issue should be reported to github.com/scylladb/scylla-pkg
