### ISSUE TITLE
dist: adjust the minimal Scylla backend db memory to the recommendation 

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3176]
The [recommendation](https://docs.scylladb.com/getting-started/system-requirements/) is to use 256M per node or 1G whichever is greater. In our case we use 100M and 1 shard. The node hardly gets load from SM and we want to save on memory but we should adjust the per node quotas.

**Comment by karol-kokoszka** [comment]
Estmation: 1

**Comment by karol-kokoszka** [comment]
Done with https://github.com/scylladb/scylla-manager/commit/fcee6cc94e5f21682bb74dd35b08c7f22ad59d9e
