### ISSUE TITLE
Automated task schedule planner

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3180]
In some clusters we can observe a usage pattern - load spikes that repeat with daily / weekly cadence.

Given:
* distribution of run times of a backup / repair task for last N runs,
* desired cadence of backup / repair task,
* load samples from cluster nodes.

We can find start time that based on historical data with think would minimize the aggregated load over the duration of a task.

**Comment by mmatczuk** [comment]
cc @tzach

**Comment by karol-kokoszka** [comment]
The only automated tasks that are created whenever cluster is added to scylla manager are:

```
➜  scylla-manager git:(master) ✗ ./sctool cluster add --host 192.168.200.11 --auth-token token --username cassandra --password cassandra 
ea031891-0357-436c-acea-9fb7f1661a90
 __  
/  \     Cluster added! You can set it as default, by exporting its name or ID as env variable:
@  @     $ export SCYLLA_MANAGER_CLUSTER=ea031891-0357-436c-acea-9fb7f1661a90
|  |     $ export SCYLLA_MANAGER_CLUSTER=<name>
|| |/    
|| ||    Now run:
|\_/|    $ sctool status -c ea031891-0357-436c-acea-9fb7f1661a90
\___/    $ sctool tasks -c ea031891-0357-436c-acea-9fb7f1661a90
➜  scylla-manager git:(master) ✗ ./sctool tasks
Cluster:  (ea031891-0357-436c-acea-9fb7f1661a90)
╭────────────────────────┬──────────────┬────────┬───────────────┬─────────┬───────┬──────────────┬────────────┬────────┬─────────────────────────╮
│ Task                   │ Schedule     │ Window │ Timezone      │ Success │ Error │ Last Success │ Last Error │ Status │ Next                    │
├────────────────────────┼──────────────┼────────┼───────────────┼─────────┼───────┼──────────────┼────────────┼────────┼─────────────────────────┤
│ healthcheck/cql        │ @every 15s   │        │ Europe/Warsaw │ 0       │ 0     │              │            │ NEW    │ 10 Jul 23 11:10:58 CEST │
│ healthcheck/rest       │ @every 1m0s  │        │ Europe/Warsaw │ 0       │ 0     │              │            │ NEW    │ 10 Jul 23 11:11:43 CEST │
│ healthcheck/alternator │ @every 15s   │        │ Europe/Warsaw │ 0       │ 0     │              │            │ NEW    │ 10 Jul 23 11:10:58 CEST │
│ repair/all-weekly      │ 0 23 * * SAT │        │ Europe/Warsaw │ 0       │ 0     │              │            │ NEW    │ 15 Jul 23 23:00:00 CEST │
╰────────────────────────┴──────────────┴────────┴───────────────┴─────────┴───────┴──────────────┴────────────┴────────┴─────────────────────────╯

```

Sctool moves all the responsibility of scheduling the backup/(other) repair tasks to the end user by introducing `--cron` flag -> https://manager.docs.scylladb.com/stable/sctool/backup.html#cron together with the `--window` flag -> https://manager.docs.scylladb.com/stable/sctool/backup.html#window

I understand that it would be nice to introduce another variables helping to schedule the task.

Let me triage it as `grooming-needed` and we will revisit the way how we schedule and how do we want to schedule.

Desing doc of maintenance windows https://docs.google.com/document/d/1p_bkMh7VNrDwzPmeEgnt3cWBgVY3mT-g0KCNOy9ReQU/edit#heading=h.f96zmiyl6np3
