### ISSUE TITLE
Do not run backup or repair when load is high

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-manager#3181]
The idea is to prevent running backup on occasional load spike. It's a lightweight version of #3180. 
#Related is https://github.com/scylladb/scylla-enterprise/issues/2268.

The implementation idea:
- Add configuration options in the configuration file that would allow to specify max load when starting backup and repair
- On start check relevant node metrics and validate them against the the threshold
- If nok return an error, scheduler would backoff and retry

This could be also helpful with https://github.com/scylladb/scylla-enterprise/issues/2196 @AdamStawarz

**Comment by karol-kokoszka** [comment]
The implementation idea looks great.
The only additional info I want to put here is the exact metric that I'm gonna check.
It's `avg(scylla_reactor_utilization)`. Exactly the same we use in scylla-monitoring to show the load.

**Comment by karol-kokoszka** [comment]
Edge case - what to do when the load (got from metrics) never goes down ?

Triaged `grooming-needed`

**Comment by karol-kokoszka** [comment]
Let's keep it in the backlog, but the time perspective for this task is currently unknown.

**Comment by Michal-Leszczynski** [comment]
Similar to #3770.

**Comment by avikivity** [comment]
IMO this shouldn't be implemented. The cluster should have 20% spares for maintenance. If it doesn't, it should be scaled up.

Deferring maintenance due to load is dangerous. You don't know if the load will drop.

**Comment by Michal-Leszczynski** [comment]
The idea would be to have some defer counter, so that we would defer backup execution by 0.5h at most twice (example config). Backup would be executed as usual even if the load is still high after those defers.

But it still creates some problems with tasks scheduled with `--window` or are executed really often, so maybe the risk is greater than the reward.

**Comment by karol-kokoszka** [comment]
Let's close it.
