### ISSUE TITLE
[operator] repair job without schedule get rerun multiple times

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-manager#3184]
### Installation details
Kernel version: `5.4.196-108.356.amzn2.x86_64`
Scylla version (or git commit hash): `5.1.dev-0.20220625.78750c2e1a45 with build-id 93b6ca8b258edda016a94430c4b109d5affd898e`
Cluster size: 3 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   sct-cluster-us-east1-b-us-east1-0 (10.0.3.144 | 10.0.3.217): 15 shards
   sct-cluster-us-east1-b-us-east1-1 (10.0.0.61 | 10.0.1.158): 15 shards
   sct-cluster-us-east1-b-us-east1-2 (10.0.1.51 | 10.0.1.96): 15 shards
Scylla running with shards number (terminated nodes):
   sct-cluster-us-east1-b-us-east1-1-0 (10.0.3.184 | 10.0.2.42): 15 shards
   sct-cluster-us-east1-b-us-east1-1-0 (10.0.1.51 | 10.0.2.127): 15 shards
   sct-cluster-us-east1-b-us-east1-1-0 (10.0.1.51 | 10.0.1.96): 15 shards
   sct-cluster-us-east1-b-us-east1-2 (10.0.3.184 | 10.0.2.82): 15 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (k8s-eks: eu-north-1)

Test: `longevity-scylla-operator-basic-12h-eks`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-scylla-operator-basic-12h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/bed2431696438a3757203be902753683d85520bf/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/bed2431696438a3757203be902753683d85520bf/test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml&source=gmail-html&ust=1656427789584000&usg=AOvVaw1NGUxVamL1UAhi3meq4Xxg))

### Issue description

Running SCT ontop of EKS with operator, on repair job get rerun, again and again, causing the next repair tasks to fail cause of that
logs of the manager are in `kubernetes` zip file (also the agents)

```
< t:2022-06-26 17:50:56,326 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "sctool tasks -c b2b48c41-690b-4630-99bd-6f91e2393802" finished with status 0
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > sctool output: +-----------------------------------+-------------+--------+----------+---------+-------+--------------+------------+-------------+----------+
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | Task                              | Schedule    | Window | Timezone | Success | Error | Last Success | Last Error | Status      | Next     |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > +-----------------------------------+-------------+--------+----------+---------+-------+--------------+------------+-------------+----------+
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/alternator            | @every 15s  |        | UTC      | 2608    | 4     | 1s ago       | 30m1s ago  | DONE        | in 13s   |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/rest                  | @every 1m0s |        | UTC      | 657     | 0     | 5s ago       |            | DONE        | in 54s   |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/cql                   | @every 15s  |        | UTC      | 2621    | 2     | 0s ago       | 1h33m ago  | DONE        | in 14s   |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | repair/default-repair-task-name   |             |        |          | 4       | 5     | 17m53s ago   | 7m43s ago  | RUNNING     |          |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | repair/default-repair-task-name-2 |             |        |          | 0       | 1     |              | 32s ago    | ERROR (0/3) | in 9m27s |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | repair/default-repair-task-name-1 |             |        |          | 2       | 2     | 6m16s ago    | 32s ago    | ERROR (0/3) | in 9m27s |
< t:2022-06-26 17:50:56,326 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > +-----------------------------------+-------------+--------+----------+---------+-------+--------------+------------+-------------+----------+
```

I have job repair/default-repair-task-name which doesn't have a schedule set, at a certain point it was in DONE status:
```
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > sctool output: +---------------------------------+-------------+--------+----------+---------+-------+--------------+--------------+--------+--------+
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | Task                            | Schedule    | Window | Timezone | Success | Error | Last Success | Last Error   | Status | Next   |
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+--------------+--------------+--------+--------+
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/alternator          | @every 15s  |        | UTC      | 1831    | 2     | 5s ago       | 2h50m20s ago | DONE   | in 9s  |
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/rest                | @every 1m0s |        | UTC      | 461     | 0     | 54s ago      |              | DONE   | in 5s  |
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/cql                 | @every 15s  |        | UTC      | 1839    | 1     | 4s ago       | 2h50m14s ago | DONE   | in 10s |
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > | repair/default-repair-task-name |             |        |          | 1       | 0     | 29s ago      |              | DONE   |        |
< t:2022-06-26 14:34:15,225 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+--------------+--------------+--------+--------+
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 4d12ed48-5880-4204-97bc-52fff98f5d46`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=4d12ed48-5880-4204-97bc-52fff98f5d46)
Show all stored logs command: `$ hydra investigate show-logs 4d12ed48-5880-4204-97bc-52fff98f5d46`

Test id: `4d12ed48-5880-4204-97bc-52fff98f5d46`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_080454/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_080454-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_080454/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_080454-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_081420/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_081420-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_081420/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_081420-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_092804/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_092805-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_092804/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_092805-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_103637/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_103638-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_103637/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_103638-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_104511/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_104512-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_104511/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_104512-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_111925/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_111925-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_111925/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_111925-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_130443/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_130443-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_130443/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_130443-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_131304/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_131304-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_131304/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_131304-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_143415/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_143415-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_143415/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_143415-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_144723/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_144723-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_144723/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_144723-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_145701/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_145701-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_145701/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_145701-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_151516/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_151516-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_151516/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_151516-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_193441/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_193442-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_193441/grafana-screenshot-longevity-scylla-operator-basic-12h-eks-scylla-per-server-metrics-nemesis-20220626_193442-longevity-scylla-operator-basic-3h--monitor-node-4d12ed48-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/db-cluster-4d12ed48.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/db-cluster-4d12ed48.tar.gz)
kubernetes - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/kubernetes-4d12ed48.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/kubernetes-4d12ed48.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/loader-set-4d12ed48.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/loader-set-4d12ed48.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/monitor-set-4d12ed48.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/monitor-set-4d12ed48.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/sct-runner-4d12ed48.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4d12ed48-5880-4204-97bc-52fff98f5d46/20220626_194442/sct-runner-4d12ed48.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-basic-12h-eks/13/)

**Comment by fruch** [comment]
just for reference (for other that might encounter it), this is how the error looks at SCT side:
```
2022-06-26 17:50:56.327: (DisruptionEvent Severity.ERROR) period_type=end event_id=988e7374-c4a3-4a75-8993-fddaf047edf0 duration=1m9s: nemesis_name=MgmtRepairCli target_node=Node sct-cluster-us-east1-b-us-east1-2 [10.0.1.51 | 10.0.2.127] (seed: False) errors=Task: repair/default-repair-task-name-2 final status is: ERROR.
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3429, in wrapper
result = method(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 171, in wrapped
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2161, in disrupt_mgmt_repair_cli
assert task_final_status == TaskStatus.DONE, 'Task: {} final status is: {}.'.format(
AssertionError: Task: repair/default-repair-task-name-2 final status is: ERROR.
```

**Comment by mmatczuk** [comment]
```
  repairs:
  - intensity: "1"
    interval: "0"
    name: default-repair-task-name
    numRetries: 3
    parallel: 0
    smallTableThreshold: 1GiB
    startDate: now
  - intensity: "1"
    interval: "0"
    name: default-repair-task-name-1
    numRetries: 3
    parallel: 0
    smallTableThreshold: 1GiB
    startDate: now
  - intensity: "1"
    interval: "0"
    name: default-repair-task-name-2
    numRetries: 3
    parallel: 0
    smallTableThreshold: 1GiB
    startDate: now
```

So we have the following spec that supposedly should indicate one shot job.


Scylla Manager logs in Kubernetes are weird

```
 michal@lh:Downloads/kubernetes-4d12ed48$ grep scheduler scylla_manager.log 
{"L":"INFO","T":"2022-06-26T06:51:51.040Z","N":"scheduler","M":"PutTask","task":"healthcheck/e748be8d-a318-4a92-a63e-3e312f739093","schedule":{"cron":"@every 15s","window":null,"timezone":"UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":0,"retry_wait":""},"properties":{"mode":"cql"},"create":true,"_trace_id":"ML1V8VrhT-uxnnIAoyO6bA"}
{"L":"INFO","T":"2022-06-26T06:51:51.041Z","N":"scheduler","M":"PutTask","task":"healthcheck/7cdfcd7d-357d-49ac-b1da-39e80dcd3681","schedule":{"cron":"@every 1m0s","window":null,"timezone":"UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":0,"retry_wait":""},"properties":{"mode":"rest"},"create":true,"_trace_id":"ML1V8VrhT-uxnnIAoyO6bA"}
{"L":"INFO","T":"2022-06-26T06:51:51.043Z","N":"scheduler","M":"PutTask","task":"healthcheck/25cf94d0-5c95-4a59-9210-82f2de02259b","schedule":{"cron":"@every 15s","window":null,"timezone":"UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":0,"retry_wait":""},"properties":{"mode":"alternator"},"create":true,"_trace_id":"ML1V8VrhT-uxnnIAoyO6bA"}
{"L":"INFO","T":"2022-06-26T06:51:51.045Z","N":"scheduler","M":"PutTask","task":"repair/8a419ff4-61dd-4308-93f3-5920ddceb4e9","schedule":{"cron":"0 23 * * SAT","window":null,"timezone":"UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":3,"retry_wait":""},"properties":{},"create":true,"_trace_id":"ML1V8VrhT-uxnnIAoyO6bA"}
{"L":"INFO","T":"2022-06-26T06:51:51.047Z","N":"scheduler.b2b48c41","M":"Schedule","task":"repair/8a419ff4-61dd-4308-93f3-5920ddceb4e9","in":"160h8m8s","begin":"2022-07-02T23:00:00.000Z","retry":0,"_trace_id":"ML1V8VrhT-uxnnIAoyO6bA"}
{"L":"INFO","T":"2022-06-26T06:51:51.081Z","N":"scheduler","M":"Task deleted","cluster_id":"b2b48c41-690b-4630-99bd-6f91e2393802","task_type":"repair","task_id":"8a419ff4-61dd-4308-93f3-5920ddceb4e9","_trace_id":"s5DF1gxXTHqTsr-nLam8jQ"}
```

Only single repair task, expected 3, clearly not the one expected in the spec.

**Comment by fruch** [comment]
@vponomaryov do we have code that restart the manager server, for some reasons ? do you have an idea why we won't have all the manger logs ?

**Comment by vponomaryov** [comment]
> @vponomaryov do we have code that restart the manager server, for some reasons ? do you have an idea why we won't have all the manger logs ?

Restart of pods is common thing in K8S which is done by variety of controllers.
The full scylla manager log is located in the root of the `kubernetes` logs. So, need to look there if the log from latest pod is not enough.
