### ISSUE TITLE
 github.com/scylladb/scylla-manager/v3 isn't go-gettable

### ISSUE THREAD

**Issue by mrVanboy** [scylladb/scylla-manager#3198]
## Context

Go modules have specific rules on file naming in the repo. The [particular one we are talking about](https://go.dev/ref/mod#zip-path-size-constraints:~:text=File%20and%20directory%20names%20within%20a%20module%20may%20consist%20of) is:

> File and directory names within a module may consist of Unicode letters, ASCII digits, the ASCII space character (U+0020), and the ASCII punctuation characters !#$%&()+,-.=@[]^_{}~. Note that package paths may not contain all these characters. See [module.CheckFilePath](https://pkg.go.dev/golang.org/x/mod/module?tab=doc#CheckFilePath) and [module.CheckImportPath](https://pkg.go.dev/golang.org/x/mod/module?tab=doc#CheckImportPath) for the differences.

## Problem
The scylla-manager repo is using the testing against golden files. [The names of the golden files are generated from the name of the test](https://github.com/scylladb/scylla-manager/blob/4c5ed0c8d1f43bea94e85a1ded8e5acc48f3d8d7/pkg/testutils/golden.go#L64-L69). No check for correctness of the filename is performed that [resulted in storing golden files with filenames](https://github.com/scylladb/scylla-manager/tree/4c5ed0c8d1f43bea94e85a1ded8e5acc48f3d8d7/pkg/scheduler/testdata/WindowParse) that are not allowed to be in the go module: the `:` character is presented in the subtest name and the golden file name.

Presence of invalid files prevents adding a `github.com/scylladb/scylla-manager/v3 ` as a dependency of another module.
```console
$ docker run --rm -ti -w /app golang:latest sh -c 'go mod init app && go get -v github.com/scylladb/scylla-manager/v3@master'
go: creating new go.mod: module app
go: downloading github.com/scylladb/scylla-manager/v3 v3.0.0-20220712092659-4c5ed0c8d1f4
go: github.com/scylladb/scylla-manager/v3@master: create zip: pkg/scheduler/testdata/WindowParse/23:00,06:00,sat-00:00,sun-23:59.golden.json: malformed file path "pkg/scheduler/testdata/WindowParse/23:00,06:00,sat-00:00,sun-23:59.golden.json": invalid char ':'
pkg/scheduler/testdata/WindowParse/23:00,06:00.golden.json: malformed file path "pkg/scheduler/testdata/WindowParse/23:00,06:00.golden.json": invalid char ':'
pkg/scheduler/testdata/WindowParse/mon-00:00,fri-15:00.golden.json: malformed file path "pkg/scheduler/testdata/WindowParse/mon-00:00,fri-15:00.golden.json": invalid char
```

## Solution
I have two solutions in mind: the quick one and the futureproof one.

<details>
<summary>Quick solution</summary>

Introduce a different name for table-driven tests that are part of the [`TestWindowParse`](https://github.com/scylladb/scylla-manager/blob/4c5ed0c8d1f43bea94e85a1ded8e5acc48f3d8d7/pkg/scheduler/window_test.go#L187-L224):

```diff
Index: pkg/scheduler/window_test.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/scheduler/window_test.go b/pkg/scheduler/window_test.go
--- a/pkg/scheduler/window_test.go	(revision 4c5ed0c8d1f43bea94e85a1ded8e5acc48f3d8d7)
+++ b/pkg/scheduler/window_test.go	(date 1657631724708)
@@ -10,6 +10,7 @@
 
 	"github.com/google/go-cmp/cmp"
 	"github.com/google/go-cmp/cmp/cmpopts"
+
 	. "github.com/scylladb/scylla-manager/v3/pkg/testutils"
 )
 
@@ -185,22 +186,22 @@
 }
 
 func TestWindowParse(t *testing.T) {
-	table := []struct {
+	table := map[string]struct {
 		Window string
 	}{
-		{
+		"weekdays": {
 			Window: "mon-00:00,fri-15:00",
 		},
-		{
+		"overnight": {
 			Window: "23:00,06:00",
 		},
-		{
+		"overnight and weekend": {
 			Window: "23:00,06:00,sat-00:00,sun-23:59",
 		},
 	}
-	for i := range table {
-		test := table[i]
-		t.Run(test.Window, func(t *testing.T) {
+	for name := range table {
+		test := table[name]
+		t.Run(name, func(t *testing.T) {
 			s := bytes.Split([]byte(test.Window), []byte{','})
 			wdt := make([]WeekdayTime, len(s))
 			for i := range wdt {

```

</details>

<details>
<summary>Futureproof solution</summary>

Check during the golden files update process that a newly created file is module-compatible.

```diff
Index: pkg/testutils/golden.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/testutils/golden.go b/pkg/testutils/golden.go
--- a/pkg/testutils/golden.go	(revision 4c5ed0c8d1f43bea94e85a1ded8e5acc48f3d8d7)
+++ b/pkg/testutils/golden.go	(date 1657632001860)
@@ -10,6 +10,8 @@
 	"path"
 	"strings"
 	"testing"
+
+	"golang.org/x/mod/module"
 )
 
 var flagUpdate = flag.Bool("update", false, "update .golden files")
@@ -76,10 +78,14 @@
 		return
 	}
 
-	if err := os.MkdirAll(path.Dir(goldenTextFileName(tb)), 0o777); err != nil {
+	filename := goldenTextFileName(tb)
+	if err := module.CheckFilePath(filename); err != nil {
+		tb.Fatalf("cannot use name of the test to store golden file %q: %v", filename, err)
+	}
+	if err := os.MkdirAll(path.Dir(filename), 0o777); err != nil {
 		tb.Fatal(err)
 	}
-	if err := os.WriteFile(goldenTextFileName(tb), []byte(s), 0o666); err != nil {
+	if err := os.WriteFile(filename, []byte(s), 0o666); err != nil {
 		tb.Error(err)
 	}
 }

```

</details>

**Comment by mmatczuk** [comment]
3rd solution, replace `:` with `_` in golden file names.
