### ISSUE TITLE
Argument segment missing from task progress output of a backup task

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3213]
This issue appeared in a cloud test

Client version: 3.0.0-0.20220523.5501e5d7f53
Server version: 3.0.0-0.20220523.5501e5d7f53

## Installation details

Kernel Version: 5.13.0-1031-aws
Scylla version (or git commit hash): `2021.1.12-20220620.e23889f17` with build-id `00bd36a6a55a00508aad03c6e9a11932a6c3b1a6`
Cluster size: 6 nodes (i3.2xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `ami-0763124bdca4e1fe3` (aws: eu-west-1)

Test: `scylla-cloud-longevity-100gb-48h`
Test id: `973ddc46-9ec7-487f-a625-90db2b04969b`
Test name: `siren-tests/longevity-tests/scylla-cloud-longevity-100gb-48h`
Test config file(s):

- [scylla_cloud_longevity-100GB-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1a4be9ada7492e9dd429fa126a226063d9b9f8b8//home/ubuntu/scylla-cluster-tests/siren-tests/sct_plugin/configurations/scylla_cloud_longevity-100GB-48h.yaml)

## Issue description

As always with cloud clusters, by the time our test has started there was already an ongoing backup `backup/cf7a6a13-1897-40f1-80fe-ebb79256d705`. But when we checked its progress, the Arguments of the task were not printed:
```
< t:2022-08-06 18:03:13,981 f:cli.py          l:1061 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool  -c CLOUD_CLUSTER_ID progress backup/cf7a6a13-1897-40f1-80fe-ebb79256d705'
< t:2022-08-06 18:03:13,981 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/opt/scylla/scylla-cloud -c /opt/scylla/scylla-dbaas.yml cluster manager sctool --cluster-id 21215 --    progress backup/cf7a6a13-1897-40f1-80fe-ebb79256d705"...
< t:2022-08-06 18:03:19,799 f:base.py         l:142  c:RemoteCmdRunner      p:DEBUG > Command "/opt/scylla/scylla-cloud -c /opt/scylla/scylla-dbaas.yml cluster manager sctool --cluster-id 21215 --    progress backup/cf7a6a13-1897-40f1-80fe-ebb79256d705" finished with status 0
< t:2022-08-06 18:03:19,799 f:cli.py          l:1064 c:sdcm.mgmt.cli        p:DEBUG > sctool output:
Run:               cfbb3e0f-15ac-11ed-bce6-0aec37006bcd
Status:           ERROR (uploading data)
Cause:            missing hosts to resume backup
Start time:       06 Aug 22 17:25:48 UTC
End time: 06 Aug 22 17:25:52 UTC
Duration: 4s
Progress: 97%
Snapshot Tag:     sm_20220806113900UTC
Datacenters:      
  - AWS_EU_WEST_1

╭────────────────┬──────────┬─────────┬─────────┬──────────────┬────────╮
│ Host           │ Progress │    Size │ Success │ Deduplicated │ Failed │
├────────────────┼──────────┼─────────┼─────────┼──────────────┼────────┤
│ 172.21.168.12  │     100% │ 26.527G │ 26.527G │            0 │      0 │
│ 172.21.168.146 │     100% │ 24.831G │ 24.831G │            0 │      0 │
│ 172.21.169.114 │     100% │ 25.487G │ 25.487G │            0 │      0 │
│ 172.21.169.74  │     100% │ 24.918G │ 24.918G │            0 │      0 │
│ 172.21.170.30  │      96% │ 26.072G │ 25.052G │            0 │      0 │
│ 172.21.170.88  │      91% │ 25.962G │ 23.817G │            0 │      0 │
╰────────────────┴──────────┴─────────┴─────────┴──────────────┴────────╯
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 973ddc46-9ec7-487f-a625-90db2b04969b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=973ddc46-9ec7-487f-a625-90db2b04969b)
- Show all stored logs command: `$ hydra investigate show-logs 973ddc46-9ec7-487f-a625-90db2b04969b`

## Logs:
- **db-cluster-973ddc46.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/db-cluster-973ddc46.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/db-cluster-973ddc46.tar.gz)
- **monitor-set-973ddc46.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/monitor-set-973ddc46.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/monitor-set-973ddc46.tar.gz)
- **siren-manager-set-973ddc46.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/siren-manager-set-973ddc46.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/siren-manager-set-973ddc46.tar.gz)
- **loader-set-973ddc46.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/loader-set-973ddc46.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/loader-set-973ddc46.tar.gz)
- **sct-runner-973ddc46.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/sct-runner-973ddc46.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/973ddc46-9ec7-487f-a625-90db2b04969b/20220808_114522/sct-runner-973ddc46.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/siren-tests/job/longevity-tests/job/scylla-cloud-longevity-100gb-48h/125/)

**Comment by karol-kokoszka** [comment]
Hey @ShlomiBalalis 
Arguments of the task are not being printed Manager 3.0 -> https://github.com/scylladb/scylla-manager/commit/b0785d04f9641352e78e1989963a7f17a775f6e5
Above is link to the commit that removes it.

If it's a must I can bring it back. Just let me know.

**Comment by karol-kokoszka** [comment]
As per @ShlomiBalalis request. We need to bring this information back.

**Comment by rayakurl** [comment]
@karol-kokoszka - any progress with this issue?

**Comment by karol-kokoszka** [comment]
@rayakurl I was about to bring back the previous functionality, but seems that with the PR removing arguments from `task progress` were moved to  command info e.g. `. ./sctool.dev info repair/all-weekly --cluster 44bd79fd-c8db-4e4d-81cd-267180c4e5d0` shows 
```
Name:   repair/all-weekly
Cron:   0 23 * * SAT (At 11:00 PM, only on Saturday)
Tz:     America/New_York
Retry:  3 

No runs yet.
```

According to PR description
```
managerclient: remove CmdRenderer
- Progress command no longer shows the args.
- Info command prints args and schedule.
```
args were just moved to `sctool info` command.

I guess previous maintainers did it for some reason (I'm not sure how well this change was announced with QA team).
Question I have, is it OK to use this command to see what arguments were used to start the task ? Or you still need to bring back previous functionality ?

Last but not least, sorry for the late response and action with this task. Scylla-manager is in maintenance mode. I didn't know how (and if) important this issue is for you.

**Comment by rayakurl** [comment]
Hi @karol-kokoszka , thanks for your response. This issue happens from time to time in cloud longevity jobs. So we will be glad if you handled it. Regarding your questions - @ShlomiBalalis can reply.

**Comment by ShlomiBalalis** [comment]
> @rayakurl I was about to bring back the previous functionality, but seems that with the PR removing arguments from `task progress`, arguments were moved to command info e.g. `. ./sctool.dev info repair/all-weekly --cluster 44bd79fd-c8db-4e4d-81cd-267180c4e5d0` shows
> 
> ```
> Name:   repair/all-weekly
> Cron:   0 23 * * SAT (At 11:00 PM, only on Saturday)
> Tz:     America/New_York
> Retry:  3 
> 
> No runs yet.
> ```
> 
> According to PR description
> 
> ```
> managerclient: remove CmdRenderer
> - Progress command no longer shows the args.
> - Info command prints args and schedule.
> ```
> 
> args were just moved to `sctool info` command.
> 
> I guess previous maintainers did it for some reason (I'm not sure how well this change was announced with QA team). Question I have, is it OK to use this command to see what arguments were used to start the task ? Or you still need to bring back previous functionality ?

I see, I'll try to work with that then!

**Comment by ShlomiBalalis** [comment]
Sctool info gets the job done! Closing.
