### ISSUE TITLE
Docs: doc releases for 2.6-patch and 3.0 patch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-manager#3261]
Docs should be release per minor version, not patch version
![image](https://user-images.githubusercontent.com/170200/200334064-9b638d34-2ba5-4af3-bbda-6d91aa1dbcea.png)

**Comment by tzach** [comment]
@dgarcia360 can yo uplease take a look

**Comment by tzach** [comment]
@karol-kokoszka did you remove the 3.0-patch and 2.6-patch branchs?
If so, please rebuild the docs so it will be remove from docs

**Comment by karol-kokoszka** [comment]
@tzach yes, I merged these branches to branch-3.0 and branch-2.6. They contained fix for the problem with `prometheus_address`
We make patch releases from `branch-3.0` and `branch-2.6`

**Comment by tzach** [comment]
Can you please trigger rebuild of the docs?

**Comment by tzach** [comment]
Problem solved!
![image](https://user-images.githubusercontent.com/170200/202234218-2d3477e7-ee00-4710-89c4-0570cd60fe79.png)
