### ISSUE TITLE
Manager agent - empty s3 config display error message - empty string

### ISSUE THREAD

**Issue by pascalp2** [scylladb/scylla-manager#3263]
Environment : Scylla-manager-agent 3.0.0 on ubuntu 22.04 VM (GCP)
Config : blank config, at the exception of the auth token.

running the following command return an error :
`scylla-manager-agent check-location --location gcs:scylla-staging-backup`

Error:
`{"L":"ERROR","T":"2022-11-10T07:13:06.854-0500","N":"rclone","M":"parse instance region: invalid character '<' looking for beginning of value","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\ngithub.com/rclone/rclone/fs.Errorf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:133\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\nmain.setupCommand\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\nmain.glob..func3\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/check_location.go:40\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\nruntime.main\n\truntime/proc.go:225"}`

This is causing a problem when I try to restore a backup.
`FAILED! => {"changed": true, "cmd": "scylla-manager-agent download-files -L gcs:scylla-staging-backup -n 71f7b398-fdb6-4033-a0c2-9a8aa2837703 -T sm_20221109145319UTC --dump-manifest | jq -r '.index[] | [.keyspace,.table] | join(\".\")'\n", "delta": "0:00:00.247104", "end": "2022-11-09 17:21:09.279167", "msg": "non-zero return code", "rc": 1, "start": "2022-11-09 17:21:09.032063", "stderr": "{\"L\":\"ERROR\",\"T\":\"2022-11-09T17:21:09.081-0500\",\"N\":\"rclone\",\"M\":\"parse instance region: invalid character '<' looking for beginning of value\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:133\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\\nmain.setupCommand\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\\nmain.glob..func5\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/download_files.go:71\\ngithub.com/spf13/cobra.(*Command).execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:850\\ngithub.com/spf13/cobra.(*Command).ExecuteC\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:958\\ngithub.com/spf13/cobra.(*Command).Execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:895\\nmain.main\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\\nruntime.main\\n\\truntime/proc.go:250\"}\nSorry, home directories outside of /home are not currently supported. \nSee https://forum.snapcraft.io/t/11209 for details.", "stderr_lines": ["{\"L\":\"ERROR\",\"T\":\"2022-11-09T17:21:09.081-0500\",\"N\":\"rclone\",\"M\":\"parse instance region: invalid character '<' looking for beginning of value\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:133\\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\\nmain.setupCommand\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\\nmain.glob..func5\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/download_files.go:71\\ngithub.com/spf13/cobra.(*Command).execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:850\\ngithub.com/spf13/cobra.(*Command).ExecuteC\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:958\\ngithub.com/spf13/cobra.(*Command).Execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:895\\nmain.main\\n\\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\\nruntime.main\\n\\truntime/proc.go:250\"}", "Sorry, home directories outside of /home are not currently supported. ", "See https://forum.snapcraft.io/t/11209 for details."], "stdout": "", "stdout_lines": []}`

The problem seem related to the execution of the remote command
`scylla-manager-agent download-files -L gcs:scylla-staging-backup -n 71f7b398-fdb6-4033-a0c2-9a8aa2837703 -T sm_20221109145319UTC --dump-manifest | jq -r '.index[] | [.keyspace,.table] | join(\".\")'`
which return the same error mentioned at the beginning of the post.

This lead to be unable to restore my backup.

**Solution to this :**
uncomment the following lines in the manager-agent config file :
`s3:
   region: `
and add a random string to the region.

**Comment by karol-kokoszka** [comment]
The error reported here comes from https://github.com/scylladb/scylla-manager/blob/e9829c2535355268cc5a1cc8b19d304b63a8583e/pkg/rclone/aws.go#L18-L46

If the region is not defined, manager calls `http://169.254.169.254/latest/dynamic/instance-identity/document` to get the region (assuming that manager is deployed in AWS).

Manager sends the output to stderr but continues to work.

We will change it to not report it to stderr, but just log some better description of what's going on.

**Comment by Michal-Leszczynski** [comment]
There is a new issue (#3691) for tracking this problem.
