### ISSUE TITLE
Setting `healthcheck`'s `max_timeout` seems to have no effect

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3268]
## Installation details

Kernel Version: 5.15.0-1021-aws
Scylla version (or git commit hash): `5.0.5-20221009.5a97a1060` with build-id `5009658b834aaf68970135bfc84f964b66ea4dee`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla/branch-5.0/relocatable/2022-10-09T08:48:44Z/scylla-x86_64-package.tar.gz
Cluster size: 3 nodes (i3.large)
Manager version: 3.0-dev-0.20221120.96eb53ed1bb-SNAPSHOT-96eb53ed1bb

Scylla Nodes used in this run:
- manager-regression-master-db-node-9af311ab-3 (35.165.10.208 | 10.15.1.55) (shards: 2)
- manager-regression-master-db-node-9af311ab-2 (44.199.255.195 | 10.12.2.8) (shards: 2)
- manager-regression-master-db-node-9af311ab-1 (44.212.12.163 | 10.12.3.115) (shards: 2)

OS / Image: `ami-08e0451a2387906f9 ami-0c60b4108a34be76c` (aws: us-east-1)

Test: `centos-sanity-test`
Test id: `9af311ab-db5a-4bb0-8986-5ef36aa3ee40`
Test name: `manager-master/centos-sanity-test`
Test config file(s):

- [manager-regression-multiDC-set-distro.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/259bd1fded9fc617ccce00342bd5c9b8533727f5/test-cases/manager/manager-regression-multiDC-set-distro.yaml)

## Issue description

As part of the manager sanity test we attempt to change the timeout of the healthcheck task (an option that was added in 2.6). We change the timeout to 20ms, and since the test is multi dc, we expect the healthcheck of the node of the distant dc to time out. The task, however, does not time out:
The contents of `scylla-manager.yaml`:
```
healthcheck:
  max_timeout: 20ms
http: 127.0.0.1:5080
prometheus: :5090
tls_cert_file: null
tls_key_file: null
```
The healthcheck task output:
```
Datacenter: us-eastscylla_node_east
╭────┬──────────┬──────────┬─────────────┬──────────┬──────┬─────────┬────────┬───────┬──────────────────────────────────────╮
│    │ CQL      │ REST     │ Address     │ Uptime   │ CPUs │ Memory  │ Scylla │ Agent │ Host ID                              │
├────┼──────────┼──────────┼─────────────┼──────────┼──────┼─────────┼────────┼───────┼──────────────────────────────────────┤
│ UN │ UP (0ms) │ UP (0ms) │ 10.12.2.8   │ 1h12m42s │ 2    │ 14.886G │ 5.0.5  │ 3.0.0 │ 51262cea-e83c-48c7-8521-5ed05bfa7135 │
│ UN │ UP (0ms) │ UP (0ms) │ 10.12.3.115 │ 1h12m42s │ 2    │ 14.886G │ 5.0.5  │ 3.0.0 │ cf99ddf8-5883-4897-9fdf-f2ae3512c34c │
╰────┴──────────┴──────────┴─────────────┴──────────┴──────┴─────────┴────────┴───────┴──────────────────────────────────────╯
Datacenter: us-west-2scylla_node_west
╭────┬────────────┬───────────┬────────────┬─────────┬──────┬─────────┬────────┬───────┬──────────────────────────────────────╮
│    │ CQL        │ REST      │ Address    │ Uptime  │ CPUs │ Memory  │ Scylla │ Agent │ Host ID                              │
├────┼────────────┼───────────┼────────────┼─────────┼──────┼─────────┼────────┼───────┼──────────────────────────────────────┤
│ UN │ UP (127ms) │ UP (64ms) │ 10.15.1.55 │ 1h9m14s │ 2    │ 14.886G │ 5.0.5  │ 3.0.0 │ c1daf3c7-33f2-4732-a65e-32d019d86eef │
╰────┴────────────┴───────────┴────────────┴─────────┴──────┴─────────┴────────┴───────┴──────────────────────────────────────╯
```
So it seems that the manager ignores the max_timeout that is set in the yaml.

I looked back at the run history, and the bug began to occur since **09.11.2022**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9af311ab-db5a-4bb0-8986-5ef36aa3ee40`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9af311ab-db5a-4bb0-8986-5ef36aa3ee40)
- Show all stored logs command: `$ hydra investigate show-logs 9af311ab-db5a-4bb0-8986-5ef36aa3ee40`

## Logs:
- **db-cluster-9af311ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/db-cluster-9af311ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/db-cluster-9af311ab.tar.gz)
- **monitor-set-9af311ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/monitor-set-9af311ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/monitor-set-9af311ab.tar.gz)
- **loader-set-9af311ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/loader-set-9af311ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/loader-set-9af311ab.tar.gz)
- **sct-runner-9af311ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/sct-runner-9af311ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9af311ab-db5a-4bb0-8986-5ef36aa3ee40/20221121_001037/sct-runner-9af311ab.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/manager-master/job/centos-sanity-test/779/)

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis we removed so called dynamic timeout from manager at all. It was done with PR https://github.com/scylladb/scylla-manager/pull/3258 

So from this moment RelativeTimeout = general timeout.
MaxTimeout is not used at all, but left to keep backward compatibility. Scylla Manager wouldn't start if someone already have MaxTimeout in their config.

> I looked back at the run history, and the bug began to occur since 09.11.2022

Yes, it's the moment exactly when the dynamic timeout was removed.

As previously (before this PR), RelativeTimeout was the one that actually were taken into the account when probing. I left RelativeTimeout but removed support MaxTimeout. 
MaxTimeout could be reached only when the value was lower than RelativeOne, or just a little bit higher.

BUT seems it may create a confusion (leaving RelativeTimeout, removing MaxTimeout).
I just replace RelativeTimeout with MaxTimeout with the last commit to scylla-manager master branch.

So now:
- RelativeTimeout is not used at all
- MaxTimeout is the general timeout for pings

Please let me know if the test passes with the latest master.

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis we removed so called dynamic timeout from manager at all. It was done with PR #3258
> 
> So from this moment RelativeTimeout = general timeout. MaxTimeout is not used at all, but left to keep backward compatibility. Scylla Manager wouldn't start if someone already have MaxTimeout in their config.
> 
> > I looked back at the run history, and the bug began to occur since 09.11.2022
> 
> Yes, it's the moment exactly when the dynamic timeout was removed.
> 
> As previously (before this PR), RelativeTimeout was the one that actually were taken into the account when probing. I left RelativeTimeout but removed support for MaxTimeout. MaxTimeout could be reached only when the value was lower than RelativeOne, or just a little bit higher.
> 
> BUT seems it may create a confusion (leaving RelativeTimeout, removing MaxTimeout). I just replace RelativeTimeout with MaxTimeout with the last commit to scylla-manager master branch.
> 
> So now:
> 
> * RelativeTimeout is not used at all
> * MaxTimeout is the general timeout for pings
> 
> Please let me know if the test passes with the latest master.

Yep, the sanity tests are passing. Thank you
