### ISSUE TITLE
docs: Issue in page Scylla Manager Upgrade

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3269]
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.0/upgrade/index

### Problem

The page is out of date, at least the `Applicable versions` section - still stating debian 9 and ubuntu 16, which have not been supported for a while

###  Suggest a fix

Update the page to be in line with the currently supported platforms

**Comment by mykaul** [comment]
@annastuchlik - can you take a look?

**Comment by annastuchlik** [comment]
@ShlomiBalalis @karol-kokoszka @roydahan @tzach 
Where can I find information about platforms supported by Scylla Manager?
I think it should be:
- Red Hat Enterprise Linux 7 and 8
- CentOS 7 and 8
- Debian 10 and 11
- Ubuntu 18.04, 20.04, 22.04

But it's only my guess, so I need confirmation or a reliable source, such as a compatibility matrix so that I can update the docs.

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis @karol-kokoszka @roydahan @tzach Where can I find information about platforms supported by Scylla Manager? I think it should be:
> 
> * Red Hat Enterprise Linux 7 and 8
> * CentOS 7 and 8
> * Debian 10 and 11
> * Ubuntu 18.04, 20.04, 22.04
> 

All true except I believe that centos (and RH) 8 is not supported by scylla, but instead we support "rocky8"

**Comment by mykaul** [comment]
> > @ShlomiBalalis @karol-kokoszka @roydahan @tzach Where can I find information about platforms supported by Scylla Manager? I think it should be:
> > 
> > * Red Hat Enterprise Linux 7 and 8
> > * CentOS 7 and 8
> > * Debian 10 and 11
> > * Ubuntu 18.04, 20.04, 22.04
> 
> All true except I believe that centos (and RH) 8 is not supported by scylla, but instead we support "rocky8"

The overall term is 'Enterprise Linux' (8 or whatever version) and it covers CentOS, RHEL, Alma, Rocky...
