### ISSUE TITLE
Backup operation becomes endless reaching the "no space" situation on it's storage backend

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-manager#3271]
Running `scylla-manager` on K8S using `MinIO` project as a backend we may easily reach the situation
where storage disk that is used for the backups runs out of free space.

If it happens, then we see following behavior:

The output of the ongoing backup process while there is free space:
```
time: 2022-11-23 15:07:38,867
+----------------+----------+---------+---------+--------------+--------+                              
| Host           | Progress |    Size | Success | Deduplicated | Failed |                              
+----------------+----------+---------+---------+--------------+--------+                              
| 172.20.138.34  |       0% | 22.890G |       0 |            0 |      0 |                              
| 172.20.193.244 |       0% | 13.952G |       0 |            0 |      0 |                              
| 172.20.210.182 |       0% | 17.380G |       0 |            0 |      0 |                              
+----------------+----------+---------+---------+--------------+--------+                              

time: 2022-11-23 15:08:42,390
+----------------+----------+---------+----------+--------------+--------+                             
| Host           | Progress |    Size |  Success | Deduplicated | Failed |                             
+----------------+----------+---------+----------+--------------+--------+                             
| 172.20.138.34  |       1% | 22.890G | 429.019M |            0 |      0 |                             
| 172.20.193.244 |       3% | 13.952G | 493.004M |            0 |      0 |                             
| 172.20.210.182 |       2% | 17.380G | 475.701M |            0 |      0 |                             
+----------------+----------+---------+----------+--------------+--------+                             

time: 2022-11-23 15:43:01,141
+----------------+----------+---------+---------+--------------+--------+
| Host           | Progress |    Size | Success | Deduplicated | Failed |
+----------------+----------+---------+---------+--------------+--------+
| 172.20.138.34  |      57% | 22.890G | 13.247G |            0 |      0 |
| 172.20.193.244 |      95% | 13.952G | 13.304G |            0 |      0 |
| 172.20.210.182 |      73% | 17.380G | 12.827G |            0 |      0 |
+----------------+----------+---------+---------+--------------+--------+
```

Then, suddenly, without any special messages in the `scylla-manager` logs we see following output:
```
time: 2022-11-23 15:43:07,375
+----------------+----------+---------+---------+--------------+--------+                           
| Host           | Progress |    Size | Success | Deduplicated | Failed |                                      
+----------------+----------+---------+---------+--------------+--------+                           
| 172.20.138.34  |      57% | 22.890G | 13.247G |            0 |      0 |                           
| 172.20.193.244 |      29% | 13.952G |  4.048G |            0 |      0 |                           
| 172.20.210.182 |      73% | 17.380G | 12.827G |            0 |      0 |                           
+----------------+----------+---------+---------+--------------+--------+
```

We see that the backup'ed data for the middle Scylla node\pod became smaller for more than 9Gb!
After several seconds one more node loses some already backup'ed data (5.2Gb) too:
```
time: 2022-11-23 15:43:20,642
+----------------+----------+---------+---------+--------------+--------+
| Host           | Progress |    Size | Success | Deduplicated | Failed |
+----------------+----------+---------+---------+--------------+--------+
| 172.20.138.34  |      58% | 22.890G | 13.320G |            0 |      0 |
| 172.20.193.244 |      29% | 13.952G |  4.134G |            0 |      0 |
| 172.20.210.182 |      43% | 17.380G |  7.474G |            0 |      0 |
+----------------+----------+---------+---------+--------------+--------+
```

Then, the backup process continue like nothing bad happened till the place where the backup'ed data reaches the same amount of space (the only available):
```
time: 2022-11-23 16:00:32,838
+----------------+----------+---------+---------+--------------+--------+
| Host           | Progress |    Size | Success | Deduplicated | Failed |
+----------------+----------+---------+---------+--------------+--------+
| 172.20.138.34  |      82% | 22.890G | 18.971G |            0 |      0 |
| 172.20.193.244 |      71% | 13.952G |  9.935G |            0 |      0 |
| 172.20.210.182 |      74% | 17.380G | 12.973G |            0 |      0 |
+----------------+----------+---------+---------+--------------+--------+
                                                                                                    
...                                                                                                 
                                                                                                    
time: 2022-11-23 16:00:39,421
+----------------+----------+---------+---------+--------------+--------+
| Host           | Progress |    Size | Success | Deduplicated | Failed |
+----------------+----------+---------+---------+--------------+--------+
| 172.20.138.34  |      82% | 22.890G | 18.971G |            0 |      0 |
| 172.20.193.244 |      28% | 13.952G |  4.028G |            0 |      0 |
| 172.20.210.182 |      74% | 17.380G | 12.973G |            0 |      0 |
+----------------+----------+---------+---------+--------------+--------+
```

So, the result of all this situation is endless loop of backing up and losing data in the middle without any errors.

Info: 
Ci job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-12h-multitenant-eks/8/console
SCT logs: https://cloudius-jenkins-test.s3.amazonaws.com/339a3064-2982-47aa-97bc-0b6957be83aa/20221124_031900/sct-runner-339a3064.tar.gz
K8S logs: https://cloudius-jenkins-test.s3.amazonaws.com/339a3064-2982-47aa-97bc-0b6957be83aa/20221124_031900/kubernetes-339a3064.tar.gz
scylla-manager version: `scylladb/scylla-manager:3.0.0`
scylla version: `5.0.5`
scylla-operator version: `v1.8.0-alpha.0-159-g73e8635`

Note that the above CI job is K8S multitenant setup with 14 clusters, where 5 of them had separate nemesis.

Expected behavior: `scylla-manager` must correctly detect the impossibility to write data to it's storage and provide an error as a result.
Actual behavior: endless backup process not providing any error message.

**Comment by mykaul** [comment]
What storage is running out - the minio backing or the local disk?

**Comment by mykaul** [comment]
Same / similar to https://github.com/scylladb/scylla-manager/issues/3243 ?

**Comment by vponomaryov** [comment]
> What storage is running out - the minio backing or the local disk?

Yes, minio storage because we specify the size of the storage explicitly creating persistent volume for it in K8S.

> Same / similar to #3243 ?

No, totally unrelated.

**Comment by mykaul** [comment]
> > What storage is running out - the minio backing or the local disk?
> 
> Yes, minio storage because we specify the size of the storage explicitly creating persistent volume for it in K8S.

We don't support Minio (and this is exactly why we need to move to use S3 - I've discussed it with @fruch just the other day.

I assume this is not a bug and should be closed.
> 
> > Same / similar to #3243 ?
> 
> No, totally unrelated.

**Comment by vponomaryov** [comment]
> > > What storage is running out - the minio backing or the local disk?
> > 
> > 
> > Yes, minio storage because we specify the size of the storage explicitly creating persistent volume for it in K8S.
> 
> We don't support Minio (and this is exactly why we need to move to use AWS S3 - I've discussed it with @fruch just the other day.
> 
> I assume this is not a bug and should be closed.

The bug really exists, it is exactly manager's bug. But it's priority becomes small if we use S3 only.
So, from status point of view I am ok to see `won't fix`, but not `it is not bug`.

**Comment by mykaul** [comment]
> > > > What storage is running out - the minio backing or the local disk?
> > > 
> > > 
> > > Yes, minio storage because we specify the size of the storage explicitly creating persistent volume for it in K8S.
> > 
> > 
> > We don't support Minio (and this is exactly why we need to move to use AWS S3 - I've discussed it with @fruch just the other day.
> > I assume this is not a bug and should be closed.
> 
> The bug really exists, it is exactly manager's bug. But it's priority becomes small if we use S3 only. So, from status point of view I am ok to see `won't fix`, but not `it is not bug`.

S3 is endless, so I'm not sure what the bug is. In any case, it's not something we are going to invest in.
