### ISSUE TITLE
Snapshot files of a decommissioned node are not removed from s3 upon rerunning the backup task

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3277]
Manager version: 3.0-dev-0.20221201.777c023fd86-SNAPSHOT-777c023fd86
Scylla relocatable package: https://downloads.scylladb.com/unstable/scylla/master/relocatable/2022-12-07T09%3A12%3A30Z/

In this scenario, we created a backup for a 3 cluster node, decommissioned one of the nodes and reran the same backup task. It's expected that once the manager identifies that one of the nodes was decommissioned, the backed up snapshots of said node will be removed from even previous runs of the backup task. This, however, is not the case, and the snapshots remain in the bucket even after the task was rerun:
* Backup is created:
```
12:00:29,438 dtest_scylla_manager DEBUG dtest_scylla_manager.py:829  | Issuing: 'sctool ['backup', '-c', '87384ebc-a78a-4f72-834b-bb6a77706af4', '--keyspace', 'ks', '--location', 's3:backup-bucket', '--retention', '1']'
12:00:29,698 dtest_scylla_manager DEBUG dtest_scylla_manager.py:836  | sctool command result:
12:00:29,698 dtest_scylla_manager DEBUG dtest_scylla_manager.py:837  | backup/fcac3de4-8e33-4093-9e28-54eb058b782a
...
12:00:39,767 dtest_scylla_manager DEBUG dtest_scylla_manager.py:829  | Issuing: 'sctool ['progress', 'backup/fcac3de4-8e33-4093-9e28-54eb058b782a', '-c', '87384ebc-a78a-4f72-834b-bb6a77706af4']'
12:00:39,813 dtest_scylla_manager DEBUG dtest_scylla_manager.py:836  | sctool command result:
12:00:39,813 dtest_scylla_manager DEBUG dtest_scylla_manager.py:837  | Run:		257b380f-76df-11ed-ad86-f4ee08c9cc47
Status:		DONE
Start time:	08 Dec 22 12:00:29 IST
End time:	08 Dec 22 12:00:30 IST
Duration:	0s
Progress:	100%
Snapshot Tag:	sm_20221208100029UTC
Datacenters:	
  - datacenter1

+-----------+----------+----------+----------+--------------+--------+
| Host      | Progress |     Size |  Success | Deduplicated | Failed |
+-----------+----------+----------+----------+--------------+--------+
| 127.0.2.1 |     100% | 131.684k | 131.684k |            0 |      0 |
| 127.0.2.2 |     100% | 133.411k | 133.411k |            0 |      0 |
| 127.0.2.3 |     100% | 138.682k | 138.682k |            0 |      0 |
+-----------+----------+----------+----------+--------------+--------+
```
All 3 nodes are UN:
```
12:00:39,814 dtest_scylla_manager DEBUG dtest_scylla_manager.py:829  | Issuing: 'sctool ['status', '--cluster', '87384ebc-a78a-4f72-834b-bb6a77706af4']'
12:00:39,861 dtest_scylla_manager DEBUG dtest_scylla_manager.py:836  | sctool command result:
12:00:39,861 dtest_scylla_manager DEBUG dtest_scylla_manager.py:837  | Datacenter: datacenter1
+----+----------+----------+-----------+-----------+------+---------+--------+-------+--------------------------------------+
|    | CQL      | REST     | Address   | Uptime    | CPUs | Memory  | Scylla | Agent | Host ID                              |
+----+----------+----------+-----------+-----------+------+---------+--------+-------+--------------------------------------+
| UN | UP (0ms) | UP (0ms) | 127.0.2.1 | 98h28m39s | 16   | 31.088G | 5.2.0  | 3.0.0 | 78ccbd16-6c41-472b-bbaf-b754077352a8 |
| UN | UP (0ms) | UP (0ms) | 127.0.2.2 | 98h28m39s | 16   | 31.088G | 5.2.0  | 3.0.0 | b07af195-ce5f-49be-a154-2e03e18fbbe2 |
| UN | UP (0ms) | UP (0ms) | 127.0.2.3 | 98h28m39s | 16   | 31.088G | 5.2.0  | 3.0.0 | 60d68fa3-60de-4257-a2c8-16c9eeefbc3b |
+----+----------+----------+-----------+-----------+------+---------+--------+-------+--------------------------------------+
```
Number of backed up snapshot files in s3 of node 3: 162:
```
12:00:41,067 manager_backup_tests DEBUG manager_backup_tests.py:1042 | number of files of node 3 60d68fa3-60de-4257-a2c8-16c9eeefbc3b before decommission and rerun: 162
all files:backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-CRC.db
backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-Data.db
backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-Digest.crc32
...
```
Node 3 is decommissioned:
```
12:00:41,068 ccm             DEBUG cluster.py     :711  | node3: nodetool cmd=decommission wait=True timeout=None
12:00:41,928 cassandra.cluster INFO  thread.py      :57   | Cassandra host 127.0.2.3:9042 removed
```
Backup task is rerun:
```
12:00:53,958 dtest_scylla_manager DEBUG dtest_scylla_manager.py:829  | Issuing: 'sctool ['start', 'backup/fcac3de4-8e33-4093-9e28-54eb058b782a', '-c', '87384ebc-a78a-4f72-834b-bb6a77706af4', '--no-continue']'
...
12:00:57,086 dtest_scylla_manager DEBUG dtest_scylla_manager.py:836  | sctool command result:
12:00:57,086 dtest_scylla_manager DEBUG dtest_scylla_manager.py:837  | Run:		33f56cf1-76df-11ed-ad87-f4ee08c9cc47
Status:		DONE
Start time:	08 Dec 22 12:00:53 IST
End time:	08 Dec 22 12:00:54 IST
Duration:	0s
Progress:	100%
Snapshot Tag:	sm_20221208100054UTC
Datacenters:	
  - datacenter1

+-----------+----------+----------+----------+--------------+--------+
| Host      | Progress |     Size |  Success | Deduplicated | Failed |
+-----------+----------+----------+----------+--------------+--------+
| 127.0.2.1 |     100% | 124.260k | 124.260k |      95.721k |      0 |
| 127.0.2.2 |     100% | 126.310k | 126.310k |      96.271k |      0 |
+-----------+----------+----------+----------+--------------+--------+
```
Number of backed up snapshot files in s3 of node 3 after it was decommissioned and the task has rerun: 162:
```
12:01:07,216 manager_backup_tests DEBUG manager_backup_tests.py:1052 | number of files of node 3 60d68fa3-60de-4257-a2c8-16c9eeefbc3b after decommission and rerun: 162
all files:backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-CRC.db
backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-Data.db
backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-Digest.crc32
backup/sst/cluster/87384ebc-a78a-4f72-834b-bb6a77706af4/dc/datacenter1/node/60d68fa3-60de-4257-a2c8-16c9eeefbc3b/keyspace/ks/table/cf1/2187198076df11ed94c35a35f97de128/me-1-big-Filter.db
...
```
As seen here, even after node 3 was decommissioned and the task was rerun the snapshots files of the decommissioned node were not removed from s3 as expected.

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis I confirm scylla-manager doesn't remove backups for nodes that are decommissioned. 
The only cleaning that manager does, is  
```
// staleTags returns collection of snapshot tags for manifests that are "stale".
// That is:
// - temporary manifests,
// - manifests over task days retention days policy,
// - manifests over task retention policy,
// - manifests older than threshold if retention policy is unknown.
```
and these are removed.

Was it working this way in 3.0 ? I haven't seen any changes in the part that is removing content from the backup location since more than a year.

It may be expected behavior to not remove these files. If it's not expected, pls point me to the doc and I'll start working on that.
Another option is to raise with the product.

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis I reproduced the behavior on branch-3.0. And I confirm that it removes data from the decommissioned node.

@Michal-Leszczynski you can reproduce it locally with following steps.
Start dev env (`make start-dev-env`)
Esnure that scylla-manager server is running.
Add cluster to manager (`sctool cluster add --host 192.168.100.12 --auth-token token`)
  Create some keyspace with data on the cluster (you can use some integration test that writes the data).
Start backup task (`sctool backup -c put_cluster_id_here --keyspace put_keyspace --location s3:backuptest-delete --retention 1`) -- bucket must exists and it must be prefixed with `backuptest` for example
Now, the location contains data from 3 nodes.
Jump to one of the nodes from the DC (`docker exec -it {} /bin/bash`)
Decomission this node (`nodetool decommission`)
Rerun the task (`sctool task start backup/704a299f-d6fd-4a25-9e99-95f75078da38 -c {} --no-continue`)

It removes the decommissioned node sstables.

**Comment by karol-kokoszka** [comment]
And I confirm that that on master, sstables from the decommissioned node are not removed.

**Comment by Michal-Leszczynski** [comment]
Hi, sorry for late response.

I would like to point out, that snapshot of decommissioned node should be deleted not because node was decommissioned, but rather because this backup task has `--retention 1`.

This means that we are interested in keeping data only from the latest backup and the data from decommissioned node is not a part of it. However, if we set `--retention 2` in this test scenario, snapshot of decommissioned node should be kept in the bucket, because deleting it would make it impossible to restore this backup.

**Comment by Michal-Leszczynski** [comment]
@ShlomiBalalis This issue is directly connected to #3246. I already created PR with fix for it (#3257) but it's currently blocked from merging. I checked that this PR resolves this issue and deletes snapshot with decommissioned node.
So in terms of this issue I will do my best to merge this PR ASAP.

**Comment by ShlomiBalalis** [comment]
The issue still occurs in the latest 3.1 build. The fix was not backported: https://github.com/scylladb/scylla-manager/compare/branch-3.1...master

**Comment by ShlomiBalalis** [comment]
@karol-kokoszka @Michal-Leszczynski ^^

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis it's backported now.
