### ISSUE TITLE
Missing docker images for ARM

### ISSUE THREAD

**Issue by sebver** [scylladb/scylla-manager#3278]
When we were trying to run scylla on ARM we noticed there were no docker images published for linux/arm64:

https://hub.docker.com/r/scylladb/scylla-manager/tags
https://hub.docker.com/r/scylladb/scylla-manager-agent/tags

Since they are published for scylla itself, it would be nice if they could be published for the agent/manager as well.

**Comment by karol-kokoszka** [comment]
@yaronkaikov Is it possible to publish linux/arm64 docker images as well ?

**Comment by yaronkaikov** [comment]
@karol-kokoszka In general we can. I assume we want one docker image which supports multi-arch (Same as we do for Scylla). based on the current code in Scylla-manager I can see we don't build arm-based docker, so first, we should add it.

**Comment by DhirajBhakta** [comment]
This PR seems to have been reverted. Any plans to add ARM support soon?

**Comment by Kavinraja-Ganesan** [comment]
@yaronkaikov -- Any reason for this PR to be reverted 😕 ? I was looking for arm64 scylla-manager/agent images.

**Comment by Kavinraja-G** [comment]
@yaronkaikov -- Any reason for this PR to be reverted 😕 ? I was looking for arm64 scylla-manager/agent images.

**Comment by yaronkaikov** [comment]
@Kavinraja-G Yes, we faced some issues with arm based docker image, I will re-post it soon

**Comment by tzach** [comment]
@karol-kokoszka should we reopen this issue?

**Comment by karol-kokoszka** [comment]
@tzach we are done from the scylla-manager perspective as per my understanding. There is some work to be done on the scylla-pkg (?) side.
 @yaronkaikov Please correct me if I'm wrong. Can you link the issue that must be completed to have ARM images available ?

**Comment by yaronkaikov** [comment]
I think we should re-open it (again) since I am about to change the way we build the manager to include the docker images and manifest.

**Comment by yaronkaikov** [comment]
@karol-kokoszka https://github.com/scylladb/scylla-pkg/issues/3239 , this is the issue from pkg side, only when both will be done we can say we have a proper docker image for ARM
