### ISSUE TITLE
Metrics scylla_manager_task_* were disappeared after upgrading to 3.0.2 version

### ISSUE THREAD

**Issue by mrlexor** [scylladb/scylla-manager#3282]
Hello,

I've installed scylla-manager via https://github.com/scylladb/scylla-operator on Kubernetes cluster and I've added Scylla OSS cluster to scylla-manager. After upgrading Scylla OSS to 5.0.5 I've upgraded scylla-manager and scylla-manager-agent to 3.0.2 according to instruction https://manager.docs.scylladb.com/stable/upgrade/index.html

Everything were done successfully, also I re-added Scylla OSS cluster to scylla-manager because of a lot of tasks were created via deprecated `school` parameters. Now I see that backup task completed successfully, but Grafana dashboard `Scylla Manager Metrics` (which I've updated along with upgrading scylla-manager) doesn't show information about almost anything and reason is `scylla_manager_task_*` don't exists anymore.

I tried to execute `curl` on `scylla_manager_address:5090/metrics` and analyse result, but there nothing about `scylla_manager_task_*` metrics.

[Here](https://github.com/scylladb/scylla-monitoring/blob/scylla-monitoring-4.1.0/prometheus/prom_rules/prometheus.rules.yml) you can find actual rules of Scylla monitoring which I've applied along with scylla-manager upgrading, and because of the `manager:backup_progress` prometheus recording rule, for example, I'm asking about these metrics.

Can you, please, confirm that the metrics `scylla_manager_task_*` don't exist anymore or help with fix the issue if they still exist?

**Comment by mykaul** [comment]
CC @amnonh , @tnozicka

**Comment by Michal-Leszczynski** [comment]
There were changes in SM metrics (2.6 -> 3.0) which replaced `scylla_manager_task_*`  with `scylla_manager_scheduler_*`.  Currently it looks like that:
- `scylla_manager_task_run_total` -> `scylla_manager_scheduler_run_total`
- `scylla_manager_task_last_success` -> `scylla_manager_scheduler_last_success`
- `scylla_manager_task_active_count` -> `scylla_manager_scheduler_run_indicator` !!!
- `scylla_manager_task_last_run_duration_seconds` -> no metric for that !!!

So I assume that metrics specified [Here](https://github.com/scylladb/scylla-monitoring/blob/scylla-monitoring-4.1.0/prometheus/prom_rules/prometheus.rules.yml) should be updated.

**Comment by mrlexor** [comment]
Okay, I will change that metrics in my prometheus recording rules and I will review Grafana dashboard `Scylla Manager Metrics`. If everything will work fine I may create a merge request with fix this issue.

**Comment by Michal-Leszczynski** [comment]
The best way to check backup/repair progress is via [sctool progress](https://manager.docs.scylladb.com/stable/sctool/progress.html). It aggregates all progress info and prints it in an convenient way. 

Although SM doesn't have direct `scylla_manager_{backup/repair}_progress` metrics, they can be calculated from other metrics. For backup task we have:
- `scylla_manager_backup_files_size_bytes` -> Total size of backup files in bytes
- `scylla_manager_backup_files_uploaded_bytes`-> Number of bytes uploaded to backup location
- `scylla_manager_backup_files_skipped_bytes` -> Number of deduplicated bytes already uploaded to backup location
- `scylla_manager_backup_files_failed_bytes`-> Number of bytes failed to upload to backup location

So it's possible to calculate general progress of backup task by aggregating those information. The same goes for repair progress with metrics like: `scylla_manager_repair_token_ranges_total`, `scylla_manager_repair_token_ranges_success`, etc...

**Comment by mrlexor** [comment]
Yeah, I know about `sctool` CLI, but I wanted to understand what I need to do with the Grafana dashboard, I don't need information about progress of `repair` or `backup` there, but I don't want to make a lot of changes in prepared Grafana dashboards and prometheus recording rules by scylladb's command.

I assume my issue may be closed here and I will open the new one in another repo. Thank you.
