### ISSUE TITLE
A task that is created using the `interval` parameter changes its next run time after upgrade

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3283]
Versions before upgrade:
Client version: 3.0.2-0.20221128.23e30739
Server version: 3.0.2-0.20221128.23e30739

Versions after upgrade:
Client version: 3.1-dev-0.20230108.71ee737dafe-SNAPSHOT-71ee737dafe
Server version: 3.1-dev-0.20230108.71ee737dafe-SNAPSHOT-71ee737dafe

Before the upgrade, we first create a repair/backup task using the interval parameter:
```
< t:2023-01-09 01:46:13,465 f:cli.py          l:1061 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool repair -c 89648509-58c9-4e98-85ef-68be2d13bb06 --interval 1d'
< t:2023-01-09 01:46:13,762 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > repair/765dccdd-48f3-4294-8bf8-c5e96bed4325
< t:2023-01-09 01:46:13,763 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Flag --interval has been deprecated, use cron instead
```
*As a side note, I'm not sure why does creating a task with the interval param is possible in the first place, since it is deprecated as the message above states

When the task ends a few minutes later, its intended next run time is in 24 hours (at ~2023-01-10 01:46):
```
< t:2023-01-09 01:46:29,704 f:cli.py          l:1061 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool tasks -c 89648509-58c9-4e98-85ef-68be2d13bb06'
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ╭─────────────────────────────────────────────┬─────────────┬────────┬──────────┬─────────┬───────┬──────────────┬────────────┬────────┬──────────────╮
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ Task                                        │ Schedule    │ Window │ Timezone │ Success │ Error │ Last Success │ Last Error │ Status │ Next         │
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ├─────────────────────────────────────────────┼─────────────┼────────┼──────────┼─────────┼───────┼──────────────┼────────────┼────────┼──────────────┤
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/alternator                      │ @every 15s  │        │ UTC      │ 7       │ 0     │ 9s ago       │            │ DONE   │ in 5s        │
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/rest                            │ @every 1m0s │        │ UTC      │ 1       │ 0     │ 54s ago      │            │ DONE   │ in 5s        │
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/cql                             │ @every 15s  │        │ UTC      │ 7       │ 0     │ 9s ago       │            │ DONE   │ in 5s        │
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ repair/765dccdd-48f3-4294-8bf8-c5e96bed4325 │ 1d          │        │ UTC      │ 1       │ 0     │ 7s ago       │            │ DONE   │ in 23h59m43s │
< t:2023-01-09 01:46:29,831 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ╰─────────────────────────────────────────────┴─────────────┴────────┴──────────┴─────────┴───────┴──────────────┴────────────┴────────┴──────────────╯
```

After the upgrade, however, the intended run time changed to 22 hours in the future (at ~2023-01-09 23:46):
```
< t:2023-01-09 01:51:14,867 f:cli.py          l:1061 c:sdcm.mgmt.cli        p:DEBUG > Issuing: 'sctool tasks -c 89648509-58c9-4e98-85ef-68be2d13bb06'
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ╭─────────────────────────────────────────────┬─────────────┬────────┬──────────┬─────────┬───────┬──────────────┬────────────┬─────────┬─────────────╮
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ Task                                        │ Schedule    │ Window │ Timezone │ Success │ Error │ Last Success │ Last Error │ Status  │ Next        │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ├─────────────────────────────────────────────┼─────────────┼────────┼──────────┼─────────┼───────┼──────────────┼────────────┼─────────┼─────────────┤
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ backup/79a7fe0f-7307-4f9a-82f5-c7a66207b9a8 │ 1d          │        │ UTC      │ 1       │ 0     │ 4m17s ago    │            │ DONE    │ in 21h56m1s │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ backup/7d49b375-0041-4757-8b15-de7f4bf3a287 │             │        │ UTC      │ 1       │ 0     │ 3m54s ago    │            │ DONE    │             │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ backup/c4ae43e3-2853-466f-b5c7-bd3ecd1a9a68 │ 1d          │        │ UTC      │ 0       │ 0     │              │            │ STOPPED │ in 21h56m1s │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/alternator                      │ @every 15s  │        │ UTC      │ 21      │ 0     │ 1s ago       │            │ DONE    │ in 13s      │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/rest                            │ @every 1m0s │        │ UTC      │ 5       │ 0     │ 16s ago      │            │ DONE    │ in 43s      │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ healthcheck/cql                             │ @every 15s  │        │ UTC      │ 21      │ 0     │ 1s ago       │            │ DONE    │ in 13s      │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > │ repair/765dccdd-48f3-4294-8bf8-c5e96bed4325 │ 1d          │        │ UTC      │ 1       │ 0     │ 4m52s ago    │            │ DONE    │ in 21h56m1s │
< t:2023-01-09 01:51:14,987 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ╰─────────────────────────────────────────────┴─────────────┴────────┴──────────┴─────────┴───────┴──────────────┴────────────┴─────────┴─────────────╯
```

## The issue does not reproduce if the task is created using cron instead of interval.

# Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/5f18c785-28fc-452f-ae35-c777106282d4/20230109_015650/db-cluster-5f18c785.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/5f18c785-28fc-452f-ae35-c777106282d4/20230109_015650/loader-set-5f18c785.tar.gz
monitor-set (**Manager server log included**)- https://cloudius-jenkins-test.s3.amazonaws.com/5f18c785-28fc-452f-ae35-c777106282d4/20230109_015650/monitor-set-5f18c785.tar.gz
sct - https://cloudius-jenkins-test.s3.amazonaws.com/5f18c785-28fc-452f-ae35-c777106282d4/20230109_015650/sct-runner-5f18c785.tar.gz

**Comment by Michal-Leszczynski** [comment]
I believe that this problem isn't directly connected to upgrading SM, but rather to restarting SM. 
For both SM 3.0 and SM 3.1 scheduling task with `--interval` but without `--start-date` causes SM to believe that start date is set to `January 1, year 1, 00:00:00.000000000 UTC`, so after each restart SM calculates next task activation (for `--interval 1d`) to be about `23:46 UTC`

**Comment by ShlomiBalalis** [comment]
> I believe that this problem isn't directly connected to upgrading SM, but rather to restarting SM.
> 
> For both SM 3.0 and SM 3.1 scheduling task with `--interval` but without `--start-date` causes SM to believe that start date is set to `January 1, year 1, 00:00:00.000000000 UTC`, so after each restart SM calculates next task activation (for `--interval 1d`) to be about `23:46 UTC` - not exactly midnight because SM treats days as 86400 seconds.

That's VERY specific. I wouldn't have guessed that

> I already created PR with fix for this issue (#3284), but should we backport it into SM 3.0 as well?

I wouldn't spin a new release just for that but it would be great if it would be included in the next one.

My question is why do we still keep the option, if it's already deprecated?

**Comment by Michal-Leszczynski** [comment]
My guess would be that we have to keep that option because there still might be some clients that use it.
However, right now the main use case for SM is Scylla Cloud, so maybe we can actually get rid of it in the next release?
What do you think @karol-kokoszka ?

**Comment by karol-kokoszka** [comment]
We should keep it to have backward compatibility and potentially decide to fully remove with next major release (4.0) (if there will be any).
The point is that this bug could be introduced with Manager 3.0 release.

> For both SM 3.0 and SM 3.1 scheduling task with --interval but without --start-date causes SM to believe that start date is set to January 1, year 1, 00:00:00.000000000 UTC

This statement seems not to be true in manager < 3.0.
See https://github.com/scylladb/scylla-manager/blob/1ced933657004269909f83397b3738e6bc230819/pkg/cmd/sctool/backup.go#L138-L145
And then see https://github.com/scylladb/scylla-manager/blob/1ced933657004269909f83397b3738e6bc230819/pkg/managerclient/utils.go#L64-L66

Check on `--start-date` that validates if the date is < now is removed in 3.0. The whole cmd flag parsing is basically refactored.

I guess we should bring it back.

**Comment by karol-kokoszka** [comment]
Examples above comes from `branch-2.6`

**Comment by Michal-Leszczynski** [comment]
I think that using strict comparison between time values can introduce unexpected  behaviors.

Right now, if user provide `--start-date now`, the `now` value is translated into time while parsing command args, so if we compare time value obtained in this way with current time when scheduling a task, we might get that the time from `--start-date now` is in the past.

On the other hand, if `--start-date` flag is not specified, start date is set to zero value, which is checked when scheduling a task and if it happens, scheduler remembers to run this task right after it's scheduled and sets start date to current time.

So even though it's rather unexpected, I believe that NOT specifying `--start-date` flag gives better result (ensures that task will be run right after schedule and not after interval time) than using `--start-date now`.

My proposition is to add separate function for parsing `--start-date` which would set start date to zero value if it encounters direct `now` (so `now+2h` would still be calculated when parsing command args). This way we can be sure that if task was supposed to be run right after schedule, the strict time comparison won't cause any issues, so we can also validate that the start date cannot be in the past.

What do you think @karol-kokoszka ?

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski makes sense. Go for it !
