### ISSUE TITLE
[SPIKE] Check possibilities of storing multiple SSTable versions in backup

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3288]
We need to find a way of storing multiple versions of single SSTable in backup location.

Option with enabled object versioning on cloud storage.
- verify whether S3 object versioning and GCS object versioning meets our requirements
- validate if Rclone fork we use, supports object versioning on S3 and GCS
- validate if it's possible to choose expected version of object when downloading backup with `download-files` (following restore procedure from ansible script) - we should rely on object version creation timestamp + snapshot tag that is the timestamp
- check the costs of enabling versioning on S3/GCS buckets

Option with artificially added snapshot tag to the object name in cloud storage.
- verify that we can easily update metadate file and clean it when manager downloads it to perform restore
- verify that RClone can rename file when moving it to cloud storage
- validate that the change is compatible with already existing backups

@Michal-Leszczynski please add anything what you think is relevant to verify/validate here.

Expected output from this task is to have verified/validated plan of adding support for multiple SSTable versions in backup location that will play well with the restore procedure.

**Comment by mykaul** [comment]
S3 object version is probably our best path. rclone (AFAIR, did not check) supports versioning.

**Comment by karol-kokoszka** [comment]
@mykaul Yes, it's our preferred way of going forward. Just need to check how RClone supports it.

**Comment by Michal-Leszczynski** [comment]
I looked into latest version of RClone  and it supports file versioning only for chosen backends, so while s3 is supported, gcs is not, so this option does not solve our problem.

Suggested approaches to file versioning supported for all backends are:
 - [--suffix](https://rclone.org/docs/#suffix-suffix): instead of overwriting a file, old version is kept with specified suffix.
 - [--backup-dir](https://rclone.org/docs/#backup-dir-dir): instead of overwriting a file, old version is moved to specified dir.

Those solutions are convenient because they don't require any changes in backup procedure, although restore and purge still needs to be adjusted.
I believe that in order to safely use those options we would have to be able to modify rclone config, which is currently forbidden in our forked Rclone repo, so we would need to modify our fork.

**Comment by mykaul** [comment]
Thanks for looking into it @Michal-Leszczynski ! 
Two options I'd like us to consider:
1. Have this features as a S3 only, not supported on GCS
2. Contribute this enhancement to rclone (I have absolutely no idea how complex it'd be!).

The first one makes most sense to me.

**Comment by tomer-sandler** [comment]
Hello @Michal-Leszczynski @karol-kokoszka @mykaul @DoronArazii , any updates?

**Comment by Michal-Leszczynski** [comment]
Hi, sorry that it drags out for so long, but I will provide docs with possible solutions to this problem from SM perspective today or tomorrow. The ideas for solutions are already there, but I needed to validate them on local tests so that they have at least some proof behind them.

**Comment by Michal-Leszczynski** [comment]
Here is a link to a [doc](https://docs.google.com/document/d/1_btU9TLwHf6mcRqtS0kRcWpaafkbVER6EixjvNWo8tQ/edit?usp=sharing) describing possible approaches to solving this issue. I will start implementing it at the beginning of the next week and I hope that (if nothing unexpected happens) I will be able to finish it before the end of next week.

**Comment by Michal-Leszczynski** [comment]
Please take a look.
@karol-kokoszka  @mykaul  @tomer-sandler @tzach

**Comment by tomer-sandler** [comment]
> Here is a link to a [doc](https://docs.google.com/document/d/1_btU9TLwHf6mcRqtS0kRcWpaafkbVER6EixjvNWo8tQ/edit?usp=sharing) describing possible approaches to solving this issue. I will start implementing it at the beginning of the next week and I hope that (if nothing unexpected happens) I will be able to finish it before the end of next week.

@vladzcloudius @tarzanek  your inputs are appreciated. Thanks!

**Comment by mykaul** [comment]
Is this item targeted for 3.1 or later?

**Comment by karol-kokoszka** [comment]
@mykaul It's going to be a part of 3.1 release, but the work is still in progress.
