### ISSUE TITLE
Use ansible script for universal restore

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3299]
Right now we have an ansible script that can perform complete restore.
One of its steps consists of wiping all cluster data and basically resetting cluster into its initial state.

This step can be useful for users which want to restore schema with universal restore.
Restoring schema requires that user ensures that there is no overlapping schema in destination cluster and AFAIK the only way to achieve that would be to do the very same thing as ansible script does.

Maybe it would be convenient for user to provide such script?

@karol-kokoszka  @tzach

**Comment by karol-kokoszka** [comment]
Out of scope
