### ISSUE TITLE
Restore progress skipped/deduplicated information

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3320]
Backup progress informs us about the amount of `deduplicated bytes` - which is obviously a useful information, because we expect that many SSTables from given snapshot are already present in the backup location.  When I was writing restore progress display, I was heavily influenced by the backup progress display, so I also included this information in it.

Looking at it now, this is not that great in terms of restore, because we don't expect any SSTables to be present in the upload dir - restore should take care of downloading all SSTables from backup location, so the expected amount of deduplicated bytes should be 0 (it can be greater than 0 as a side effect of pausing and resuming restore - deduplicated bytes would describe the amount of bytes downloaded before the pause, but this sounds like a misleading information, because those bytes were still downloaded within the same task).

I just want to make sure that removing `deduplicated bytes` column from restore progress display is the right direction.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka @tzach am I right with this one?

**Comment by tzach** [comment]
What is the restore process restart? Does the deduplication allow you to download only the missing sstables?

**Comment by Michal-Leszczynski** [comment]
In general rclone always 'skips' transferring a file to remote destination if this file is already there - my question is only about displaying restore progress and not changing the procedure itself.

In case of restore procedure, SM remembers which bundles of files were already fully downloaded before interruption (e.g. task pause, SM crash) and it does not try to download them again. SM also remembers bundles of files which download was interrupted and recreates rclone job to download them again. Here, some of those files might already been fully downloaded into remote destination before the interruption occurred, so the recreated job will skip those files.

Here is an example of restore procedure with two possible progress displays:
- The upload dir to which SM will be downloading files is empty (as expected - it should always be empty at the start of restore procedure)
- SM starts downloading file bundle consisting of two files A and B
- Rclone finished downloading file A
- Restore task gets paused
- ...
- Restore task gets resumed
- SM see that the download of file bundle A and B got interrupted, so it retries that
- Rclone skips downloading file A because it's already there, so it only downloads file B
- Restore finishes
- User asks for restore progress

When we display restore progress, should file A be marked as downloaded or deduplicated?
From rclone perspective, file A has been deduplicated, because it has already been present in the upload dir when the download was retried. But from user perspective, it would probably be more useful to mark it as downloaded, because it happened during the same task run, but before the interruption.

**Comment by tzach** [comment]
Thanks for the detailed explanation.
Your view (user perspective) makes sense to me.
