### ISSUE TITLE
SM 3.1: `1680223234483_manager_restore_tests.py::TestScyllaMgmtRestore::test_restore_alter_batch_size` regression

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3341]
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/manager-dtest/22/testReport/junit/manager_restore_tests/TestScyllaMgmtRestore/test_restore_alter_batch_size/

artifacts:
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.1/job/manager-dtest/22/artifact/scylla-dtest/logs/1680223234483_manager_restore_tests.py%3A%3ATestScyllaMgmtRestore%3A%3Atest_restore_alter_batch_size/

**Comment by Michal-Leszczynski** [comment]
This is the same situation as the one described [here](https://github.com/scylladb/scylla-manager/issues/3340#issuecomment-1491631463).

@ShlomiBalalis

**Comment by karol-kokoszka** [comment]
Closing in favor of issue in dtest repo https://github.com/scylladb/scylla-dtest/issues/3107
