### ISSUE TITLE
Scylla Manager on Ubuntu 22

### ISSUE THREAD

**Issue by gatchajc** [scylladb/scylla-manager#3343]
Hi Team!

May I ask if there is a plan or an ETA on having a version of scylla manager that's supported for ubuntu 22?

There are customers that are asking about this. 

Thank you!

**Comment by karol-kokoszka** [comment]
@gatchajc we actually have the commit on master https://github.com/scylladb/scylla-manager/commit/adccf8cf44f427685f633051bc5a762c156cce69
I was wondering about moving it to 3.1 release.
But seems it's a must.
OK, consider it's done.

**Comment by gatchajc** [comment]
Thank you @karol-kokoszka !
