### ISSUE TITLE
scylla manager repair keyspace by keyspace, table by table - starting with small (system) tables

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-manager#3362]
Consider a cluster  with the following tables:

```
keyspace | table
system_auth                   │                 role_attributes
system_auth                   │                    role_members
system_auth                   │                role_permissions
system_auth                   │                           roles
system_traces                 │                          events
system_traces                 │                   node_slow_log
system_traces                 │          node_slow_log_time_idx
system_traces                 │                        sessions
system_traces                 │               sessions_time_idx
system_distributed            │                 cdc_description
system_distributed            │     cdc_generation_descriptions
system_distributed            │       cdc_generation_timestamps
system_distributed            │     cdc_streams_descriptions_v2
system_distributed            │        cdc_topology_description
system_distributed            │                  service_levels
system_distributed            │               view_build_status
system_distributed_everywhere │  cdc_generation_descriptions_v2
k1 | t1
k1 | t2
k1 | t3
k2 | t1
k2 | t2
k2 | t3
```

Currently, scylla manager will repair all tables in parallel. 

It is better to repair keyspaces and tables in serial. 

For example,  scylla manager starts with the small but important system keyspaces first, then repair user keyspaces. 

- Repair system_auth.role_attributes first then move to system_auth. role_members and finish the rest tables inside system_auth. 
- Then repair system_traces keysapce
- Repair system_distributed keyspace
- Repair system_distributed_everywhere keyspace
- Repair k1 keyspace
- Repair k2 keyspace

It is better this way because:

- table with more data won't block tiny keyspaces, e.g., system tables
- off strategy is more efficient to compact sstables generated by repair of a specific table
- the duration to repair a specific table is more accurate, avoid the time to wait other tables to finish

**Comment by mykaul** [comment]
@karol-kokoszka - I'm setting this tentatively to 3.1.1 - let me know if it's not feasible and push accordingly.

**Comment by mykaul** [comment]
@asias - just to clarify the request - is there an issue with repair the user tables concurrently?

**Comment by noellymedina** [comment]
@mykaul there is, https://github.com/scylladb/scylla-enterprise/issues/2661 
also I have other customer who would benefit from this (no existing Gh although)

**Comment by asias** [comment]
> @asias - just to clarify the request - is there an issue with repairing the user tables concurrently? I understand and agree with the ordering and serialization of the system of course.

Scylla core has no limitation on the repair of multiple tables in parallel. It should work but serialization on the tables makes it more efficient.

**Comment by karol-kokoszka** [comment]
@asias I found the repair design doc https://docs.google.com/document/d/1E4Dl3VNdtkKY3jIE7jPCHEivNRq1LVV2j2hIshafu5c/edit#

I one of the comments, you talk with Michał Matczuk about repairing tables one by one, see https://docs.google.com/document/d/1E4Dl3VNdtkKY3jIE7jPCHEivNRq1LVV2j2hIshafu5c/edit?disco=AAAAGgkdaAQ

From what I understood, the assumption was that Scylla Manager will repair tables one by one and they will not  be handled in parallel. 
This comment https://github.com/scylladb/scylla-enterprise/issues/2661#issuecomment-1501927705 shows that it's not true though and tables are handled in parallel.

@asias do you remember if it ever was handled table by table ? 

I'm just wondering if repairing in parallel is some sort of bug or if handling tables one by one was never implemented actually (or if the comment I mentioned is about something completely different :) )

**Comment by karol-kokoszka** [comment]
Proposal:
- define the repair order during repair initialization
   a) system keyspace first
   b) user keyspaces next
- extend repair's generator fillNext method to create repair jobs/chunks following the predefined order. See https://github.com/scylladb/scylla-manager/blob/d01a18c6bea9ffb44691093363a218c0e6202dd4/pkg/service/repair/generator.go#L293
- make sure that fix doesn't break pause/resume feature
- create integration-test that checks the repair order 

Estimation: 8

**Comment by asias** [comment]
> @asias I found the repair design doc https://docs.google.com/document/d/1E4Dl3VNdtkKY3jIE7jPCHEivNRq1LVV2j2hIshafu5c/edit#
> 
> In one of the comments, you talk with Michał Matczuk about repairing tables one by one, see https://docs.google.com/document/d/1E4Dl3VNdtkKY3jIE7jPCHEivNRq1LVV2j2hIshafu5c/edit?disco=AAAAGgkdaAQ
> 
> From what I understood, the assumption was that Scylla Manager will repair tables one by one and they will not be handled in parallel. This comment [scylladb/scylla-enterprise#2661 (comment)](https://github.com/scylladb/scylla-enterprise/issues/2661#issuecomment-1501927705) shows that it's not true though and tables are handled in parallel.
> 
> @asias do you remember if it ever was handled table by table ?
> 
> I'm just wondering if repairing in parallel is some sort of bug or if handling tables one by one was never implemented actually (or if the comment I mentioned is about something completely different :) )

The discussion in the design doc is about the same thing as this GH. Scylla manager is supposed to repair table by table. You can check with extra logs if needed and verify with the current code in scylla manager.  What makes me think we probably have issues in the scylla manager scheduling is that multiple tables finished some percentages.

**Comment by asias** [comment]
> * define the repair order during repair initialization
>       a) system keyspace first
>       b) user keyspaces next

In side B, finish base table first then repair the mv tables.

**Comment by karol-kokoszka** [comment]
That one is not part of 3.1.1.
We revisit repair in 3.2.

**Comment by karol-kokoszka** [comment]
Moved to v3.2
We are going to revisit current repair implementation.
See https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit
