### ISSUE TITLE
Once a restore task ends, revert the tombstone_gc mode of any restored table back to its original state

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3363]
As stated in https://github.com/scylladb/scylla-dtest/issues/3108, when a restore task starts, the manager alters the `tombstone_gc` mode of any table that is involved in the restore to `disabled`.
But when the restore task ends the manager does not revert the mode back to its value before the restore has started.

To prevent a potentially large buildup of tombstones, the manager should revert the tombstone_gc mode back to its original value.

**Comment by karol-kokoszka** [comment]
The assumption is that we automate to execute the repair before bringing back proper `tombstone_gc` value.

Estimation: 5

**Comment by karol-kokoszka** [comment]
> Right now, when we are restoring schema, we require all nodes in the cluster to be available and in the UN state.
Can we have the same requirement when restoring tables?

Yes, we can.
