### ISSUE TITLE
Repair base table before view table (MV and secondary indexes)

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-manager#3367]
Repair of the base table will trigger view update to the view tables, which will reduce the mismatch of the view tables. So it is more efficient to repair base tables before repair any view tables built from the base table.  

UPDATE (@karol-kokoszka):
- this feature will be available only if CQL credentials are provided to scylla-manager

**Comment by mykaul** [comment]
@karol-kokoszka - optimistically setting this to 3.1.1, feel free to push to 3.2 if it's too complex/risky (I doubt the latter).

**Comment by tzach** [comment]
ScyllaDB restore procedure include the following:

> Best practise is not to restore [Materialized Views (MV)](https://docs.scylladb.com/stable/using-scylla/materialized-views.html) and [Secondary Indexes (SI)](https://docs.scylladb.com/stable/using-scylla/secondary-indexes.html) SSTables. It is recommended to:
> 
> Drop the MV and SI using DROP MATERIALIZED VIEW or DROP INDEX
> 
> Restore the base table only (see below)
> 
> Recreate the MV or SI, using the original description from the CQL backup, using CREATE MATERIALIZED VIEW or CREATE INDEX
source: https://docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html

If this is valid for Manager (at least for 3.0 and 3.1) it needs to be explicity mentioned.
If MV and SI are part of the bacup,  we need to fix it.

**Comment by karol-kokoszka** [comment]
Basing on the assumption that #3362 is implemented first, there is a need to query system tables against existing views and place them at the end of the repair order.

Estimation: 1

**Comment by karol-kokoszka** [comment]
Moved to v3.2
We are going to revisit current repair implementation.
See https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit
