### ISSUE TITLE
Restore: add backoff/retry on disabling tombstone_gc

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3379]
Add backoff/retry mechanism on disabling tombstone_gc in restore procedure.
https://github.com/scylladb/scylla-manager/blob/e4ba01c5fa277cb34e4a3ba3e7dcef5861c5ca82/pkg/service/backup/restore_worker_tables.go#L30-L36

When there is hundrends/thousands of tables in the backup location, it may happen that scylla will get stuck for a moment when trying to disable tomstone_gc. These requests should be backed off.

https://github.com/scylladb/scylla-manager/issues/3326

**Comment by mykaul** [comment]
I'm unsure why it did not go to 3.1.1, I hope it doesn't delay 3.1.0.

**Comment by karol-kokoszka** [comment]
It's merged and fixed already anyway.
