### ISSUE TITLE
docs: Issue in page ScyllaDB Manager Upgrade

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-manager#3400]
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.1/upgrade/index
It's relevant also for SM 3.0 upgrade page

### Problems
1. Centos/RHEL and Debian/Ubuntu show the same repo
![image](https://github.com/scylladb/scylla-manager/assets/25585995/54348dcf-62e2-411b-ba8b-85cabef16919)

2. SM 3.1 upgrade page shows the instructions of SM 3.0 upgrade

###  Suggest a fix
1. Correct repo/pkgs for SM 3.1 for Ubuntu 20.04
https://www.scylladb.com/download/?platform=ubuntu-20.04&version=manager-3.1#manager
![image](https://github.com/scylladb/scylla-manager/assets/25585995/f654d00b-3925-4d79-a62c-9729d1338dd1)

2. Correct repo/ pkgs for SM 3.0 for Ubuntu 20.04
https://www.scylladb.com/download/?platform=ubuntu-20.04&version=manager-3.0#manager
![image](https://github.com/scylladb/scylla-manager/assets/25585995/bd067580-1663-418b-bcda-20a8dc0aea89)

3. We should have upgrade docs matrix for various OS (like we have for Scylla Core)
  - RHEL/CentOS
  - Ubuntu 16/18/20/22

**Comment by annastuchlik** [comment]
Thanks for reporting. I've added a [separate issue](https://github.com/scylladb/scylla-manager/issues/3401) to add a matrix.

**Comment by annastuchlik** [comment]
I started using the procedure, and it's totally pointless to include all links - they are only used to illustrate the outcome of the commands. 
The step is about the command to display the contents of ``scylla-manager.repo`` (the content may change between the releases, so the max we can do is to document an example).

**Comment by tomer-sandler** [comment]
Our customers go to Scylla Manager upgrade/fresh install for Ubuntu (Debian) and get instructions for CentOS/RHEL.
This was reported by 3 different customers, thus we should definitely do something about it @annastuchlik 

![image](https://github.com/scylladb/scylla-manager/assets/25585995/7110ff9b-b24e-4916-85f8-d6c29108a0c5)

**Comment by tzach** [comment]
> Centos: https://downloads.scylladb.com/rpm/centos/scylladb-manager-3.0
> Ubuntu: http://downloads.scylladb.com/deb/ubuntu/scylladb-manager-3.0
> Debian: http://downloads.scylladb.com/deb/debian/scylladb-manager-3.0

This links does not work for me

@tomer-sandler where is this screen capture from? please provide a link

**Comment by annastuchlik** [comment]
@tzach It's taken on the Upgrade Manager page: https://manager.docs.scylladb.com/branch-3.1/upgrade/index

@tomer-sandler I totally understand why customers had problems with the instructions, but the problem is bigger than just incorrect links.
The links are provided for reference only - we don't add them separately for each version. It's the upgrade procedure that is unclear. See the related PR I've opened - we need input from @karol-kokoszka and @roydahan to fix the procedure.

**Comment by karol-kokoszka** [comment]
@annastuchlik input is in the PR.

**Comment by annastuchlik** [comment]
@tomer-sandler The problem you reported was greater than simply incorrect links. The upgrade procedure had to be fixed. Please see the new PR I opened above.
