### ISSUE TITLE
Possible bug in 3.1 backup retention

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla-manager#3415]
Since upgrading from Manager 3.0 to 3.1 I noticed my AWS S3 usage climbing steadily. After examining it, it appears the old backups aren't being removed properly? Or something changed in how things operate, I am not clear?

I have updated my backup task to all add "--retention-days 2", but I still see older backups kept. I also tried deleting my entire S3 bucket to restart from scratch, and remade my backup task in 3.1, but still seeing this behavior.

My backup task looks like: sctool backup -c clustername -L 's3:scylla-cluster-1-snapshots' -s '2023-05-29T04:00:00Z' -i 24h --retention 2 --retention-days 2

I have run the backup validate task with the option to purge orphaned items, and it found 0 items to purge.

Here is the backup as described by the update command: sctool backup update -c clustername --dry-run

> NOTICE: dry run mode, backup is not scheduled
> 
> Data Centers:
>   - us-east
> 
> Keyspaces:
>   - system_auth all (4 tables)
>   - system_distributed all (4 tables)
>   - system_distributed_everywhere all (1 table)
>   - system_traces all (5 tables)
>   - mytables all (36 tables)
>   - scylla_manager all (14 tables)
>   - system_schema all (15 tables)
> 
> Disk size: ~5.130T
> 
> Locations:
>   - s3:scylla-cluster-1-snapshots
> 
> Bandwidth Limits:
>   - 100 MiB/s
> 
> Snapshot Parallel Limits:
>   - All hosts in parallel
> 
> Upload Parallel Limits:
>   - All hosts in parallel
> 
> Retention: Last 2 backups

Here is the backup list, as you can see it is keeping way more than 2 backups/2 days: sctool backup list -c clustername

> NOTICE: this may take a while, we are reading metadata from backup location(s)
> backup/dc5c6378-ec03-40cd-a83d-65582470b10c
> Snapshots:
>   - sm_20230610040002UTC (5.126T, 3 nodes)
>   - sm_20230609040002UTC (5.122T, 3 nodes)
>   - sm_20230608040001UTC (5.114T, 3 nodes)
>   - sm_20230606105943UTC (5.104T, 3 nodes)
>   - sm_20230603040000UTC (5.053T, 3 nodes)
>   - sm_20230602040002UTC (5.039T, 3 nodes)
>   - sm_20230601040002UTC (5.021T, 3 nodes)
>   - sm_20230531040004UTC (5.004T, 3 nodes)
>   - sm_20230530063209UTC (4.981T, 3 nodes)

Please let me know if there was some change in 3.1 that is causing this, and how I can correct it, thanks.

**Comment by tzach** [comment]
@karol-kokoszka could it be related to https://github.com/scylladb/scylla-manager/issues/3355 or https://github.com/scylladb/scylla-manager/pull/3321?

@ShlomiBalalis please try to repreduce

**Comment by Michal-Leszczynski** [comment]
Hi @A-Posthuman and thanks for reporting this issue!
Could you provide us with corresponding Scylla Manager logs, so that we can have a better insight at what happened?

**Comment by A-Posthuman** [comment]
Sure, it looks like I have several MB of logs from "journalctl --since "3 days ago" _COMM=scylla-manager", is there some particular lines from it you're interested in?

**Comment by A-Posthuman** [comment]
This could be the issue, I got this error from sctool while attempting to manually delete one of the old snapshots. 2 previous manual deletions worked ok, but this one had an error:

> Error: delete snapshots
>  172.31.128.7: delete: file backup/sst/cluster/24f9c1c1-b208-4c8e-890e-d2923a39aa88/dc/us-east/node/8128b3a1-5316-43b9-9618-4d56bbc95563/keyspace/mykeyspace/table/mytable/0b580f80aaf611ecb3b23c2fd9d352e4/me-4403566-big-Filter.db: giving up after 2 attempts: after 30s: context deadline exceeded; file backup/sst/cluster/24f9c1c1-b208-4c8e-890e-d2923a39aa88/dc/us-east/node/3718791e-9696-456e-91c7-7feb05b905bf/keyspace/mykeyspace/table/mytable/0b580f80aaf611ecb3b23c2fd9d352e4/me-4321840-big-CompressionInfo.db: giving up after 2 attempts: after 30s: context deadline exceeded; file backup/sst/cluster/24f9c1c1-b208-4c8e-890e-d2923a39aa88/dc/us-east/node/e543e6c6-c86c-46a4-a4cb-f1be8e7ac9ff/keyspace/mykeyspace/table/mytable/0b580f80aaf611ecb3b23c2fd9d352e4/me-4263043-big-TOC.txt: giving up after 2 attempts: after 30s: context deadline exceeded
> Trace ID: Pmxya6jrSi2h2FqLzJo2ZA (grep in scylla-manager logs)

This cluster is under very heavy load currently. Is the backup deletion unreliable under high loads?

**Comment by A-Posthuman** [comment]
Ok I've attached the logfile from a 24 hr period containing a completed backup task, starting at this line:

> Jun 11 00:00:00 ip-172-31-112-5 scylla-manager[337974]: {"L":"INFO","T":"2023-06-11T00:00:00.008-0400","N":"scheduler.24f9c1c1","M":"Run started","task":"backup/dc5c6378-ec03-40cd-a83d-65582470b10c","retry":0,"_trace_id":"QXibaLj6Rs-nYygq72dbQA"}

and ending with:

> Jun 11 08:35:58 ip-172-31-112-5 scylla-manager[337974]: {"L":"INFO","T":"2023-06-11T08:35:58.442-0400","N":"scheduler.24f9c1c1","M":"Run ended","task":"backup/dc5c6378-ec03-40cd-a83d-65582470b10c","status":"DONE","duration":"8h35m58.415172612s","_trace_id":"QXibaLj6Rs-nYygq72dbQA"}

At the time this backup ran, there were several undeleted backups/snapshots as described in my first message in this issue.

Regarding the version, I can dig into it further if you need me to, let me know what steps to perform, but AFAIK I upgraded it normally, the steps were:

1. I noticed the announcement of the Manager 3.1 release around May 8th.
2. Around May 10th according to the last modified time on /etc/apt/sources.list.d/scylla-manager.list, I updated that sources file read:

> deb  [arch=amd64,arm64] http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.1 stable main

3. I ran sudo apt update, sudo apt-get dist-upgrade, then Manager updated to 3.1. Also around this time I similarly upgraded the Agents on each Scylla node to 3.1.

4. I confirmed just now that the scylla-manager process has a start time on May 10th on the server.

[scylla-manager.logs.txt](https://github.com/scylladb/scylla-manager/files/11751037/scylla-manager.logs.txt)

**Comment by Michal-Leszczynski** [comment]
We had a problem regarding SM 3.1 release as we accidentally released the wrong version at the beginning.
It was discovered and fixed short time after that, but it looks like your SM upgrade suffered from this issue, even though your upgrade procedure was properly executed.

In order to get the correct version of SM you would have to reinstall it. Unfortunately, there is one problem with that.
The incorrect version of SM has slightly different schema of the restore task (kept inside SM database), so even when you reinstall SM, it won't start, as it will complain about that. In order to fix that, you would  have to delete the whole SM keyspace, so that the correct version of SM 3.1 could recreate the schema from scratch. This would also mean, that **all of your tasks saved in manager DB would be lost, so you would have to recreate them after this step!!!**. 

This procedure would look similar to the general [upgrade procedure](https://manager.docs.scylladb.com/stable/upgrade/#upgrade-procedure), with the additional step of executing:
```
DROP KEYSPACE scylla_manager;
```
on SM database via `cqlsh` before starting SM.

There is also another approach. If you haven't used your SM for restoring data (`sctool restore`) from backup, instead of droping the whole SM keyspace, you could mannually apply required schema changes in SM database. This would once again look similar to the general [upgrade procedure](https://manager.docs.scylladb.com/stable/upgrade/#upgrade-procedure), with the additional step of executing:
```
ALTER TABLE scylla_manager.restore_run_progress ADD versioned_progress bigint;
ALTER TABLE scylla_manager.restore_run ADD location text;
UPDATE scylla_manager.gocqlx_migrate SET checksum = '7cb98d445928959e06fcb9f893f10ad4' WHERE name = 'v3.1.0.cql';
```
on SM database via `cqlsh` before starting SM.

Those statements perform missing schema changes and let SM know, that they were properly applied.

These are the only two solutions I can currently think of and I am really sorry, that this problem occurred in the first place. I hope that this will make it possible to fix it.

**Comment by A-Posthuman** [comment]
Ok, thank you for the tips on how to correct it. As for uninstalling/reinstalling the current Manager 3.1, would I simply do:

1. Uninstall the package using apt, (then fix the table(s) as you mentioned), then reinstall using apt?

Is the current version of Manager that apt reinstalls going to be the updated 3.1 package, or do I need to alter my sources file contents:

> deb [arch=amd64,arm64] http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.1 stable main

And lastly, do I also need to uninstall/reinstall the Manager Agent packages on the Scylla instances, or are those ok to leave as-is?

In the future I guess my suggestion should a buggy release like this happen again would be to release a further minor point release like 3.1.1 or something? Then maybe apt could have simply upgraded my install. But perhaps that wouldn't work in this case due to needing to fix the tables.

**Comment by Michal-Leszczynski** [comment]
> And lastly, do I also need to uninstall/reinstall the Manager Agent packages on the Scylla instances, or are those ok to leave as-is?

Agents should also be reinstalled as their code was also changed in the SM 3.1.

> Uninstall the package using apt, (then fix the table(s) as you mentioned), then reinstall using apt?

This should work, but it should be done like in the upgrade procedure (wait for SM to finish its tasks, stop SM and agents before reinstalling, etc.)

> deb [arch=amd64,arm64] http://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.1 stable main

This link looks good.

> In the future I guess my suggestion should a buggy release like this happen again would be to release a further minor point release like 3.1.1 or something? Then maybe apt could have simply upgraded my install. But perhaps that wouldn't work in this case due to needing to fix the tables.

Unfortunately, as you suspected, this would still require some workaround.

**Comment by A-Posthuman** [comment]
Ok I believe I have everything uninstalled/reinstalled. I saw on some of the instances apt had cached copies of the packages, so I ran "sudo apt-get clean" everywhere before reinstalling, to make sure I should have the new code.

I deleted all the old backups, cleared the snapshots, etc. And have now remade the backup task in sctool. So if it's ok with you, can we leave this issue open for several more days until I can get a few backups completed and we'll see if they have correct retention now? I will post an update here eventually to let you know if it's fixed.

**Comment by A-Posthuman** [comment]
Ok I can provide an update, and it's good news the retention system is now working properly.

The only remaining issue I see in the logs and Grafana dashboard now are occasional upload failures to S3, I don't know if that is "normal", or potentially related to my cluster being heavily loaded? I seem to see them cropping up mostly in the latter part of the backup process like when it gets into the last 10% or so of bytes remaining.

In the logs they mention a S3 error about timeouts:

`Jun 24 16:00:44 ip-172-31-112-5 scylla-manager[590134]: {"L":"ERROR","T":"2023-06-24T16:00:44.515-0400","N":"backup.upload","M":"Failed to upload host","host":"172.31.128.8","keyspace":"mykeyspace","table":"mytable","error":"mykeyspace.mytable: upload snapshot: copy \"data:mykeyspace/mytable-e0656bf00faf11ed85ccd661445acfca/snapshots/sm_20230624040005UTC\" to \"s3:scylla-cluster-1-snapshots/backup/sst/cluster/874b5931-6587-4d09-8c08-6ef319e0175d/dc/us-east/node/e543e6c6-c86c-46a4-a4cb-f1be8e7ac9ff/keyspace/mykeyspace/table/mytable/e0656bf00faf11ed85ccd661445acfca\": job error (1687551069): s3 upload: 400 Bad Request: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>7RAHX53AJ0M87AZP</RequestId><HostId>RVvry8gaLGgmnU9w/SjgajiFDT7R3BFupsYafRgzi8c06KBPByfVTw2X8cD1wxMFAOf23rcegy4=</HostId></Error>; mytable-e0656bf00faf11ed85ccd661445acfca/snapshots/sm_20230624040005UTC/me-121729-big-Data.db s3 upload: 400 Bad Request: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>7RAHX53AJ0M87AZP</RequestId><HostId>RVvry8gaLGgmnU9w/SjgajiFDT7R3BFupsYafRgzi8c06KBPByfVTw2X8cD1wxMFAOf23rcegy4=</HostId></Error>; mytable-e0656bf00faf11ed85ccd661445acfca/snapshots/sm_20230624040005UTC/me-121729-big-Data.db s3 upload: 400 Bad Request: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>7RAHX53AJ0M87AZP</RequestId><HostId>RVvry8gaLGgmnU9w/SjgajiFDT7R3BFupsYafRgzi8c06KBPByfVTw2X8cD1wxMFAOf23rcegy4=</HostId></Error>","_trace_id":"zEBjJOQqTpaKoYxdSqfxJQ","errorStack":"github.com/scylladb/scylla-manager/v3/pkg/service/backup.(*worker).uploadHost.func1.2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/worker_upload.go:75\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*worker).uploadHost.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/worker_upload.go:93\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parallel.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:72\nruntime.goexit\n\truntime/asm_arm64.s:1172\n","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/service/backup.(*worker).uploadHost.func2\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/worker_upload.go:101\ngithub.com/scylladb/scylla-manager/v3/pkg/util/parallel.Run.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:79"}`

The backup does eventually reach 100% despite a few of these errors, and in sctool tasks it shows it eventually counted as a Success and the backup retention rotation occurs to then remove the oldest backup. So does this mean despite these occasional upload errors that the backup is completing successfully and I don't need to worry about these errors?

This log is from Manager/Agent 3.1.1

Thx

**Comment by Michal-Leszczynski** [comment]
If the backup is in a success state, then there should be nothing to worry about:)
