### ISSUE TITLE
Manager is using an old version of gocqlx

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3416]
github.com/scylladb/gocqlx/v2 v2.6.1-0.20211220144210-2b885ac61b11 - while there's already 2.8.0 (and more commits beyond that).
Would be good to use later versions.

**Comment by mykaul** [comment]
Also gocql itself?
github.com/gocql/gocql => github.com/scylladb/gocql v1.5.1-0.20210906110332-fb22d64efc33

**Comment by karol-kokoszka** [comment]
@charconstpointer please take care on the issue. 
gocqlx needs to be upgraded and validated (integration-tests should be enough).

Besdies, please check if we can get rid of this https://github.com/scylladb/scylla-manager/blob/97ee657da22654ca08ab93ca8e31ca0c10efed08/go.mod#L120
And just use scylladb/gocql in imported dependencies.
