### ISSUE TITLE
IPv6 testing env (new docker-compose)

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3419]
We need to have a docker-compose that creates IPv6 environment.
Right now, our integration-tests are checking SM behavior against IPv4 setup only, see https://github.com/scylladb/scylla-manager/blob/master/testing/docker-compose.yaml

The idea behind this issue is to have:
- another docker-compose that creates the IPv6 env
- docker-compose for IPv6 should mirror the current compose file for IPv4 (with 2 networks see this PR https://github.com/scylladb/scylla-manager/pull/3418)
- another targets in Makefile that will trigger integration tests execution against IPv6 env (see https://github.com/scylladb/scylla-manager/blob/97ee657da22654ca08ab93ca8e31ca0c10efed08/Makefile#L105-L110)
- IPv6 integration tests must be included into GH actions https://github.com/scylladb/scylla-manager/tree/master/.github/workflows

**Comment by karol-kokoszka** [comment]
Example draft compose file with IPv6 support is on this branch https://github.com/scylladb/scylla-manager/tree/ipv6_compose_draft

**Comment by karol-kokoszka** [comment]
@dkropachev assigned to you, please ping me if you need more details

**Comment by dkropachev** [comment]
Fixed here - https://github.com/scylladb/scylla-manager/pull/3436
