### ISSUE TITLE
`--parallel` flag to ensure single repair job per host

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3425]
Current definition of `--parallel` flag is as follow https://manager.docs.scylladb.com/stable/sctool/repair.html#parallel

> The maximum number of Scylla repair jobs that can run at the same time (on different token ranges and replicas). Each node can take part in at most one repair at any given moment. By default the maximum possible parallelism is used. The effective parallelism depends on a keyspace replication factor (RF) and the number of nodes. The formula to calculate is is as follows: number of nodes / RF, ex. for 6 node cluster with RF=3 the maximum parallelism is 2.

We have to ensure that only a single repair job is executed on a host. Definition of the `--parallel` flag stays as-is.

~~We want to change it to~~
~~> The maximum number of Scylla repair jobs that can run at the same time on a single host.~~

~~Given a scenario where:~~
~~- there are 4 nodes A, B, C, D~~
~~- replication factor is set to 2~~
~~- woth ranges r1, r2, r3, r4, r5, r6~~
~~- ranges are distributed as follow~~
~~r1 are on nodes A, B~~
~~r2 -> A, C~~
~~r3 -> A. D~~
~~r4 -> B, C~~
~~r5 -> B, D~~
~~r6 -> C, D~~
~~.... with parallel set to 1 only following combinations are possible...~~
~~r1(A, B) together with r6(C, D)~~
~~r2(A, C) together with r5(B, D) etc~~

~~We must assure that max `--parallel` number of jobs are executed in parallel on a single host~~

**Default for `parallel`: 1**

**Comment by mykaul** [comment]
I would not change the meaning of an existing flag. I think it's better to introduce a new flag and deprecate this one.

**Comment by vladzcloudius** [comment]
@asias FYI.

I agree with @mykaul - the current definition of `--parallel` and `--intensity` are totally ok.

However it seems the implementation is currently broken.

Two questions:
1) Since what SM version.
2) Why we are not fixing it ASAP?

**Comment by vladzcloudius** [comment]
ref https://github.com/scylladb/scylla-manager/issues/3463

**Comment by karol-kokoszka** [comment]
Current definition of `--parallel` doesn't match the SM behavior.

It says:
> Each node can take part in at most one repair at any given moment.

#3463 shows that it's not true.

In new implementation of the repair we wan't to guarantee that max configured value number of jobs can be send to a single host.
Current definition of `--parallel` flag supposed to define max number of repair jobs executed in parallel across non-overlapping replica sets. This part of the definition doesn't match the behavior of the SM neither.

We want't to change `--parallel` meaning (or rather deprecate it and introduce new flag) to not define max parallelism across non-overlapping replica sets, but max parallelism for a single host.
By default, max parallelism for a single host = 1. Max parallelism for a single host impacts max parallelism across replica sets too.
With the max parallelism for a single host = 1, the parallelism across non-overlapping replica sets is our current default from the documentation.

>  The formula to calculate is is as follows: number of nodes / RF, ex. for 6 node cluster with RF=3 the maximum parallelism is 2.

6 nodes A, B, C, D, E, F
RF = 3

`--parallelism` set to 1 => 
job sent to replica set (A, B, C) and another job sent to (D, E, F)

Parallelism across replica sets is 2 then.

@asias should we give a possibility to limit max parallelism across non-overlapping replica sets ? Is it needed ?

**Comment by vladzcloudius** [comment]
> Current definition of `--parallel` doesn't match the SM behavior.
> 
> It says:
> 
> > Each node can take part in at most one repair at any given moment.
> 
> #3463 shows that it's not true.

Yes, because the implementation is broken.
So, we need to fix it - not invent a new semantics instead.

> 
> In new implementation of the repair we wan't to guarantee that max configured value number of jobs can be send to a single host. Current definition of `--parallel` flag supposed to define max number of repair jobs executed in parallel across non-overlapping replica sets. This part of the definition doesn't match the behavior of the SM neither.
> 
> We want't to change `--parallel` meaning (or rather deprecate it and introduce new flag) to not define max parallelism across non-overlapping replica sets, but max parallelism for a single host. By default, max parallelism for a single host = 1. Max parallelism for a single host impacts max parallelism across replica sets too. With the max parallelism for a single host = 1, the parallelism across non-overlapping replica sets is our current default from the documentation.
> 
> > The formula to calculate is is as follows: number of nodes / RF, ex. for 6 node cluster with RF=3 the maximum parallelism is 2.
> 
> 6 nodes A, B, C, D, E, F RF = 3
> 
> `--parallelism` set to 1 => job sent to replica set (A, B, C) and another job sent to (D, E, F)
> 
> Parallelism across replica sets is 2 then.
> 
> @asias should we give a possibility to limit max parallelism across non-overlapping replica sets ? Is it needed ?

I don't see any advantage in the proposed new semantics of `--parallel`.
On the contrary. 

This new semantics is actually dangerous and confusing because it doesn't guarantee that the actual repair concurrency is going to be as the value provided.

Running 2 repair jobs on every host in the cluster doesn't mean that the repair parallelism on every host is 2.

And this is unlike the current semantics which does guarantee that.

@mykaul please, let's make sure @karol-kokoszka reviews all his new designs with at least Asias and myself.

Please, keep in mind that existing SM repair related APIs are a result of multiple years of work of a lot of people. Let's not rush deprecating them before we at least sure that what we suggest is better than what we had.

**Comment by Michal-Leszczynski** [comment]
The idea is to leave the meaning of this flag as it is (although fix the implementation to match it) and introduce a new flag `single-host-parallelism` that will be responsible for defining the max number of repair jobs per host (with default value 1).

**Comment by vladzcloudius** [comment]
> The idea is to leave the meaning of this flag as it is (although fix the implementation to match it) and introduce a new flag `single-host-parallelism` that will be responsible for defining the max number of repair jobs per host (with default value 1).

@Michal-Leszczynski this doesn't answer my question above.
What added functionality this new parameter is going to provide in addition to `--parallel`? As far as I understand - it won't add any.
What am I missing?

**Comment by Michal-Leszczynski** [comment]
The general reason is to allow for repairing faster, but you can also see [comment1](https://github.com/scylladb/scylla-manager/issues/3424#issuecomment-1653057379), [comment2](https://github.com/scylladb/scylla-manager/issues/3424#issuecomment-1653246099) and generally the whole thread for more information.

**Comment by vladzcloudius** [comment]
> The general reason is to allow for repairing faster, but you can also see [comment1](https://github.com/scylladb/scylla-manager/issues/3424#issuecomment-1653057379), [comment2](https://github.com/scylladb/scylla-manager/issues/3424#issuecomment-1653246099) and generally the whole thread for more information.

@Michal-Leszczynski Please, read carefully mine and Asias'es explanation in the GH issue you have referenced above.
You should use `--intensity` flag to run repairs faster by increasing the number of repaired ranges in a given repair task - not `--parallel`.

**Comment by karol-kokoszka** [comment]
Issue description is updated.
We just want to ensure single repair job per host.
