### ISSUE TITLE
Restore documentation for `restore-schema` is missing info about need for `system_schema` in backup

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3444]
https://manager.docs.scylladb.com/stable/restore/restore-schema.html

The documentation describing how to restore the schema is missing crucial information that the backup must contain the `system_schema` keyspace inside. 
Otherwise, it won't be possible to bring back the schema.

**Comment by Michal-Leszczynski** [comment]
Isn't `system_schema` always backed up since SM 2.4?

**Comment by karol-kokoszka** [comment]
It is when you create backup task without defining what keyspaces to include.
If you choose to backup just selected list of keyspaces, then it's not.

**Comment by Michal-Leszczynski** [comment]
You can see in the implementation of backup's `GetTarget`:
```go
// Always backup system_schema.
//
// Some schema changes, like dropping columns, are applied lazily to
// sstables during compaction. Information about those schema changes is
// recorded in the system schema tables, but not in the output of "desc schema".
// Using output of "desc schema" is not enough to restore all schema changes.
// As a result, writes in sstables may be incorrectly interpreted.
// For example, writes of deleted columns which were later recreated may be
// resurrected.
systemSchemaUnit := Unit{
	Keyspace: systemSchema,
	// Tables are added later
	AllTables: true,
}
...
// Do not filter system_schema
if keyspace == systemSchema {
	systemSchemaUnit.Tables = tables
} else {
	f.Add(keyspace, tables)
}
...
// Get the filtered units
v, err := f.Apply(false)
if err != nil {
	return t, err
}

// Copy units and add system_schema by the end.
for _, u := range v {
	t.Units = append(t.Units, Unit{
		Keyspace:  u.Keyspace,
		Tables:    u.Tables,
		AllTables: u.AllTables,
	})
}
t.Units = append(t.Units, systemSchemaUnit)
```
that system schema unit is not going through the keyspace filtration as it's always included. Local experiments also support this claim, as I can see backed-up `system_schema` even when specifying some other keyspaces with the `-K` flag.

**Comment by karol-kokoszka** [comment]
Double checked and you are correct...
I too much relied on the integration-tests that bypasses the `GetTarget` method.

Closing as not relevant.
