### ISSUE TITLE
s-m can lose connection to a cluster if major topology change occurred between jobs

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-manager#3454]
There is logic that forces cql client to target hosts from closest dc: https://github.com/scylladb/scylla-manager/blob/0c742f50dd607877e1b047fe63eb3c3c7da72286/pkg/service/cluster/service.go#L139-L152

As result if that dc is getting killed, `s-m` loose ability to connect to the cluster.
And fails with following reason:
```
sctool --api-url http://127.0.46.1:5080/api/v1 restore -c c9c97847-f9be-458d-a941-11a4a25d8430 --restore-tables --location s3:backup-bucket --snapshot-tag sm_20230707141949UTC
Error: create restore target: list all views of cluster c9c97847-f9be-458d-a941-11a4a25d8430: get CQL cluster session: get client: discover cluster topology: giving up after 3 attempts: dial tcp 127.0.60.3:10001: connect: connection refused Trace ID: mvCHY2ovQsaGpckVPl2zpQ (grep in scylla-manager logs)
```
There is test in dc that proof the case `test_restore_different_dc`

**Comment by dkropachev** [comment]
Source of the problem is that `s-m` don't track cluster topology changes, unless it is doing something on the cluster, as result, if user deletes all nodes known by `s-m` and add new ones, in between operations `s-m` will not be able to connect to the cluster despite that cluster operational.

Solution could be to actively track cluster topology by periodically running flow we currently run when clients are created:
```
	hosts, err := s.discoverHosts(ctx, client)
	if err != nil {
		return nil, errors.Wrap(err, "discover cluster topology")
	}
	if err := s.setKnownHosts(c, hosts); err != nil {
		return nil, errors.Wrap(err, "update cluster")
        }
```

**Comment by karol-kokoszka** [comment]
> Solution could be to actively track cluster topology by periodically running flow we currently run when clients are created:

	hosts, err := s.discoverHosts(ctx, client)
	if err != nil {
		return nil, errors.Wrap(err, "discover cluster topology")
	}
	if err := s.setKnownHosts(c, hosts); err != nil {
		return nil, errors.Wrap(err, "update cluster")
        }

Unfortunately this is not a solution. `hosts` here is just a list of IPs. Would work fine for add-node or remove-node, but it won't work for node replacement.
There is a possibility to save `host-id` instead of IPs, but still, it won't catch node-replacement as the host-id may stay the same.

ScyllaDB emits TOPOLOGY_CHANGE (NEW_NODE, REMOVED_NODE, MOVED_NODE) events.
If there is a way to subscribe to these events somehow with some guarantees that they are always delivered (or buffered somehow if they cannot be consumed), we could use them.

**Comment by karol-kokoszka** [comment]
It would be good to detect cluster topology change, but I don't see how we can do it to cover all cases:
- node_add
- node_delete
- repleace_node

**Comment by dkropachev** [comment]
> It would be good to detect cluster topology change, but I don't see how we can do it to cover all cases:
> 
> * node_add
> * node_delete
> * repleace_node

Let's move it to another issue

**Comment by dkropachev** [comment]
There is nothing to do with this issue, i am closing it, topology tracking issue is [here](https://github.com/scylladb/scylla-manager/issues/3477).
