### ISSUE TITLE
Prometheus metric cardinality issue

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-manager#3458]
We are using snapshot id as a label for some prometheus metrics:
```
// SetRemainingBytes sets restore "remaining_bytes" metric.
func (rm RestoreM) SetRemainingBytes(labels RestoreBytesLabels, remainingBytes int64) {
	l := prometheus.Labels{
		"cluster":      labels.ClusterID,
		"snapshot_tag": labels.SnapshotTag,
		"location":     labels.Location,
		"dc":           labels.DC,
		"node":         labels.Node,
		"keyspace":     labels.Keyspace,
		"table":        labels.Table,
	}
	rm.remainingBytes.With(l).Set(float64(remainingBytes))
}

```

```
// DecreaseRemainingBytes decreases restore "remaining_bytes" metric.
func (rm RestoreM) DecreaseRemainingBytes(labels RestoreBytesLabels, restoredBytes int64) {
	l := prometheus.Labels{
		"cluster":      labels.ClusterID,
		"snapshot_tag": labels.SnapshotTag,
		"location":     labels.Location,
		"dc":           labels.DC,
		"node":         labels.Node,
		"keyspace":     labels.Keyspace,
		"table":        labels.Table,
	}
	rm.remainingBytes.With(l).Sub(float64(restoredBytes))
}
```

Which is destine to blow [metric cardinality](https://grafana.com/blog/2022/02/15/what-are-cardinality-spikes-and-why-do-they-matter/) indefinitely since `shapshot_tag` is unique for every given backup.

My understanding that this should address this issue by removing `snapshot_tag` from the metrics, given the fact that in all ocasions it is enough information in rest labels to figure which repair/backup metric related to.

**Comment by dkropachev** [comment]
@amnonh , is it something that we see in production, is there a occasions when prometheus metrics from `scylla-manager` went off hand?

**Comment by dkropachev** [comment]
@Michal-Leszczynski, could you please share your thoughts on it

**Comment by Michal-Leszczynski** [comment]
I don't know how exactly are those metrics utilized by users/monitoring/cloud, but I would say that there is no need to include snapshot tag as a label here.
