### ISSUE TITLE
Test many Scylla versions

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3471]
Right now our gh actions run test only on the Scylla with version hardcoded in `testing/.env`. 
Perhaps we should use [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to run tests on more versions (at least the oldest and newest supported versions).

Because of restore task, SM relies on the internals of Scylla more than before, so it would be nice to monitor, whether some Scylla assumptions used while writing SM code haven't changed in the meantime.

**Comment by karol-kokoszka** [comment]
I agree, we should test all supported scylla versions.
GH actions for public repos is free of charge, we can do exactly the same as with docker-compose for ipv6.
