### ISSUE TITLE
Test env setup takes a lot of time

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3472]
After ipv6 changes introduced in [commit](1819fae5), `make start-dev-env` takes a significant time to set up testing environment. When I want run some tests on different Scylla versions, it is more time efficient for me to just:
- `git checkout 59a303e8` (one commit before described changes has been made)
- `make start-dev-env`
- `git checkout <working-branch>`

Why is this set-up taking such a long time in comparison to the previous one? If ipv6 env cannot be set-up faster, then could we heave an option in makefile to set up a simple ipv4 env faster, like it was done before?

@dkropachev @karol-kokoszka

**Comment by karol-kokoszka** [comment]
It has nothing common with ipv6 actually. Makefile just chooses explicitly which nodes to start and is doing it in chain. 
https://github.com/scylladb/scylla-manager/blame/fd8417dafa0f9a6194c84dca556c7bdcf37b3c64/testing/Makefile#L72-L86

I think we can rollback to previous apporach.

**Comment by dkropachev** [comment]
There is official prodecidure on cluster bootstraping https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster-multidc.html
That says:
`Starting Scylla nodes, starting with the seed node, wait until it is in UN state, and repeat for the other nodes.`

The reason why it is so, is that scylla does not handle some edge cases that pops up in parallel bootstraping well.
As result you node boostraping endup in failure and cannot be proceeded.

In my personal experience I had 30% chance that cluster bootstrap fails before https://github.com/scylladb/scylla-manager/pull/3436, now i have not seen it at all.

Given the fact that this is also part of pipeline I would not recomend falling back to old bootstraping proceedure.
