### ISSUE TITLE
Repair: possible bug in small table range merging

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3478]
As described  in #3128, Scylla Manager detects small, fully replicated tables and merges their token ranges, so that they can be repaired in one call. 

From my local experiments, it looks like in some cases (failed case reproduces every time) it can break repair (checked on Scylla 5.1.0, 5.1.13, 5.2.0, 5.2.4). These are logs from a node on which repair has failed.

```
INFO  2023-07-14 08:29:59,660 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: starting user-requested repair for keyspace restoretest_tables_view_cql_schema, repair id 1, options {{ hosts -> 192.168.200.13,192.168.200.21,192.168.200.12,192.168.200.11,192.168.200.22,192.168.200.23}, { columnFamilies -> big_table}, { ranges -> -9223372036854775808:9223372036854775807}}
INFO  2023-07-14 08:29:59,660 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: Skipped sending repair_flush_hints_batchlog to nodes=[192.168.200.23, 192.168.200.22, 192.168.200.11, 192.168.200.12, 192.168.200.21, 192.168.200.13]
INFO  2023-07-14 08:29:59,660 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: Started to repair 1 out of 1 tables in keyspace=restoretest_tables_view_cql_schema, table=big_table, table_id=79ec9630-2220-11ee-8e44-0009ae6052fe, repair_reason=repair
INFO  2023-07-14 08:29:59,660 [shard 1] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: Started to repair 1 out of 1 tables in keyspace=restoretest_tables_view_cql_schema, table=big_table, table_id=79ec9630-2220-11ee-8e44-0009ae6052fe, repair_reason=repair
{"L":"INFO","T":"2023-07-14T08:29:59.660Z","N":"http","M":"POST /storage_service/repair_async/restoretest_tables_view_cql_schema?columnFamilies=big_table&hosts=192.168.200.13%2C192.168.200.21%2C192.168.200.12%2C192.168.200.11%2C192.168.200.22%2C192.168.200.23&ranges=-9223372036854775808%3A9223372036854775807","from":"192.168.200.1:47468","status":200,"bytes":1,"duration":"0ms"}
WARN  2023-07-14 08:29:59,901 [shard 1] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: shard=1, keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807], got error in row level repair: std::bad_alloc (std::bad_alloc)
WARN  2023-07-14 08:29:59,920 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: shard=0, keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807], got error in row level repair: std::bad_alloc (std::bad_alloc)
INFO  2023-07-14 08:29:59,945 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: Started to shutdown off-strategy compaction updater
INFO  2023-07-14 08:29:59,945 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: Finished to shutdown off-strategy compaction updater
WARN  2023-07-14 08:29:59,946 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: repair_tracker run failed: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807]), shard 1: std::runtime_error (Failed to repair for keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807])})
```

So I have two questions:
- @asias is this optimization important from Scylla side? Should it really improve performance (I expect that it shouldn't be significant improvement, as the amount of repaired ranges per request is more about granularity, not performance)?
- @DoronArazii why was this optimization requested?

Perhaps the problem lies in the fact, that SM is sending wrong min/max token to repair. We have them defined as:
- min token: -9223372036854775808 (-1 << 63)
- max token: 9223372036854775807 ( 1 << 63 - 1)

cc @karol-kokoszka

**Comment by asias** [comment]
Could you please share the schema of the table and full scylla logs?

**Comment by Michal-Leszczynski** [comment]
> It failed due to bad allocation. Give more memory per shard and try again.

You are right, it solved the issue:) Thanks!

What was strange to me is that (with the same config) I didn't experience this issue in Scylla 5.0.3, so I thought that perhaps something changed on the Scylla side after this optimization had happened in SM.

Nevertheless, this means that it would be nice for SM (as a part of #3423) to have a fallback for this situation, so that even when it encounters a small, fully replicated table, it won't try to merge all ranges into one request when Scylla is low on memory.

Here are schema and logs (although I don't think that they are needed anymore):
[scylla.LOG](https://github.com/scylladb/scylla-manager/files/12067393/scylla.LOG)
```
CREATE KEYSPACE restoretest_tables_view_cql_schema WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': '3', 'dc2': '3'}  AND durable_writes = true;

CREATE TABLE restoretest_tables_view_cql_schema.big_table (
    id int PRIMARY KEY,
    data blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by mykaul** [comment]
> What was strange to me is that (with the same config) I didn't experience this issue in Scylla 5.0.3, so I thought that perhaps something changed on the Scylla side after this optimization had happened in SM.
> 
> Nevertheless, this means that it would be nice for SM (as a part of #3423) to have a fallback for this situation, so that even when it encounters a small, fully replicated table, it won't try to merge all ranges into one request when Scylla is low on memory.

Let's not spend time on non realistic scenarios - how much memory was given per shard? At least 1GB should be given.

**Comment by karol-kokoszka** [comment]
> WARN  2023-07-14 08:29:59,901 [shard 1] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: shard=1, keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807], got error in row level repair: std::bad_alloc (std::bad_alloc)
WARN  2023-07-14 08:29:59,920 [shard 0] repair - repair[7b9296dc-b354-4b0b-95c9-f83c5249eb2b]: shard=0, keyspace=restoretest_tables_view_cql_schema, cf=big_table, range=(minimum token, 9223372036854775807], got error in row level repair: std::bad_alloc (std::bad_alloc)

Does `std:bad_alloc` always mean there is not enough memory ?
If so, SM may be bit more user friendly and inform the end user about potential root-cause.

**Comment by Michal-Leszczynski** [comment]
> Let's not spend time on non realistic scenarios - how much memory was given per shard? At least 1GB should be given.

SM testing env runs Scylla with: `--smp 2 --memory 1G`, so it should be changed.

**Comment by Michal-Leszczynski** [comment]
>  If so, SM may be bit more user friendly and inform the end user about potential root-cause.

Unfortunately, SM would have to go to Scylla logs in order to discover that, as the error returned by Scylla looks like: 
```Scylla error - check logs on host 192.168.200.21 for job 1```

**Comment by Michal-Leszczynski** [comment]
> Let's not spend time on non realistic scenarios - how much memory was given per shard? At least 1GB should be given.

@mykaul So the testing env requirement taken from [here](https://opensource.docs.scylladb.com/stable/getting-started/system-requirements.html#memory-requirements) should also be adjusted?

Minimum:
- For test environments: 1 GB or 256 MiB per lcore (whichever is higher)

**Comment by mykaul** [comment]
I've seen somewhere that we need to increase it - let's test first that the increase fixes the issue (I don't remember where it was also hit - driver tests? gemini? need to search...)
