### ISSUE TITLE
Alert Manager Rule: add a too-many-files alert

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3503]
Scylla and the Linux kernel don't cope with the fact of having too many files, hence nodes can get in an out-of-memory situation where the kernel out-of-memory killer daemon forcibly kills scylla or other processes in the system when it runs out of memory with no ability to evict fragmented pages occupied by inodes.

TL;DR; in order to prevent incidents where nodes start crashing due to a huge number of files, we should implement an alert of too-many-files.
e.g to retrieve the number of files we have the following formula on monitoring:
sum(node_filesystem_files{mountpoint="$mount_point", instance=~"$node"}- node_filesystem_files_free{mountpoint="$mount_point", instance=~"$node"}) by ([[by]]) 

This is @avikivity 's calculation to determine a reasonable threshold:

```
    50,000 * nr_vcpus (to start with)
    ICS generates 8 files per gigabyte. i3en has 500 GB/vcpu, so 4,000 files/vcpu. LCS is 6x higher, so 24,000 files/vcpu, but we rarely have such huge LCS tables. I think 50,000/vcpu is a good start, but we may want to adjust it later.
```

Let's add an "info" alert for 20K files/shard, "warn" for 30K, "error" for 40K and "critical" for 50K.

**Comment by karol-kokoszka** [comment]
This issue should be transferred to scylla-monitoring repo https://github.com/scylladb/scylla-monitoring
Scylla-manager doesn't raise or define alerts, we can just expose metrics that are used to define alert later on.
`node_filesystem_files` comes from the node_exporter and is available already.

I have no permissions to move it to scylla-monitoring repo, @mykaul could you please transfer it ?

**Comment by mykaul** [comment]
@vladzcloudius - isn't it a dup of https://github.com/scylladb/siren/issues/9366 ?

**Comment by karol-kokoszka** [comment]
> @vladzcloudius - isn't it a dup of https://github.com/scylladb/siren/issues/9366 ?

Alerts that are applied to scylla-cloud exists in cloud clusters only.
Siren overwrites alert rules from scylla-monitoring.

**Comment by vladzcloudius** [comment]
> @vladzcloudius - isn't it a dup of [scylladb/siren#9366](https://github.com/scylladb/siren/issues/9366) ?

I don't remember why I opened this GH issue in SM repo (by mistake?) but I agree with @karol-kokoszka that this issue should be in the `scylla-monitoring` repo.

Here it is: https://github.com/scylladb/scylla-monitoring/issues/2060

**Comment by vladzcloudius** [comment]
> > @vladzcloudius - isn't it a dup of [scylladb/siren#9366](https://github.com/scylladb/siren/issues/9366) ?
> 
> Alerts that are applied to scylla-cloud exists in cloud clusters only. Siren overwrites alert rules from scylla-monitoring.

This is a very bad practice (that they completely overwrite these rules) and I have already told this to @d-helios.

There is no reason whatsoever not to use our packaged rules as a base or not to contribute some "nice" generic rule if it's missing.

Closing this issue.
