### ISSUE TITLE
[Doc]: contradicting content in the repair page

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3505]
Page URL: https://manager.docs.scylladb.com/stable/sctool/repair.html

*Description*
The description of newly added `--single-host-parallelism` parameter (https://manager.docs.scylladb.com/stable/sctool/repair.html#single-host-parallelism) and the existing `--parallel` parameter (https://manager.docs.scylladb.com/stable/sctool/repair.html#id8) are contradicting.

The former suggests that there may be more than a single task running on a given host, while the later clearly states this is forbidden.

This is related to https://github.com/scylladb/scylla-manager/issues/3463

**Comment by vladzcloudius** [comment]
FYI @tzach @annastuchlik

**Comment by annastuchlik** [comment]
@karol-kokoszka It looks like the sentence "Each node can take part in at most one repair at any given moment." in the description or `--parallel` is incorrect. Please confirm, and I'll remove it.

**Comment by karol-kokoszka** [comment]
@annastuchlik This sentence `Each node can take part in at most one repair at any given moment.` is not correct. We are not ensuring it.

**Comment by vladzcloudius** [comment]
> @annastuchlik This sentence `Each node can take part in at most one repair at any given moment.` is not correct. We are not ensuring it.

@karol-kokoszka it's the bug in SM that we must fix - not document it: https://github.com/scylladb/scylla-manager/issues/3463

@annastuchlik the sentence in question is correct. The need to remove the `--single-host-parallelism` from our documentation ASAP.

There are still discussions about the design which mentions this parameter and this parameter is very much not liked by me and @asias.

Again, I suggest we remove this from our public documentation till further notice.

**Comment by vladzcloudius** [comment]
@annastuchlik and of course, please, revert the https://github.com/scylladb/scylla-manager/pull/3509.

**Comment by vladzcloudius** [comment]
cc @mykaul

**Comment by Michal-Leszczynski** [comment]
As the flag `--single-host-parallelism` isn't a part of SM 3.2 release, I think we can close this issue.
#3509 was effectively reverted by the #3526.
