### ISSUE TITLE
manager crashes when scylla sstable uuid identifier feature is enabled 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-manager#3512]
Scylla has this new feature (which is enabled by default) uuid_sstable_identifier_enabled
https://github.com/scylladb/scylladb/pull/13932

and now `sctool restore` is crashing scylla manager 
```
{"L":"INFO","T":"2023-07-30T13:38:38.552Z","N":"scheduler.b4c2d6bb","M":"Run ended","task":"restore/006f36fb-6079-4df3-8d4b-5962e713b0b8","status":"DONE","duration":"609.26413ms","_trace_id":"n_SVpivOSl-aqRzYEDeBDw"}
panic: unknown SSTable format version: me-3g83_11w8_5az0026ynbe3lqk0u3-big-CRC.db. Supported versions are: 'mc', 'md', 'me', 'la', 'ka'

goroutine 1040 [running]:
```

**Comment by fruch** [comment]
@tchaikov FYI

**Comment by karol-kokoszka** [comment]
@fruch can you let us know which version of Scylla Manager (commit hash if the one from master) did you use for testing ? 
This recent PR https://github.com/scylladb/scylla-manager/pull/3461 is supposed to fix it.

**Comment by fruch** [comment]
> @fruch can you let us know which version of Scylla Manager (commit hash if the one from master) did you use for testing ? This recent PR #3461 is supposed to fix it.

it was latest 3.1

**Comment by karol-kokoszka** [comment]
@fruch I see that `uuid_sstable_identifier_enabled` is going to be introduced in scylla 5.4. Scylla manager is using 5.2.4 as the latest version we are validating scylla-manager against in the CI checks.

https://github.com/scylladb/scylla-manager/actions/runs/5692478722

PR that I mentioned in previous comment is fixing the problem with new sstable uuid identifier even though we cannot validate it in the real env.
We are going to add 5.4 and enable the flag to the CI whenever it's released.
Is it fine ? Do you want to keep this issue opened for tracking or we can close it ?

**Comment by fruch** [comment]
> @fruch I see that `uuid_sstable_identifier_enabled` is going to be introduced in scylla 5.4. Scylla manager is using 5.2.4 as the latest version we are validating scylla-manager against in the CI checks.
> 
> https://github.com/scylladb/scylla-manager/actions/runs/5692478722
> 
> PR that I mentioned in previous comment is fixing the problem with new sstable uuid identifier even though we cannot validate it in the real env.
> We are going to add 5.4 and enable the flag to the CI whenever it's released.
> Is it fine ? Do you want to keep this issue opened for tracking or we can close it ?

The fix isn't going to be backported to 3.1 ?

**Comment by karol-kokoszka** [comment]
@fruch it's going to be backported ofc. Not sure if to 3.1 only yet.

**Comment by mykaul** [comment]
I'm not sure I see the reason to backport to 3.1. There's no ScyllaDB yet with this feature, to the best of my knowledge.

**Comment by karol-kokoszka** [comment]
Issue is not valid anymore.
SM supports scylla sstable uuid identifiers and is able to perform backup + restore.
Here is the PR that explicitly enables that option on all Scylla versions that we are using to test SM agaist.
https://github.com/scylladb/scylla-manager/pull/3883

Screenshot of the minio folder contain backup SSTables ->
![image](https://github.com/scylladb/scylla-manager/assets/50329145/3c637d4d-2512-4ce0-8516-1f55d45eaf31)

They keep the uuid.
