### ISSUE TITLE
Make sure it's possible to re-enable disabled task using task name instead of just the task ID

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla-manager#3513]
I previously used the command "sctool stop -c my-cluster-name --disable repair/all-weekly" to temporarily disable repairs while doing some work on my cluster, and now I want to enable it, but can't find anything in the docs on how to do this.

The "sctool start" command doesn't seem to have an option for this. "sctool tasks resume" also doesn't seem to do the trick.

I tried to modify an example like this "sctool repair update -c my-cluster-name repair/all-weekly --enabled=true", but that returned "Error: no tasks of type repair". But if I do "sctool tasks -a", I do see the repair/all-weekly task in the list with an asterisk in front of it.

Let me know the trick, thanks.

**Comment by Michal-Leszczynski** [comment]
Hi, this looks like a bug in the implementation,  but there is a workaround for this. Command:
```
sctool repair update -c my-cluster-name repair/all-weekly --enabled=true
```
should work fine if you replace task name with task ID (e.g. `repair/f57acf20-84fd-4cb7-90ad-e6e0056c99e2`). You can query it by:
```
sctool tasks -c my-cluster-name -a --show-ids
```

**Comment by A-Posthuman** [comment]
Cool that worked, thanks for the tip!

**Comment by karol-kokoszka** [comment]
Let's fix it the way that the task ID is not required and it's possible to re-enable the task by simply using the task name.
Added 3.2 milestone as it seems to be easy to fix.
