### ISSUE TITLE
Centos-Sanity and Ubuntu-Sanity fail when `system_traces` is excluded from the repair

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3523]
https://jenkins.scylladb.com/job/manager-master/job/centos-sanity-test/1000/

The jenkins job above failed on asserting if the system_traces keyspace is repaired.
`system_traces` is excluded from the repair procedure with the following issue https://github.com/scylladb/scylla-manager/issues/3522

The Centos-Sanity job was triggered on the `ml/repair_refactor` branch,

```
19:58:16  ----- LAST ERROR EVENT -------------------------------------------------------
19:58:16  2023-08-12 17:58:04.315: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=cbcc3a4e-8520-4ae4-b74e-239537d4fa5f, source=MgmtCliTest.test_manager_sanity (mgmt_cli_test.MgmtCliTest) [Repair Multiple Keyspace Types]() message=Traceback (most recent call last):
19:58:16  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 349, in test_manager_sanity
19:58:16  self.test_repair_multiple_keyspace_types()
19:58:16  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 856, in test_repair_multiple_keyspace_types
19:58:16  assert keyspace_repair_percentage is not None, \
19:58:16  AssertionError: The keyspace system_traces was not included in the repair!
```

**Comment by karol-kokoszka** [comment]
The same apply to the Ubuntu-Sanity ofc.
https://jenkins.scylladb.com/job/manager-master/job/ubuntu22-sanity-test/294/

**Comment by ShlomiBalalis** [comment]
> This looks like a test issue to me - @ShlomiBalalis ?

Yes, and we already fixed that: https://github.com/scylladb/scylla-cluster-tests/pull/6506

**Comment by karol-kokoszka** [comment]
Fixed with https://github.com/scylladb/scylla-cluster-tests/pull/6506
