### ISSUE TITLE
docs: Issue in page Restore

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-manager#3533]
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.1/sctool/restore

### Problem

https://manager.docs.scylladb.com/stable/sctool/restore.html#restore-schema
should explain that restoring system* tables (besides system_auth) IS a BIG problem if versions are NOT compatible
e.g. restoring 2022.2 system tables to 5.2 is a disaster
even 2023 (despite it being built on top of 5.2) restored to 5.2 WILL be a problem (since OSS lacks EE features)

###  Suggest a fix

we should explicitely and in bold warn people to use this options ONLY with compatible versions (so same flavour, EE, OSS, and only lower to higher or same to same version, anything else will break the node(s) )

**Comment by tarzanek** [comment]
simply said
--restore-schema
can only be used between compatible Scylla versions

@karol-kokoszka should I file a bug in SM to disallow incompatible usages of this option?
(IHAC that actually got bitten by this, he was using it from EE to OSS)

**Comment by Michal-Leszczynski** [comment]
> @karol-kokoszka should I file a bug in SM to disallow incompatible usages of this option?

Right now SM does not store information about Scylla version in backup manifest files, so this would require some changes in this regard. This would mean that this validation is only possible for newer backups, but it can be done.

> simply said
--restore-schema
can only be used between compatible Scylla versions

But this is probably also accurate for `--restore-tables`, as it can also restore system tables (e.g. `system_distributed`).
Or is it just `system_schema` that suffers in this scenario?

**Comment by tarzanek** [comment]
@Michal-Leszczynski basically all system* keyspaces (and I fear even system_auth can be a victim, if you have new sstables with new columns and you try to push to old scylla version)

the only thing safe would be user sstables, if moving to newer version that has support for the format and while keeping schema
