### ISSUE TITLE
Run post-restore repair with max intensity

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3542]
I think that SM should run post-restore repair with max intensity.
There are two reasons for that:
- restore procedure is usually the only thing putting pressure on the cluster
- recent changes to repair (SM 3.2) made it run slower (although with greater stability)

Right now SM runs the repair task with default intensity (1) and this change should speed-up the process.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski do you want to fix this one ? We want to include it into 3.2.8.

**Comment by karol-kokoszka** [comment]
**grooming notes**
`repair control` must be extended the way that it's possible to change instensity/pallel parameters on post-restore repair (or just validated if it's already working this way).
It's nice to give a possibility of changing these parameter when the restore task is running and the repair is not started yet.

It must be verified if the repair control is already working correctly on post-restore repair. (cc: @Michal-Leszczynski )
