### ISSUE TITLE
[Repair]: total task progress value is misleading

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3547]
Version: 3.2

*Description*
The repair task progress is apparently calculated based on the total number of token ranges that have been processed so far.
However this doesn't take into the account the actual amount of data that has been repaired so far out of the total.

And this became particularly confusing with 3.2 which repairs small tables first.
As a result the task's progress increases very rapidly at the start and then "gets stuck" when the task gets to repairing a large table at a very large progress value (e.g. 90% in the example below).

See the output of the `sctool progress` and the corresponding "repair progress" graph: 

```
Run:            5155826b-46a2-11ee-8dff-4201ac1300bb
Status:         RUNNING
Start time:     29 Aug 23 19:29:05 UTC
Duration:       4h28m40s
Progress:       90%
Intensity:      1
Parallel:       0
Datacenters:
  - asia-southeast1

╭───────────────────────────────┬────────────────────────────────┬──────────┬──────────╮
│ Keyspace                      │                          Table │ Progress │ Duration │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ audit                         │                      audit_log │ 100%     │ 1m52s    │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ largest_ks                    │               largest_table    │ 0%       │ 0s       │
│ largest_ks                    │            largest_table_mv    │ 33%      │ 4h22m4s  │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_auth                   │                role_attributes │ 100%     │ 29s      │
│ system_auth                   │                   role_members │ 100%     │ 30s      │
│ system_auth                   │               role_permissions │ 100%     │ 28s      │
│ system_auth                   │                          roles │ 100%     │ 30s      │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_distributed_everywhere │ cdc_generation_descriptions_v2 │ 100%     │ 0s       │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_distributed            │    cdc_generation_descriptions │ 100%     │ 42s      │
│ system_distributed            │      cdc_generation_timestamps │ 100%     │ 28s      │
│ system_distributed            │    cdc_streams_descriptions_v2 │ 100%     │ 31s      │
│ system_distributed            │                 service_levels │ 100%     │ 28s      │
│ system_distributed            │              view_build_status │ 100%     │ 29s      │
╰───────────────────────────────┴────────────────────────────────┴──────────┴──────────╯
```

![image](https://github.com/scylladb/scylla-manager/assets/6103981/5dd20dfc-e97c-4e4e-8ffe-c50617e7e1c8)

*Proposal*
Use a table size on disk as a "weight" factor when accounting a total repair task progress.

**Comment by Michal-Leszczynski** [comment]
Since the repair progress metric is only an aggregation of SM repair metrics (`token_ranges_total`, `token_ranges_success`), there are two options:
- introduce new `progress` metric that would replace aggregation
- change aggregation on monitoring side so that it takes Scylla table size metrics into consideration (not sure if it's easy or even possible)
- introduce new `table_size` metric that would allow monitoring for simpler progress aggregation

I'm in favor of the first solution, so that's it's easier to control this metric from SM dev side. Second solution could be problematic for monitoring team and would also put some unnecessary dependency between repos. Third solution adds redundant metrics (table size on both Scylla and SM metrics), so that's also not ideal and still requires changes from monitoring team.

FYI @karol-kokoszka

**Comment by Michal-Leszczynski** [comment]
The `repair_progress` metric would be labeled only by `clusterID`, as that's the only repair progress aggregation done on [monitoring side](https://github.com/scylladb/scylla-monitoring/blob/f8217886951a139399e3ea5784cb1ec67595fc89/prometheus/prom_rules/back_fill/3.8/rules.1.yml#L24-L25C25). We can't provide per keyspace/table/host metric as it wouldn't be possible to correctly aggregate it into total repair progress without knowing repaired tables size.
