### ISSUE TITLE
SM 3.2 - Cron scheduler in SM runs tasks outside scheduled pattern

### ISSUE THREAD

**Issue by ppalczak** [scylladb/scylla-manager#3549]
## Issue
SM runs backup outside of schedule.

Current tasks schedule.
**backup/9f63621c-97af-4036-8909-c9f4e63c33bd** is scheduled for all days at 8 UTC except for Mondays
![image](https://github.com/scylladb/scylla-manager/assets/134054072/6521dc40-b468-4491-9165-e537ef7281ce)

However it was run on Monday at 8 UTC:
```
+--------------------------------------+------------------------+----------+---------+
| ID                                   | Start time             | Duration | Status  |
+--------------------------------------+------------------------+----------+---------+
| 37b6c499-470b-11ee-a460-4201ac1e0012 | 30 Aug 23 08:00:00 UTC | 13m31s   | RUNNING |
| 0d4d2285-4642-11ee-a45f-4201ac1e0012 | 29 Aug 23 08:00:00 UTC | 2h30m28s | DONE    |
| e2e34c9f-4578-11ee-a45d-4201ac1e0012 | 28 Aug 23 08:00:00 UTC | 2h9m47s  | DONE    |
```
Aug 28 08:00:00 scylla-cloud-xxxx-manager-17-7371f31f82cce897222e scylla-manager[473324]: {"L":"INFO","T":"2023-08-28T08:00:00.000Z","N":"scheduler.3bc9011a","M":"Run started","task":"backup/9f63621c-97af-4036-8909-c9f4e63c33bd","retry":0,"_trace_id":"X-3-5YinRHOGfZS7Es8igg"}
scheduler.3bc9011a","M":"Run started","task":"backup/9f63621c-97af-4036-8909-c9f4e63c33bd","retry":0,"_trace_id":"X-3-5YinRHOGfZS7Es8igg"}

**Comment by doctorg-ml** [comment]
Ticket [3549](https://github.com/scylladb/scylla-manager/issues/3549) has been created for this issue.

**Comment by doctorg-ml** [comment]
We've made changes: the backup under the ID 273fbe8d-3513-44c5-aa92-5109c5768756 (previously set for Mondays at 15:00 hours) has been removed. Instead, we've implemented a daily backup schedule. This schedule will operate each day from Tuesday to Saturday at 8:00 AM UTC, and also on Mondays at 15:00 hours. 

![image](https://github.com/scylladb/scylla-manager/assets/73360941/faca1110-e6f3-453b-a89c-6d398c39e9a5)

**Comment by ppalczak** [comment]
@karol-kokoszka could you please advice if any further information from support is required?

**Comment by Michal-Leszczynski** [comment]
@ppalczak sorry for such a late response.
Has this issue been observed more than 1 time?
Was this task schedule changed recently before/after this issue occurred?

It would be nice to see output of the following queries on SM DB:
```
select * from scylla_manager.scheduler_task_run;
select * from scylla_manager.scheduler_task;
```
And also SM logs from around when this issue occurred (e.g. from 2 days before to 2 days after).

**Comment by Michal-Leszczynski** [comment]
Hi @ppalczak, is it still possible to get some of those information?

**Comment by ppalczak** [comment]
@Michal-Leszczynski I'm collecting the data. Will get back to you soon

**Comment by ppalczak** [comment]
I'm moving the issue to another repository
