### ISSUE TITLE
Fix test_repairing_a_downed_node and test_ignore_down_hosts_with_one_down_host DTests

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3565]
Two additional tests are failing on branch-3.2.
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.2/job/manager-dtest/4/testReport/

It happens due to the validation of the task that is moved to the task creation layer.

Tests must be changed to assert the error directly on task creation instead of task execution.

Tests failures are introduced with the following commit https://github.com/scylladb/scylla-manager/commit/3f6127aa4a1264e6cfed4616148bee83be7a95d1

**Comment by Michal-Leszczynski** [comment]
Corresponding [issue](https://github.com/scylladb/scylla-dtest/issues/3561) on dtest repo.
