### ISSUE TITLE
Give better explanation on host down error during task creation

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3568]
With the latest changes, scylla-manager just throws basic "connection refused" error to the output whenever host is down on task creation.

The message should be more self-explanatory.
We need to replace it with 
```
Node XXXX is down. Task cannot be created.
Please use --ignore-host-down flag (https://manager.docs.scylladb.com/stable/sctool/repair.html#ignore-down-hosts) if you want to skip the repair on this node.
```

**Comment by Michal-Leszczynski** [comment]
I'm just wondering about safety of using `--ignore-host-down` flag ion general. If we skip repair of down node and then it comes back to cluster it could cause data resurrection, right? So is suggesting to use this flag a good approach?

**Comment by karol-kokoszka** [comment]
We are not the administrators of the customers database.
We are just delivering the tool they can use to achieve what they want.

I don't think there is a hidden suggestion in the sentence. It just lists one of the options customer can use to proceed with the repair of UN nodes.
