### ISSUE TITLE
docs: Issue in page Progress

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylla-manager#3578]
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.2/sctool/progress

### Problem
How to generate progress is documented but interpreting the output is not.

###  Suggest a fix
Please add example output.  Include explanation success/fail nuance of progress field (which is described in prior release notes, but ideally would be in this section also).  (Thanks @noellymedina )
https://www.scylladb.com/product/release-notes/scylla-manager-release-1-4/

**Comment by Michal-Leszczynski** [comment]
I think that the output of `sctool progress` ideally should be self explanatory, so I would suggest to improve success/failure display readability rather than giving some example on how to interpret that (and this applies for other tasks as well).

Are there any other parts of `sctool progress` that you find ambiguous?

**Comment by pdbossman** [comment]
@Michal-Leszczynski that sounds wonderful.
I saw some tables with just 100% and others with 100%/0% and then in-progress tables with say 90%/0%.
It was confusing why some had two columns and others didn't.

Knowing parallelism when it is computed would be good, I mentioned this in another ticket.
It's not clear when changes to parameters take effect.  Eg. If I run a repair control to slow down repair, would that apply next table a repair works on, next set of token ranges?  Basically, what I'd be trying to decide is - should I cancel the repair and start over (if reduction in parallelism takes too long to take effect), or will progress tell me my parallelism reduction has fully taken effect.
