### ISSUE TITLE
Repair: small table optimization is used on big tables

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3591]
SM should repair small, fully replicated tables in 1 Scylla repair job, but it happens that bigger tables are also optimized.

Examples:
- SM [issue](https://github.com/scylladb/scylla-manager/issues/3584#issuecomment-1732627868)
- Scylla [issue](https://github.com/scylladb/scylla-enterprise/issues/3400#issuecomment-1720870937)

Cause:
This fragment of `FillSize` method:
```go
	for i, kp := range p.Keyspaces {
		p.Keyspaces[i].Size = ksSize[kp.Keyspace]
		for j, tp := range kp.Tables {
			kp.Tables[j].Size = tableSize[kp.Keyspace+"."+tp.Table]
			// Return merged ranges for small, fully replicated table (#3128)
			if tp.Size <= smallTableThreshold && len(kp.Replicas) == 1 {
				kp.Tables[j].Optimize = true
			}
		}
	}
```
where we set `kp.Tables[j].Size` but then we check `tp.Size` which hasn't been updated.
This basically means that all fully replicated tables (no matter their size) are always optimized (repaired in 1 Scylla repair job) since SM 3.2.

Also, we need to add tests checking that bigger tables are not optimized even when they are fully replicated.

**Comment by Michal-Leszczynski** [comment]
This is 100% SM bug, but is Scylla behavior described in those issues expected (huge latency spikes / not responding node)?

**Comment by Michal-Leszczynski** [comment]
FYI @tzach @mykaul @karol-kokoszka

**Comment by tzach** [comment]
Thanks @Michal-Leszczynski think should be part of the 3.2.2
@ShlomiBalalis we should add tests to capture this type of errors (not just this one)

**Comment by mykaul** [comment]
When was this regression introduced? I wonder how urgently we need to get 3.2.2 out with this fix.

**Comment by karol-kokoszka** [comment]
Looks that it was introduced in 3.2.

**Comment by mykaul** [comment]
> Looks that it was introduced in 3.2.

OK - then as soon as this is done, let's see if we can get 3.2.2 out of the door. It's a critical regression.
