### ISSUE TITLE
Tablets support

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3636]
This is a tracker / meta-issue to ensure Manager is compatible with Tablets (OSS 6.0 / following Enterprise release)

**Comment by tzach** [comment]
In particualr, tablet repair API will not include range by range repair.
@tgrabiec @asias do we have the API for tabelt repair?

https://github.com/scylladb/scylladb/issues/16101

**Comment by bhalevy** [comment]
@mykaul do we need to keep both this issue and #3516?
Maybe close this one as duplicate

**Comment by avikivity** [comment]
Closing as duplicate of https://github.com/scylladb/scylla-manager/issues/3516#issuecomment-1867816102
