### ISSUE TITLE
Github actions failing because cluster setup hangs 

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3654]
Recently some github actions runs are failing because they reach the 6h timeout on cluster creation step. Example:
```
2023-12-05T23:00:23.7152983Z ==> Waiting for first nodes from DC1 and DC2 to spin up
2023-12-06T04:59:54.8577560Z ##[error]The operation was canceled.
```
It would be nice to know if the root cause is connected to:
- Scylla regression (from what I have seen, this only happens with Scylla 5.2.X)
- SM cluster setup script
- github actions runners

**Comment by mykaul** [comment]
> * Scylla regression (from what I have seen, this only happens with Scylla 5.2.X)

5.2 is so yesterday. How's 5.4 doing?

**Comment by Michal-Leszczynski** [comment]
> 5.2 is so yesterday. How's 5.4 doing?

I will include it in our test matrix and see the results.
