### ISSUE TITLE
Unable to configure Scylladb-manager and agent [using containers]

### ISSUE THREAD

**Issue by ketul93** [scylladb/scylla-manager#3672]
We are trying to configure the pilot scylladb manager ... These are the configuration we are trying to get it
Scylladb with scylladb - agent - IP1
Scylladb manager - IP2
Using the Dockerized env as mentioned here - https://manager.docs.scylladb.com/stable/docker/index.html
When I am trying to add the cluster of IP1 using sctool at Scylla-manager [bash] running in IP2 ... Getting the following error as shared in the screenshot ....
I have already whitelisted and exposed these ports at agent side ...
```
     - "9042:9042"  # CQL native transport port
      - "19042:19042"  # Internode communication (non-SSL)
      - "7199:7199"  # JMX management port
      - "9180:9180"  # Prometheus metrics port
      - "10001:10001" # Scylla Manager agent port
      - "9100:9100"
```
Also generated and added TLS cert.
Also tried connecting the agent with GET req and seems it is able to respond but yet failed to be added as cluster

![image](https://github.com/scylladb/scylla-manager/assets/10497402/f05b3d25-2c32-4af4-a1fe-a562b3b3d3c5)
![image](https://github.com/scylladb/scylla-manager/assets/10497402/4d5553f8-ee4c-4a4a-996d-ecd2c0f17693)

Let me know if you need any further info for this ... 

Thanks.

**Comment by ketul93** [comment]
Hi guys, any leads on the same ? 

Thanks.

**Comment by Michal-Leszczynski** [comment]
Hi and sorry for such a late response!

Perhaps there is some problem regarding Scylla setup (e.g. connected to `rpc-address` and `listen-address`).
It would be nice to see used dockerfiles and compose files, Scylla, Manager and Agent, their .yaml configs and commands used for deploying this setup.

**Comment by DarshakDev** [comment]
Hi, I have attached the compose file which we are using for deployment (It is working if we deploy both on same VM). but if we just deploy agents to other VM and manager to another VM then i could not add agent cluster to manager. .yaml configurations we kept as it is , no change in defaults.
[scylla_manager_agent.txt](https://github.com/scylladb/scylla-manager/files/13973931/scylla_manager_agent.txt)
[Dockerfile.txt](https://github.com/scylladb/scylla-manager/files/13973932/Dockerfile.txt)
