### ISSUE TITLE
Unable to add CA to trust or disable validation

### ISSUE THREAD

**Issue by bipul-baishya** [scylladb/scylla-manager#3683]
Internal error occurred: failed calling webhook "webhook.scylla.scylladb.com": Post "[https://scylla-operator-webhook.scylla-operator.svc:443/validate?timeout=10s](https://scylla-operator-webhook.scylla-operator.svc/validate?timeout=10s)": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "My Ceritificate Authority")

We have our on CA which is used by Cert Manager to sign the certificate. I was looking for a away to add the CA to scylla-manager's trust. Is there a way to do so?

Also, is there a way to disable the validation?

**Comment by Michal-Leszczynski** [comment]
Hi!

Have you tried using the following options in `scylla-manager.yaml` config?
```yaml
# Optional custom client/server encryption options.
#ssl:
# CA certificate used to validate server cert. If not set will use he host's root CA set.
#  cert_file:
#
# Verify the hostname and server cert.
#  validate: true
#
# Client certificate and key in PEM format. It has to be provided when
# client_encryption_options.require_client_auth=true is set on server.
#  user_cert_file:
#  user_key_file
```
I believe that `cert_file` can be used to allow custom CAs, and `validate` to disable validation.

**Comment by bipul-baishya** [comment]
@Michal-Leszczynski 
Yes, I have tried this as well. It did not take the CA.

**Comment by Michal-Leszczynski** [comment]
@rzetelskik could you take a look?

**Comment by rzetelskik** [comment]
@bipul-baishya please open an issue in Scylla Operator repository with [must-gather archive](https://operator.docs.scylladb.com/stable/support/must-gather.html) attached.
