### ISSUE TITLE
`now+duration` start-date is broken by design

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-manager#3702]
sctool's `start-date` supports `now+duration` syntax, which is broken by design.
While `now` is handled by sending a zero-value time to the manager server, `now+duration` is resolved on the CLI's side by taking current time and adding duration to it: https://github.com/scylladb/scylla-manager/blob/d96e5d8338dd0afa5e130ee8cbb88b9cb11bc94b/pkg/command/flag/type.go#L121 

With an offset shorter than the network trip, this results in an error:
```
scylla@scylla-manager-f9fd9cc87-rvhzm:/$ sctool backup --cluster=scylla/scylla --location=gcs:rzetelskik-test --start-date='now+1s'
Flag --start-date has been deprecated, use cron instead
Error: create task: start date of scheduled task cannot be in the past
Trace ID: GDVIyJ0wTCiJU-e_6BxFIw (grep in scylla-manager logs)
```

I believe this is broken by design, since it should be handled on the server's side, but the API doesn't allow it.
Perhaps the most confusing part is that with the current implementation, scheduling two tasks with 'now' and 'now+duration' might result in only the latter failing.

Whether the `start date of scheduled task cannot be in the past` error is reasonable is up for debate - maybe the server could run the task immediately if the start-date is in the past according to it. However, such behaviour would force the server to take an opinionated decision regarding the `interval` flag then.

Since `start-date` is deprecated in sctool (see https://github.com/scylladb/scylla-manager/issues/3701 and https://github.com/scylladb/scylla-manager/issues/3700), this bug should at least be documented as a known issue. Ideally, there should be a replacement for this functionality.

cc @Michal-Leszczynski @karol-kokoszka

**Comment by karol-kokoszka** [comment]
I agree it's broken by design.
The problem is that flag is parsed before the startDate value is used.

So, the flow is:
- let's assume now() returns current time
- parse the "now + 1" that evaluates to now() + 1s and is saved as strict time.Time 
- check on saving task to db if start_date is < now(), but the now() here is later than now() from previous step o_O

The only quick way to work it around I see is define minimal shift that can be added to now and set it to ... let's say 10 minutes.

Who is even using it with now() + seconds ?

**Comment by karol-kokoszka** [comment]
Actually this whole check on server side is useless.
What's wrong if someone define start_date in the past ? Nothing.
I'll just remove the check.

**Comment by karol-kokoszka** [comment]
OK, actually there is a history behind why we use this check.
https://github.com/scylladb/scylla-manager/issues/3283

It's added to support old combination of interval + start_date.
Will keep the check, but I'm gonna limit it to the situation where interval and start_date is introduced. 
I'm not gonna fix the situation with now+1s. It's deprecated already.
