### ISSUE TITLE
The very first `repair` task fails with the `another task is running` error message but repair process really starts

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-manager#3709]
## Packages

Scylla version: `5.5.0~dev-20240201.66b859a29f8c` with build-id `30bfa8028707bf4d02a269a0c33be0d64153e592`

Operator Image: `scylladb/scylla-operator:latest`
Operator Helm Version: `v1.12.0-alpha.1-94-gfb3a2aa-latest`
Operator Helm Repository: `https://storage.googleapis.com/scylla-operator-charts/latest`
Kernel Version: `5.15.0-1048-gke`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

As part of the `disrupt_mgmt_corrupt_then_repair` nemesis the `mgmt repair` operation was triggered.
Before trigger:
```
2024-02-04 03:13:06,187 f:remote_base.py  l:521  c:KubernetesCmdRunner  p:DEBUG > Running command "sh -c "supervisorctl start scylla || supervisorctl start scylla-server""...
...
2024-02-04 03:13:07,733 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "sh -c "supervisorctl start scylla || supervisorctl start scylla-server"" finished with status 0
...
2024-02-04 03:14:11,766 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "sctool cluster list" finished with status 0
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > sctool output: +--------------------------------------+-------------------------------+---------+-----------------+
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | ID                                   | Name                          | Port    | CQL credentials |
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > +--------------------------------------+-------------------------------+---------+-----------------+
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | 2bb2ce80-7cf9-4db2-b23c-28cf01684f35 | scylla/sct-cluster            | default | set             |
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | 688fbaa7-47bc-4d40-907c-9c99194d019e | scylla-manager/scylla-manager | default | set             |
2024-02-04 03:14:11,766 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > +--------------------------------------+-------------------------------+---------+-----------------+
```

After:
```
2024-02-04 03:14:14,472 f:wait.py         l:52   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until operator repair task: default-repair-task-name get it's status: attempt 1 ended with: None
...
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Schedule","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","in":"0s","begin":"2024-02-04T03:14:15.425Z","retry":0,"_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"http","M":"POST /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks","from":"10.112.1.26:55958","status":201,"bytes":0,"duration":"1083ms","_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Run started","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","retry":0,"_trace_id":"ZuGtwS_dRD2vo21xBorgQw"}
I0204 03:14:15.442877       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
...
{"L":"INFO","T":"2024-02-04T03:14:17.684Z","N":"scheduler.2bb2ce80","M":"Run ended with ERROR","task":"repair/562394a7-442f-4bc8-b753-dff50dcaf24d","status":"ERROR","cause":"another task is running","duration":"3.605711ms","_trace_id":"-oUKq6smR0ysFRguwzn5jg"}
...
{"L":"INFO","T":"2024-02-04T03:14:18.968Z","N":"scheduler.2bb2ce80","M":"Run started","task":"repair/52f0d92c-a82b-4968-9aa5-b31fe61be3df","retry":0,"_trace_id":"0hFZkEOmQ_CYMl3GQ6pWKw"}
{"L":"INFO","T":"2024-02-04T03:14:18.977Z","N":"scheduler.2bb2ce80","M":"Run ended with ERROR","task":"repair/52f0d92c-a82b-4968-9aa5-b31fe61be3df","status":"ERROR","cause":"another task is running","duration":"4.899166ms","_trace_id":"0hFZkEOmQ_CYMl3GQ6pWKw"}
...

...
2024-02-04 03:14:19,000 f:base.py         l:142  c:KubernetesCmdRunner  p:DEBUG > Command "sctool tasks -c 2bb2ce80-7cf9-4db2-b23c-28cf01684f35" finished with status 0
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > sctool output: +---------------------------------+-------------+--------+----------+---------+-------+------------------------+-----------------------+-+
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | Task                            | Schedule    | Window | Timezone | Success | Error | Last Success           | Last Error             | Status      |...
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+------------------------+------------------------+-------------+-+
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/rest                | @every 1m0s |        | UTC      | 140     | 0     | 04 Feb 24 03:14:02 UTC |                        | DONE        |...
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/alternator          | @every 15s  |        | UTC      | 559     | 0     | 04 Feb 24 03:14:17 UTC |                        | DONE        |...
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | healthcheck/cql                 | @every 15s  |        | UTC      | 551     | 0     | 04 Feb 24 03:14:15 UTC |                        | DONE        |...
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > | repair/default-repair-task-name |             |        |          | 0       | 1     |                        | 04 Feb 24 03:14:18 UTC | ERROR (0/3) |...
2024-02-04 03:14:19,000 f:cli.py          l:1126 c:sdcm.mgmt.cli        p:DEBUG > +---------------------------------+-------------+--------+----------+---------+-------+------------------------+------------------------+-------------+-+
...
```

So, we see that the `repair` operation marked as `failed`. 
But, we see following in the DB node logs:
```
INFO  2024-02-04 03:14:18,618 [shard 0:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: starting user-requested repair for keyspace system_auth, repair id 1, options {{columnFamilies -> role_attributes}, {ranges -> -9223372036854775808:9223372036854775807}, {hosts -> 10.116.2.139,10.116.8.204,10.116.8.55}}
INFO  2024-02-04 03:14:18,618 [shard 0:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Skipped sending repair_flush_hints_batchlog to nodes={10.116.8.55, 10.116.8.204, 10.116.2.139}
INFO  2024-02-04 03:14:18,618 [shard 0:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,618 [shard 2:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,618 [shard 4:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,618 [shard 6:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,618 [shard 3:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,619 [shard 5:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,622 [shard 1:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: Started to repair 1 out of 1 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=repair
INFO  2024-02-04 03:14:18,622 [shard 6:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: stats: repair_reason=repair, keyspace=system_auth, tables={role_attributes}, ranges_nr=1, round_nr=1, round_nr_fast_path_already_synced=1, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=10, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.003322689 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{10.116.2.139, 0}, {10.116.8.204, 0}, {10.116.8.55, 0}}, row_from_disk_nr={{10.116.2.139, 0}, {10.116.8.204, 0}, {10.116.8.55, 0}}, row_from_disk_bytes_per_sec={{10.116.2.139, 0}, {10.116.8.204, 0}, {10.116.8.55, 0}} MiB/s, row_from_disk_rows_per_sec={{10.116.2.139, 0}, {10.116.8.204, 0}, {10.116.8.55, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
INFO  2024-02-04 03:14:18,622 [shard 6:strm] repair - repair[ce5450df-8449-48ec-ad36-6f0c1dcb3710]: completed successfully, keyspace=system_auth
...
```

## Impact

`sctool` shows that repair operation failed.

## How frequently does it reproduce?

Unknown

## Installation details

Cluster size: 3 pods/nodes (n1-standard-8)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `scylladb/scylladb:5.5.0-dev-0.20240201.66b859a29f8c` (k8s-gke: `us-east1`)

Test: `longevity-scylla-operator-3h-gke`
Test id: `d32afd01-a070-49ac-ab85-5ed87332bae0`
Test name: `scylla-operator/operator-master/gke/longevity-scylla-operator-3h-gke`
Test config file(s):

- [longevity-scylla-operator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6833e66b858db723075c0e956b306887d8fe3d58/test-cases/scylla-operator/longevity-scylla-operator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d32afd01-a070-49ac-ab85-5ed87332bae0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d32afd01-a070-49ac-ab85-5ed87332bae0)
- Show all stored logs command: `$ hydra investigate show-logs d32afd01-a070-49ac-ab85-5ed87332bae0`

## Logs:
- **kubernetes-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-d32afd01.tar.gz)
- **kubernetes-must-gather-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-must-gather-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/kubernetes-must-gather-d32afd01.tar.gz)
- **db-cluster-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/db-cluster-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/db-cluster-d32afd01.tar.gz)
- **sct-runner-events-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-runner-events-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-runner-events-d32afd01.tar.gz)
- **sct-d32afd01.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-d32afd01.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/sct-d32afd01.log.tar.gz)
- **loader-set-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/loader-set-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/loader-set-d32afd01.tar.gz)
- **monitor-set-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/monitor-set-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/monitor-set-d32afd01.tar.gz)
- **parallel-timelines-report-d32afd01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/parallel-timelines-report-d32afd01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d32afd01-a070-49ac-ab85-5ed87332bae0/20240204_043305/parallel-timelines-report-d32afd01.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/gke/job/longevity-scylla-operator-3h-gke/70/)
[Argus](https://argus.scylladb.com/test/b9f7805a-73c8-45a1-9846-5826da89bcb9/runs?additionalRuns[]=d32afd01-a070-49ac-ab85-5ed87332bae0)
</details>

**Comment by Michal-Leszczynski** [comment]
Error `another task is running` means that this SM is in the middle of running a repair task on the same cluster, so it won't start a new repair. But there is still the ongoing repair, so it makes sense that there are repair logs in the DB.

What's puzzling is that the fragment of pasted logs contains only one repair task definition in `sctool tasks` output, but we can see multiple repair tasks in the logs: 
- repair/562394a7-442f-4bc8-b753-dff50dcaf24d
- repair/52f0d92c-a82b-4968-9aa5-b31fe61be3df
- repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10

Is there a chance that this test deletes a running repair task and then tries to start a new one?
Also, it looks like SM logs from `monitor-set` are empty, so I can't tell much more about SM POV.

**Comment by soyacz** [comment]
there are SM logs in kubernetes-dc964a53.tar.gz - https://cloudius-jenkins-test.s3.amazonaws.com/dc964a53-775c-419d-9fb3-0f976e4994f5/20240211_043130/kubernetes-dc964a53.tar.gz

**Comment by vponomaryov** [comment]
> Error `another task is running` means that this SM is in the middle of running a repair task on the same cluster, so it won't start a new repair. But there is still the ongoing repair, so it makes sense that there are repair logs in the DB.
> 
> What's puzzling is that the fragment of pasted logs contains only one repair task definition in `sctool tasks` output, but we can see multiple repair tasks in the logs:
> 
> * repair/562394a7-442f-4bc8-b753-dff50dcaf24d
> * repair/52f0d92c-a82b-4968-9aa5-b31fe61be3df
> * repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10
> 
> Is there a chance that this test deletes a running repair task and then tries to start a new one? 

We don't do it from the SCT side explicitly.

> Also, it looks like SM logs from `monitor-set` are empty, so I can't tell much more about SM POV.

This bug report is based on the K8S.
In K8S the scylla-manager runs as a pod in a K8S cluster.
So, it's logs are in the it's logs.
There are 2 types of scylla-manager logs - pod logs and streamed log for whole test run.
So, the streamed one must be enough for this case.

**Comment by vponomaryov** [comment]
Looked at the logs of the test run used for the bug report.
Logs in scylla-manager:

```
{"L":"INFO","T":"2024-02-04T03:14:15.419Z","N":"scheduler","M":"PutTask","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","schedule":{"cron":"","window":null,"timezone":"","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":3,"retry_wait":""},"properties":{"intensity":1,"parallel":0,"small_table_threshold":1073741824},"create":true,"_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Schedule","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","in":"0s","begin":"2024-02-04T03:14:15.425Z","retry":0,"_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"http","M":"POST /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks","from":"10.112.1.26:55958","status":201,"bytes":0,"duration":"1083ms","_trace_id":"ACrHtMx0TMybPomMXW0nRw"}
{"L":"INFO","T":"2024-02-04T03:14:15.425Z","N":"scheduler.2bb2ce80","M":"Run started","task":"repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","retry":0,"_trace_id":"ZuGtwS_dRD2vo21xBorgQw"}
I0204 03:14:15.442877       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
{"L":"INFO","T":"2024-02-04T03:14:15.447Z","N":"http","M":"GET /api/v1/clusters","from":"10.112.1.26:55958","status":200,"bytes":553,"duration":"4ms","_trace_id":"uDnGOBTHS-OP7gv5tEwHDA"}
{"L":"INFO","T":"2024-02-04T03:14:15.451Z","N":"http","M":"GET /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks?all=true&type=repair","from":"10.112.1.26:55958","status":200,"bytes":520,"duration":"3ms","_trace_id":"4Vye-kEnSAWfKH3b2zUbYA"}
{"L":"INFO","T":"2024-02-04T03:14:15.453Z","N":"http","M":"GET /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/tasks?all=true&type=backup","from":"10.112.1.26:55958","status":200,"bytes":5,"duration":"1ms","_trace_id":"lrPBAfXmQPKmPhbAGTIdGg"}
{"L":"INFO","T":"2024-02-04T03:14:15.465Z","N":"scheduler","M":"Task deleted","cluster_id":"2bb2ce80-7cf9-4db2-b23c-28cf01684f35","task_type":"repair","task_id":"799b3ca6-7cf8-4437-aef6-5e917cd08a10","_trace_id":"GkrvnTU9Rk2yf7SbPcfjnw"}
{"L":"INFO","T":"2024-02-04T03:14:15.465Z","N":"http","M":"DELETE /api/v1/cluster/2bb2ce80-7cf9-4db2-b23c-28cf01684f35/task/repair/799b3ca6-7cf8-4437-aef6-5e917cd08a10","from":"10.112.1.26:55958","status":0,"bytes":0,"duration":"11ms","_trace_id":"GkrvnTU9Rk2yf7SbPcfjnw"}
```

Just `46ms` pass between creation and deletion of the mgmt `repair` task.
The caller of the `Delete` API is `10.112.1.26:55958`.

And the `10.112.1.26` IP address belongs to the `scylla-manager-controller` (one of two) provisioned by the `scylla-operator`:
```
...
scylla-manager            scylla-manager-controller-845cd4749d-4gg6x                   1/1     Running     0 \
                  3h45m   10.112.1.26   gke-longev-scylla-operat-default-pool-efb3d2c6-z8fc   <none>           <none>
scylla-manager            scylla-manager-controller-845cd4749d-txpsj                   1/1     Running     0 \
                  3h45m   10.112.0.21   gke-longev-scylla-operat-default-pool-efb3d2c6-vmt0   <none>           <none>
scylla-manager            scylla-manager-ff7c6ffcf-ztp9l                               1/1     Running     0 \
                  3h45m   10.112.1.25   gke-longev-scylla-operat-default-pool-efb3d2c6-z8fc   <none>           <none>
scylla-manager            scylla-manager-manager-dc-manager-rack-0                     2/2     Running     0 \
                  3h45m   10.112.0.22   gke-longev-scylla-operat-default-pool-efb3d2c6-vmt0   <none>           <none>
...
```

Logs from that controller at that time:
```
I0204 03:14:15.442877       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
I0204 03:14:18.998063       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
```

We know that `ScyllaCluster` K8S object has `backups` and `repairs` fields which get updated each time new appropriate mgmt task gets created.
Example:
```
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  annotations:
    meta.helm.sh/release-name: scylla
    meta.helm.sh/release-namespace: scylla
  creationTimestamp: "2024-02-04T00:42:47Z"
  generation: 16
  labels:
    app.kubernetes.io/managed-by: Helm
  name: sct-cluster
  namespace: scylla
  resourceVersion: "151064"
  uid: 944aa1a8-0c0e-4cd2-a94d-b1f4a8edd7f5
spec:
...
  repairs:
  - intensity: "1"
    interval: "0"
    name: default-repair-task-name
    numRetries: 3
    parallel: 0
    smallTableThreshold: 1GiB
    startDate: now
...
```

So, from scylla-operator point of view it is `retry` on failure to update the `ScyllaCluster` K8S object , but from the scylla-manager point of view it is loop of task creations and deletions.
It is definitely bug in the `scylla-manager-controller` created by `scylla-operator`.

**Comment by vponomaryov** [comment]
Created appropriate scylla-operator bug here: https://github.com/scylladb/scylla-operator/issues/1729
