### ISSUE TITLE
Incorrect repair --host node filtering

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3736]
SM doesn't allow to repair with `--host` flag when table is not fully replicated (all tokens are on all hosts).
I was introduced when refactoring SM repair in `3.2.1`.
Ref https://github.com/scylladb/scylla-enterprise/issues/3948

**Comment by mykaul** [comment]
Is this going into 3.2.6 or 3.2.7?

**Comment by Michal-Leszczynski** [comment]
It can be a part of 3.2.6.
