### ISSUE TITLE
not all keyspaces are repaired after restore

### ISSUE THREAD

**Issue by nopzdk** [scylladb/scylla-manager#3739]
created keyspace1.standard1
ran sctool backup,
truncated table keyspace1.standard1
restored table with sctool
Then when running sctool repair keyspace1.standard1 was not included in the repair.  

 sctool -c test progress repair/all-weekly
Run:            2d4a8f2a-d707-11ee-9389-0242ac170002
Status:         DONE
Start time:     29 Feb 24 13:33:51 UTC
End time:       29 Feb 24 13:33:52 UTC
Duration:       0s
Progress:       100%
Intensity:      1
Parallel:       0
Datacenters:
  - datacenter1

+-------------------------------+--------------------------------+----------+----------+
| Keyspace                      |                          Table | Progress | Duration |
+-------------------------------+--------------------------------+----------+----------+
| system_distributed_everywhere | cdc_generation_descriptions_v2 | 100%     | 0s       |
+-------------------------------+--------------------------------+----------+----------+
| system_distributed            |      cdc_generation_timestamps | 100%     | 0s       |
| system_distributed            |    cdc_streams_descriptions_v2 | 100%     | 0s       |
| system_distributed            |                 service_levels | 100%     | 0s       |
| system_distributed            |              view_build_status | 100%     | 0s       |
+-------------------------------+--------------------------------+----------+----------+

**Comment by nopzdk** [comment]
It was the same problem with any restore.

**Comment by Michal-Leszczynski** [comment]
> It was the same problem with any restore.

Could you paste the output of `sctool progress restore --details`?

Also, if restored keyspace has RF 1, then it won't be repaired because there is no need to.
