### ISSUE TITLE
Disable tablets load balancing on taking the snapshot

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3759]
We must ensure that tablets load balancing is disabled before taking the snapshot and to reenable (!) it just afterwards.

The endpoint is as follow:
```
         "path":"/storage_service/tablets/balancing",
         "operations":[
            {
               "nickname":"tablet_balancing_enable",
               "method":"POST",
               "summary":"Controls tablet load-balancing",
               "type":"void",
               "produces":[
                  "application/json"
               ],
               "parameters":[
                  {
                     "name":"enabled",
                     "description":"When set to false, tablet load balancing is disabled",
                     "required":true,
                     "allowMultiple":false,
                     "type":"boolean",
                     "paramType":"query"
                  }
               ]
            }
         ]
```

Tablets could migrate during the snapshot creation time otherwise what makes the snapshot useless.

It must be used only on tablets enabled environment.

**Comment by tzach** [comment]
@bhalevy FYI

**Comment by Michal-Leszczynski** [comment]
Is it safe to assume that we *always* want to disable it for taking a snapshot and *always* enable it afterwards? 

What about a situation when (for whatever reason) SM snapshots a cluster with already disabled tablet migration. Should SM enable tablet migration after snapshot anyway? I don't see any endpoint for checking if tablet migration is enabled or not, so it's not possible for SM to check that.

@bhalevy @tzach

**Comment by bhalevy** [comment]
Using the api to temporarily disable load balancing is an interim solution.
It's not design to be perfect or robust in any way.
We should implement a simple solution that disables LB unconditionally before snapshot and enables it afterwards
