### ISSUE TITLE
scylla-manager-agent --dump-manifest doesn't contain index files

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3761]
4dc88beb did the following:
- decoupled Index from ManifestContent
- read Index into memory only when requested (e.g. via `LoadIndex`)

This changes didn't take  `scylla-manager-agent --dump-manifest` into account and resulted in returning only less interesting  information like shown [here](https://github.com/scylladb/scylla-enterprise/issues/3995#issuecomment-2013971695) (skipped index files).

Note that this command has also been a part of restore ansible script since SM 3.1 (6933761c). This means that this script shouldn't have worked since that time.

cc: @karol-kokoszka

**Comment by tarzanek** [comment]
awesome, so old cloning ansible playbook will work again?
thnx @Michal-Leszczynski !

**Comment by Michal-Leszczynski** [comment]
@tarzanek we don't plan on supporting it, but it should work as it used to and I will try to validate that.
Note that this playbook has always been vulnerable to some issues fixed in SM restore task (e.g. https://github.com/scylladb/scylla-enterprise/issues/2534), so this will still be the case here.

**Comment by Michal-Leszczynski** [comment]
Also, it is a know fact that SM restore task is really slow - mostly because it is supposed to work on any topology, but we can extend it with the `restore happy path` that should work as fast as ansible script but only when restoring into the same cluster as the one that was backed-up. This means the same topology, nodes, token ranges etc.

cc: @karol-kokoszka

**Comment by tarzanek** [comment]
> Also, it is a know fact that SM restore task is really slow - mostly because it is supposed to work on any topology, but we can extend it with the `restore happy path` that should work as fast as ansible script but only when restoring into the same cluster as the one that was backed-up. This means the same topology, nodes IDs, token ranges etc (so not even into another cluster with the same topology).
> 
> cc: @karol-kokoszka 

that would be great, Karol said he filed a bug to optimize ideal paths, so looking forward! thnx Michael
