### ISSUE TITLE
Don't backup views

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3771]
Backing up views doesn't make any sense as the advised way to restore them is by recreating them on restored table. This would require to first validate that the base table is even being backed up. Checking which tables are views and which are not can currently be done only via cql session. It might be available via scylla client if https://github.com/scylladb/scylladb/issues/17958 is implemented.

cc: @karol-kokoszka @tzach

**Comment by karol-kokoszka** [comment]
Candidate for **3.2.9** (or **3.3.1**)

**Comment by karol-kokoszka** [comment]
**grooming notes**

SM doesn't restore views using SSTables. It just recreates them. There is complete no need of backing them up.

We must drop the backup of views and explicitly inform about it in the documentation.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka What about the situation, where someone sets `--keyspace` (perhaps by accident or because of not fully understanding how views work) in a way that the view table is included in the backup, but the base table is not? The two options are:
- don't backup base nor view table - not possible to restore base nor view tables
- backup base and not the view table - possible to restore both base and view tables

The second option results in more uploads and costs, but it's safer.

**Comment by karol-kokoszka** [comment]
The best in my option would be to validate this parameter upfront and just do not proceed.
Although the second option sounds reasonable too, but please WARN (or even ERROR) in logs.
