### ISSUE TITLE
'sctool backup list --all-clusters` requires cluster id

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3780]
Sctool supports command `sctool backup list --all-clusters -L s3:<location>` which is expected to list all snapshots that exist in the given location.
The command `sctool backup` requires to include cluster-id, what makes no sense for listing all snapshots from given location.

Example:
```
➜  scylla-manager git:(branch-3.2) ./sctool backup list --all-clusters -L s3:backuptest-smoke 
Error: required flag(s) "cluster" not set
```

, but works fine when cluster is specified and lists snapshots from other clusters too
```
➜  scylla-manager git:(branch-3.2) ./sctool backup list -c 2db3cfc5-e0bd-4832-ab13-652bff9a7bec --all-clusters -L s3:backuptest-smoke
Cluster: 2db3cfc5-e0bd-4832-ab13-652bff9a7bec

backup/aa327c5e-c12e-4340-a47d-70d0f2dcdf03
Snapshots:
  - sm_20240403092454UTC (3.900M, 6 nodes)
Keyspaces:
  - system_auth (4 tables)
  - system_traces (5 tables)
  - system_distributed (4 tables)
  - system_distributed_everywhere (1 table)
  - system_schema (15 tables)

Cluster: ab667845-996e-46a5-9699-9c3b3c792443

backup/eb28b979-c128-453d-b15c-88c0783f46f2
Snapshots:
  - sm_20240321143455UTC (3.595M, 3 nodes)
  - sm_20240321143454UTC (3.595M, 3 nodes)
Keyspaces:
  - backuptest_data (1 table)
```

**Goal**
Do not require `-c` flag on `sctool backup list --all-clusters -L s3:<location>` if `--all-clusters` is used.

**Comment by Michal-Leszczynski** [comment]
I think it's a dup of #3468.

**Comment by karol-kokoszka** [comment]
> I think it's a dup of #3468.

Seems so :) 
I'm loosing track of old issues. I'll set a mileston for this one and closed the original one.

**Comment by karol-kokoszka** [comment]
Update:
Indeed, it requires a cluster ID, and it cannot be changed.
The cluster ID serves as a coordinator cluster for the check. To verify the available backups in the backup location, the Scylla Manager Agent must have access to it.

In summary, the only action I can take is to update the documentation and clarify this caveat.
