### ISSUE TITLE
Update gocqlx dep

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3805]
We are using 2.6.0, from Nov 2021. The latest is newer https://github.com/scylladb/gocqlx/releases/tag/v2.8.0 and there's no reason we should not be using our own latest-greatest.

**Comment by karol-kokoszka** [comment]
@mykaul we are actually using the latest one https://github.com/scylladb/scylla-manager/blob/1634cd1875b047784be8528fcc8bb413fb7f3d60/go.mod#L37
Closing.
