### ISSUE TITLE
doc: wrong command to restart Scylla Manager Agent service

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla-manager#3808]
The procedure to Setup S3 compatible storage includes the following command to restart Scylla Manager Agent service:
`sudo systemctl start scylla-manager-agent`

A [Community Forum user reported](https://forum.scylladb.com/t/scylla-manager-backup-dry-run-fails-with-giving-up-after-2-attempts-after-30s-context-deadline-exceeded/529/17?u=anna) that the command is wrong and should be as follows (using `restart` instead of `start`):
`sudo systemctl restart scylla-manager-agent`

@karol-kokoszka Can you confirm?

We use the same command with `start` on other pages, too, e.g.:
https://manager.docs.scylladb.com/stable/backup/setup-amazon-s3.html
https://manager.docs.scylladb.com/stable/backup/setup-azure-blobstorage.html 
https://manager.docs.scylladb.com/stable/troubleshooting.html

**Comment by karol-kokoszka** [comment]
@annastuchlik community is right

**Comment by tzach** [comment]
@karol-kokoszka ping
