### ISSUE TITLE
docs: Issue in page Backup

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3825]
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.2/sctool/backup

### Problem

Wrong parameter name - `name` instead of `<bucket>`

https://manager.docs.scylladb.com/stable/sctool/backup.html#l-location

![image](https://github.com/scylladb/scylla-manager/assets/50706401/86303c8e-7e78-4914-9b04-02a4f9ca5fb3)

###  Suggest a fix

Replace `name` by `<bucket>`

**Comment by rayakurl** [comment]
@tzach - FYI. I assigned this issue to you, feel free to re-assign to the owner. Thanks
