### ISSUE TITLE
Failing `def test_small_table_threshold_parameter(self)` on manager-master jenkins CI

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3826]
https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-dtest/1486/consoleFull#-335546773fcc21424-66d2-4bd8-8e0d-9746405e5b16

There is high probability that it's flakiness, as the same test passed in the run from the day before.
https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-dtest/1483/

We need to validate if it's introduced in latest changes and which change could introduce this error.

cc: @Michal-Leszczynski @mikliapko

**Comment by Michal-Leszczynski** [comment]
This test fails on parsing logs Scylla node. From what I see in the logs, this test is run against master Scylla version (`unstable/master:2024-04-24T19:11:44Z`), so there were some changes in the log formatting on the core side.

**Comment by mikliapko** [comment]
I'll take a look into it most probably tomorrow
