### ISSUE TITLE
Include Scylla Enterprise nightly latest image to CI tests

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3833]
Scylla Nightly may not be fully stable.
Example of failing repair against Scylla Nightly https://github.com/scylladb/scylla-manager/actions/runs/8925245333/job/24517270900?pr=3832

We must test against fully releases or release candidates only.

**Comment by Michal-Leszczynski** [comment]
Mentioned test fails because of #3834, not Scylla Nightly on its own - but I agree that it would be good to have some more stable Scylla version in gh test matrix.

**Comment by mykaul** [comment]
I disagree, we need to test against master. We can pick master that passed CI of course. @yaronkaikov  can help with that.
