### ISSUE TITLE
[SCT] Introduce the test for Manager installation and smoke checks 

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3852]
The idea is to have a very basic smoke test that verifies:
- Manager installation;
- possibility to run some very common operations. 

The purpose is _**to run this test with non-main distros**_ (debian10, debian11, ubuntu20) as the main idea of test executions on different platforms are mainly to verify Manager installation process.

Worth mentioning that we have never encountered the OS-specific Manager issues before which makes this testing approach viable.

**Comment by mikliapko** [comment]
@karol-kokoszka @Michal-Leszczynski I'd like to hear your recommendations here what to check in manager right after installation to verify installation process for different OS distros?

**Comment by karol-kokoszka** [comment]
Hey @mikliapko, the most important part of Scylla Manager server is the API server actually.
The API server can be probed with `/api/v1/version` curl or by calling `sctool version` https://manager.docs.scylladb.com/stable/sctool/version.html. 
The latter is calling the same endpoint under the hood, so it validates if the API server is up and running.

In terms of scylla-manager-agent -> the same. The most important is API server to be up and running.
Call `/version` endpoint.

Would be good to have some readiness/liveness endpoint available in manager to check if other servers are up and running too, like prometheus server and consul handler (@Michal-Leszczynski ).

**Comment by Michal-Leszczynski** [comment]
> Would be good to have some readiness/liveness endpoint available in manager to check if other servers are up and running too, like prometheus server and consul handler (@Michal-Leszczynski ).

Do you mean that SM should query prometheus server which scrapes metrics from SM/agent and check if it's responding, or that SM should query SM/agent endpoints from which the metrics are being scraped and check if they are responding?

**Comment by karol-kokoszka** [comment]
**grooming notes**

Current idea:
- install manager on the cluster + install agents
- it checks the availability of the SM http server `curl --write-out "%{{http_code}}\n" --silent --output /dev/null "http://127.0.0.1:{port}/ping`
- the same ping is needed on the Scylla Manager Agent's HTTP server
- `sctool version` which ping SM HTTP server
