### ISSUE TITLE
[SCT] Introduce the test with mixed database (vnodes + tablets keyspaces)

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3853]
A few tests can be introduced here:

**Test 1**
Run manager sanity checks against the database with two keyspaces:
- vnodes ks;
- tablets ks.

**Test 2**
1. Create a backup for vnodes ks;
2. Turn on the tablets for ks;
3. Verify restore operation.

**Comment by mikliapko** [comment]
@karol-kokoszka @Michal-Leszczynski Guys, could you please review and spare your thoughts about the tests?

**Comment by Michal-Leszczynski** [comment]
Test 1 is really useful as we don't cover mixed setup with our own test right now.

I'm not sure about correctness of Test 2. In theory SM requires that backed-up cluster and restore destination cluster have the same schema and this test scenario breaks this assumption. It would be an interesting experiment, but it's not something that is currently covered by SM functionality.

**Comment by karol-kokoszka** [comment]
@mikliapko I agree with Michał.
Test 2 is against the restore pre-requisite which is to have the same schema.https://manager.docs.scylladb.com/stable/restore/restore-tables.html#prerequisites

**Comment by rayakurl** [comment]
@mikliapko please open an issue to scylla OSS to have an endpoint to check the status of tablet migration (ongoing or not).

**Comment by mikliapko** [comment]
Closing this task since the test for mixed cluster (vnodes+tablets) was introduced here (https://github.com/scylladb/scylla-cluster-tests/pull/7632).

The idea of test for tablets migration that comes from Michal [here](https://github.com/scylladb/scylla-manager/issues/3853#issuecomment-2120074678)) would be covered in a separate [task](https://github.com/scylladb/scylla-manager/issues/3940).
