### ISSUE TITLE
[SCT] Introduce the test for Rocky distro

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3854]
Since CentOS7 has been deprecated and manager tests were switched to run on Ubuntu images, we need to have at least one test for RHEL distro. 

Moreover, Rocky8 and Rocky9 are officially supported by Scylla Enterprise (https://enterprise.docs.scylladb.com/stable/getting-started/os-support.html).

**Comment by rayakurl** [comment]
Not sure if we need to run both rocky9 and rocky8. Maybe we can run 9 on a regular basis and 8 in the other job with all different distributions.

**Comment by mikliapko** [comment]
@fruch 
We have an idea to execute Manager tests on Rocky 8/Rocky 9 distributions since we got rid of CentOS and have no RHEL distributions coverage in tests.
In SCT I found only one example of Rocky usage - artifact tests in Google Cloud only. No attempts to use Rocky as image for monitoring node or install manager on such node yet. I suppose during the implementation of these tests in AWS with any untested Rocky image we may face some issues. Perhaps, you could anticipate any of them and guide us in the right direction to prevent from them?

@rayakurl FYI

**Comment by fruch** [comment]
> @fruch We have an idea to execute Manager tests on Rocky 8/Rocky 9 distributions since we got rid of CentOS and have no RHEL distributions coverage in tests. In SCT I found only one example of Rocky usage - artifact tests in Google Cloud only. No attempts to use Rocky as image for monitoring node or install manager on such node yet. I suppose during the implementation of these tests in AWS with any untested Rocky image we may face some issues. Perhaps, you could anticipate any of them and guide us in the right direction to prevent from them?

not much guidance on it, just start trying it out.
and start flushing any issue, it might work nicely out of the box..., it might not.

as for rocky9, there no python2, so it was problematic for scylla at a time, but now it's not (5.4/2024.1 and up).
so as for manager that need scylla, it might not work with older scylla

> 
> @rayakurl FYI

**Comment by mikliapko** [comment]
Rocky 9 is blocked by the issue https://github.com/scylladb/scylla-cluster-tests/issues/7678
