### ISSUE TITLE
Github Actions CI - add section on README.md

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3872]
We would like to move the integration tests badges down in the README.md file under its own section.
The name may be "Scylla integration status" and badges may be divided into explicit sections (scylla version, etc...).

What is the must, is the information of what test is skipped and why.
E.g. "system_auth_v2" data restore is not supported with Scylla 6.0.

**Comment by Michal-Leszczynski** [comment]
Also, we should describe it in our docs!
