### ISSUE TITLE
Issue on nodetool repair : keeps getting stuck for a long time 

### ISSUE THREAD

**Issue by shitalnyaupane** [scylladb/scylla-manager#3877]
I am trying to add a new Data Center to an existing 3 node scylla cluster. The older DC and the new DC are are different location (connected via IPsec). 
I successfully joined the new DC and is UN.
The problem arises while running nodetool repair command on the new node. It runs smoothly for a while but gets stuck at a certain point and the process stops suddenly.

###  Suggest a fix

**Comment by Michal-Leszczynski** [comment]
@shitalnyaupane If you are using nodetool repair and not Scylla Manager repair task, then this issue belongs to the https://github.com/scylladb/scylladb repository. In any case, it would probably be useful to see logs from repaired node.

I don't have permission to transfer issue to scylladb repo, @karol-kokoszka can you do that?

**Comment by karol-kokoszka** [comment]
Nope, I have no permissions to do that.
@tzach @mykaul can you transfer the issue to scylla repository ?

**Comment by shitalnyaupane** [comment]
Closing the issue. Posting it on scylla repository.
