### ISSUE TITLE
Use the replace_node_first_boot option rather than replace_address

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-manager#3901]
Since https://github.com/scylladb/scylladb/commit/1577aa8098cac7bc2ef0b7f9523044383e14896e (5.2), the `replace_address` and `replace_address_first_boot` options are deprecated and their usage is discouraged, and warned about (when used).
Instead, the user should use the `replace_node_first_boot` which states the replaced node's host_id rather than its ip address.

**Comment by karol-kokoszka** [comment]
Scylla Manager is not using `replace_address` config option at all, but thanks for the heads up !
I removed it from the scylla client we use.
