### ISSUE TITLE
Use read barrier API

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3932]
As described in https://github.com/scylladb/scylladb/issues/19213, we can now move from the "dummy schema change" workaround (also described in the mentioned issue) for Scylla versions starting at 6.1.
As this change has not been backported to Scylla 6.0, we still need to use the workaround there.

**Comment by Michal-Leszczynski** [comment]
Context:
When making a backup, it's important that backed up schema is not older than backed up sstables (otherwise sstables cannot be correctly interpreted). That's why we first snapshot all interesting tables, and only after that we query schema via CQL (`DESCRIBE SCHEMA WITH INTERNALS`).
The problem is that this query is routed to some single node in the cluster and it is possible that the schema from this node is older than already snapshot-ed sstables from some other node. In order to fix this, we perform raft read barrier in between snapshot-ing sstables and querying schema (it makes sure that all nodes fetch the new schema). It was previously done by relying on some mechanism performed under the hood when Scylla was evaluating dummy schema changing query, but now we should move to the proper approach.

**Comment by VAveryanov8** [comment]
> use this method instead of query.ReadBarrier when Scylla version is at least [6.1 or 2024.2](https://github.com/scylladb/scylla-manager/blob/bd6d1317d8f4770f9805152ed0713829cac0d737/pkg/scyllaclient/client_agent.go#L215)

hey @Michal-Leszczynski,  should we keep `query.ReadBarrier` method for Scylla version >= 6.0 then?

**Comment by Michal-Leszczynski** [comment]
> hey @Michal-Leszczynski, should we keep query.ReadBarrier method for Scylla version >= 6.0 then?

We want to use new Scylla API for Scylla versions supporting it (>= 6.1 / >= 2024.2).
We want to use `query.ReadBarrier` when we back-up schema via cql and the Scylla API is not supported (>= 6.0 and < 6.1)

**Comment by Michal-Leszczynski** [comment]
Fixed in #4110.
