### ISSUE TITLE
Unstable master builds versioning issue

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3944]
The version of unstable master builds contains invalid data about date and commit hash.

```
ubuntu@manager-regression-mikita-monitor-node-459da13b-1:~$ apt-cache policy scylla-manager-server
scylla-manager-server:
  Installed: 3.3.0~0.20240707.8f6f1c0b8-SNAPSHOT
  Candidate: 3.3.0~0.20240707.8f6f1c0b8-SNAPSHOT
  Version table:
 *** 3.3.0~0.20240707.8f6f1c0b8-SNAPSHOT 500
        500 https://downloads.scylladb.com/manager/deb/unstable/unified-deb/master/2024-07-24T21:54:57Z stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

For the example above, the build was created at **2024-07-24T21:54:57** but it has wrong:
- version **3.3.0~0.20240707.8f6f1c0b8-SNAPSHOT**;
- hash **8f6f1c0b8** which, at the moment of testing, is the latest commit to branch-3.3.

[Build.txt](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/manager-build/737/artifact/00-Build.txt/*view*/) file content for this build:
```
timestamp: 2024-07-24T21:54:57Z
jenkins-job-path: manager-master/manager-build
jenkins-job-number: 737
url-id: 2024-07-24T21:54:57Z
manager-build-sha: 50ad87c987959fd921d8350be88a5337685daf90
manager-version: 3.4.dev
manager-release: 0.20240724.50ad87c98
centos-rpm-repo-url: downloads.scylladb.com/manager/rpm/unstable/centos/master/2024-07-24T21:54:57Z
centos-rpm-repo-file-url: downloads.scylladb.com/manager/rpm/unstable/centos/master/2024-07-24T21:54:57Z/scylla-manager.repo
unified-deb-repo-url: downloads.scylladb.com/manager/deb/unstable/unified-deb/master/2024-07-24T21:54:57Z
unified-deb-repo-file-url: downloads.scylladb.com/manager/deb/unstable/unified-deb/master/2024-07-24T21:54:57Z/scylla-manager.list
reloc-pack-url: downloads.scylladb.com/manager/relocatable/unstable/master/2024-07-24T21:54:57Z
reloc-pack-file-url: https://downloads.scylladb.com/manager/relocatable/unstable/master/2024-07-24T21:54:57Z/scylla-manager_3.3.0-0.20240707.8f6f1c0b8-SNAPSHOT_linux_x86_64.tar.gz
scylla-manager-image-name: scylla-manager:3.4.dev-0.20240724.50ad87c98
scylla-manager-agent-image-name: scylla-manager-agent:3.4.dev-0.20240724.50ad87c98
```

**Comment by mikliapko** [comment]
@yaronkaikov Could you please take a look?

**Comment by yaronkaikov** [comment]
@mikliapko will send a fix today

**Comment by mikliapko** [comment]
The latest build from master has the version 3.4.0-dev
https://downloads.scylladb.com/manager/relocatable/unstable/master/2024-08-22T21%3A55%3A14Z/
![image](https://github.com/user-attachments/assets/3af7eec3-c168-42f7-85d6-b08315cd6a8a)

I suppose it should be something like 3.3.2-dev
@yaronkaikov @Annamikhlin

**Comment by yaronkaikov** [comment]
@mikliapko No, `master` is using the next major version so it is ok to be `3.4.0-dev`

**Comment by mikliapko** [comment]
> @mikliapko No, `master` is using the next major version so it is ok to be `3.4.0-dev`

okay, good to know, thanks!
