### ISSUE TITLE
Document max speed full cluster restore

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-manager#3946]
When running a full restore on the clusters, there is no need to limit resource consumption, which is there for backup and partial restore cases.

Examples:
`batch-size` can be increased
`parallel` set to zero
etc

Another recommendation is to restore to a bigger cluster and remove nodes later once the cluster with restored data is up and running.

**Comment by Michal-Leszczynski** [comment]
In terms of batch size, its impact on performance is already a part of the [docs](https://manager.docs.scylladb.com/stable/restore/index.html#restore-speed-and-granularity), but the default value should be adjusted (https://github.com/scylladb/scylla-manager/issues/3809).
