### ISSUE TITLE
[SCT] Add an option to reuse existing backup for restore benchmark test

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3950]
**The problem**
There is a great interest to improve Manager restore operation performance.

For this purpose we need to have stable SCT job for benchmarking. 

The bottleneck of the test we have now is:
- data propagation step, especially for large datasets (5TB per node dataset took around 5 hours to be propagated, [job](https://jenkins.scylladb.com/view/scylla-manager/job/manager-master/job/backup-restore-custom-dataset-test/28/));
- and backup operation that takes even longer time;

Both these operations are not significant for restore benchmarking purposes since might be eliminated in the test itself.

**The solution**
The possible solution to speed up the testing process might be a restore from precreated backups for different datasets (500GB, 1TB, 2TB, 5TB).

To achieve it, I suggest to add extra parameter to SCT job to whether reuse existing backup or write and backup the data from scratch.

**Comment by fruch** [comment]
> @fruch Is it safe to use s3:manager-backup-tests-us-east-1 bucket for such backup storing purpose? Do we have any retention policies for this bucket?

one should one and check, I remember it was setup to clear things after a week.
but that was long time ago, before restore was available, and @ShlomiBalalis was keeping backup for longer durations.
I don't remember where those are kept, and how retention works now
