### ISSUE TITLE
Allow for more pinned CPUs in the context of full speed restore

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3951]
On startup agent tries to pin to CPUs. The code is presented below, but the logic looks like this:
- if desired (single) CPU is specified in `scylla-manager-agent-yaml`, pin to this CPU
- find CPUs not taken by Scylla (if any) (taken from `/etc/scylla.d/cpuset.conf`), pin to those CPUs
- otherwise, don't pin to any CPU, but set the max amount of utilized CPUs at any time to 1

```go
	// Try to get CPUs to pin to
	var cpus []int
	if s.config.CPU != agent.NoCPU {
		cpus = []int{s.config.CPU}
	} else if free, err := findFreeCPUs(); err != nil {
		if os.IsNotExist(errors.Cause(err)) || errors.Is(err, cpuset.ErrNoCPUSetConfig) {
			// Ignore if there is no cpuset file
			s.logger.Debug(ctx, "Failed to find CPUs to pin to", "error", err)
		} else {
			s.logger.Error(ctx, "Failed to find CPUs to pin to", "error", err)
		}
	} else {
		cpus = free
	}
	// Pin to CPUs if possible
	if len(cpus) == 0 {
		s.logger.Info(ctx, "Running on all CPUs")
		runtime.GOMAXPROCS(1)
	} else {
		if err := pinToCPUs(cpus); err != nil {
			s.logger.Error(ctx, "Failed to pin to CPUs", "cpus", cpus, "error", err)
		} else {
			s.logger.Info(ctx, "Running on CPUs", "cpus", cpus)
		}
		runtime.GOMAXPROCS(len(cpus))
	}
```
We should allow for controlling the CPU pinning in the context of faster restore speed.
The current implementation of restore does not allow for files download (agent) and load&stream (Scylla) at the same time, so even when they share the CPUs, they "wouldn't fight for them that much" (note that Scylla is still receiving data send to it by other load&streaming nodes in the Cluster while the download is happening).
Anyway, pinning CPUs to agent in the context of full speed restore should be bench-marked.

cc: @mykaul @tzach

**Comment by mykaul** [comment]
> * otherwise, don't pin to any CPU, but set the max amount of utilized CPUs at any time to 1

Why? Just like the network cores, if there aren't any dedicated cores, they are shared with Scylla.
