### ISSUE TITLE
Potential bug - data resurrection during restore from backup

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla-manager#3964]
There is potential in data resurrection in this scenario of backup restore.

Assume there are 2 sstables files for a given key. In one of them, s1, we have
a tombstone entry with a date d1, in the other sstable, s2, we have data
from a date of d2 = d1-x.

If the backup process first processes S1, runs compaction and purges the tombstone
and later copies S2 from backup, data will resurect.

Possible solutions:
1. Pause compaction until all data arrived from backup
2. Use tombstone-gc=repair this way tombstones will stay until repair

**Comment by Michal-Leszczynski** [comment]
@dorlaor SM already sets tombstone_gc=disabled for the time of restoring the data, and resets it to the previous value only after running the repair. It is also mentioned in the [docs](https://manager.docs.scylladb.com/stable/restore/restore-tables.html#procedure).

So can we close this issue, or is there still something missing?

**Comment by dorlaor** [comment]
Yes, super!
