### ISSUE TITLE
 Batch sstables of similar size

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3979]
Assume the following scenario: node with 8 shards, batch with 8 sstables, 1 is really big, 7 are small.
As only a single shard works on load&stream of given sstable, we would end up in a situation where the 7 shards taking care of small sstables would finish their work quickly and wait for the single shard working on a big sstable.
Creating batches of similarly sized sstables would improve load&stream performance.

**Comment by mykaul** [comment]
Is this part of 3.3.2?

**Comment by Michal-Leszczynski** [comment]
No, the 3.3.2 will mostly contain a fix for #3989 and perhaps #4007 and #3995.
I would say that the restore related improvements are big enough for 3.4, but if there is a need to keep it as a patch release, it could be 3.3.3.

**Comment by karol-kokoszka** [comment]
The change is going to affect the meaning of `batch-size` flag when the value is set to 0.
0 is going to be wild-card meaning that batch size is expected to be 5% of the all data that would be sent to the node (basing on the following calculation -> **(amount_of_restore_data * number_of_node_shards) / number_of_all_shards** ).

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka do we want to make --batch-size=0 default in SM 3.4?
If I were to choose the default values from the scratch, I would choose in order to restore as fast as possible - as this is the most common case. On the other hand, changing the default value for the flag might break compatibility in other projects.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski please leave the current default.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka so we can close https://github.com/scylladb/scylla-manager/issues/3809 then?

**Comment by karol-kokoszka** [comment]
Let's bring it to the planning. IMHO we should keep the default, but let's discuss on planning.
