### ISSUE TITLE
Restore many tables in parallel from a single node

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3982]
In order to increase resource saturation, SM could restore many (probably 2) tables from the same node at the same time. It would be even better to restore the same table from the same node in parallel, but each table has only a single upload dir on which the l&s job works, so it's not possible.

**Comment by karol-kokoszka** [comment]
There is no observation that proves real need for this fix.
The experiment made with more than 1 L&S running in parallel from a single cluster didn't show any restore time improvement.
