### ISSUE TITLE
 Unable to locate package scylla-manager-server, Unable to locate package scylla-manager-client  errors during node setup 

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-manager#3988]
SCT failed at the node setup stage with the error sdcm.cluster.NodeSetupFailed on latest enterprise image  scylla-enterprise-2024.3.0-dev-x86_64-2024-08-21T01-55-20 | ami-0c6e012613f908379
 
 JOB: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2-low-load/18/execution/node/182/log/
 
 message 
 
 ```
 10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=120 -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" install -y scylla-manager-server scylla-manager-client'
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Exit code: 100
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stdout:
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Reading package lists...
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Building dependency tree...
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Reading state information...
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stderr:
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > E: Unable to locate package scylla-manager-server
10:42:15  < t:2024-08-21 08:42:15,414 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > E: Unable to locate package scylla-manager-client
 ```
 
The issue also reproduced on images that worked previously (scylla-enterprise-2024.3.0-dev-x86_64-2024-08-19T01-44-22 | ami-0703eb70ef9806b2f)  
 
Node setup  21 Aug - failed:   https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2/15/execution/node/182/log/

Node setup 19 Aug - passed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2/11/execution/node/182/log/?consoleFull

**Comment by temichus** [comment]
cc @mykaul

**Comment by mykaul** [comment]
@Annamikhlin , @karol-kokoszka - please look into it. Either some repo issue - or the new gpg key issue?

**Comment by karol-kokoszka** [comment]
It seem to be connected to the new gpg key.
I added manager-3.3 to my local apt, and cannot update because of:
```
Err:12 https://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.3 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A43E06657BAC99E3
```

@Annamikhlin the .list file looks like that:
```
deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/scylladb.gpg] https://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.3 stable main
```
How can I import the new key ?

Things like:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A43E06657BAC99E3
```
or
```
wget -qO - https://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.3/A43E06657BAC99E3.gpg.key | sudo apt-key add -
```

doesn't work.

**Comment by Annamikhlin** [comment]
@karol-kokoszka - It was imported for me locally
```
root@d00e4cdf0693:/# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A43E06657BAC99E3
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.jYy3yLzlxh/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys A43E06657BAC99E3
gpg: key A43E06657BAC99E3: public key "ScyllaDB Package Signing Key 2024 (RSA) <security@scylladb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@d00e4cdf0693:/# 
```

> Node setup 21 Aug - failed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2/15/execution/node/182/log/

@temichus - to which byo job number your test is refer to?
```
byo_job_path
/scylla-master/byo/byo_build_tests_dtest
```

**Comment by karol-kokoszka** [comment]
@Annamikhlin try 
```
sudo apt-get update
```
Err:13 https://downloads.scylladb.com/downloads/scylla-manager/deb/ubuntu/scylladb-manager-3.3 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A43E06657BAC99E3

**Comment by mykaul** [comment]
@karol-kokoszka - are you failing to update the key first? or did you update and it still doesn't work?

**Comment by karol-kokoszka** [comment]
I updated the key, I see the same output as @Annamikhlin provided, but the `sudo apt-get update` still fails.

**Comment by temichus** [comment]
> @karol-kokoszka - It was imported for me locally
> 
> ```
> # apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A43E06657BAC99E3
> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
> Executing: /tmp/apt-key-gpghome.jYy3yLzlxh/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys A43E06657BAC99E3
> gpg: key A43E06657BAC99E3: public key "ScyllaDB Package Signing Key 2024 (RSA) <security@scylladb.com>" imported
> gpg: Total number processed: 1
> gpg:               imported: 1 
> ```
> 
> > Node setup 21 Aug - failed: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2/15/execution/node/182/log/
> 
> @temichus - to which byo job number your test is refer to?
> 
> ```
> byo_job_path
> /scylla-master/byo/byo_build_tests_dtest
> ```

Job has just  "scylla_version: enterprise:latest" and did non use  "byo" functionality

**Comment by Annamikhlin** [comment]
ok, reproduced it locally and found an issue with configuration of ListUrl in pkg
https://github.com/scylladb/scylla-pkg/blob/3784ef0b4520da8ddbd79432587ee6237c4740d4/scripts/jenkins-pipelines/manager/branch-specific.properties#L24
pointed to `master` instead of b`ranch-3.3`

**Comment by karol-kokoszka** [comment]
@Annamikhlin will we need to promote Scylla-Manager once again ?

**Comment by Annamikhlin** [comment]
> @Annamikhlin will we need to promote Scylla-Manager once again ?

Yes

**Comment by Annamikhlin** [comment]
https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.3/job/manager-build/48/ - manager-build passed with a fix commit

**Comment by karol-kokoszka** [comment]
So, now it's `manager-release` and `manager-promote` to run ?

**Comment by Annamikhlin** [comment]
> So, now it's `manager-release` and `manager-promote` to run ?

`manager-promote` is currently running https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.3/job/manager-promote/4/
create repo already passed. checking locally

**Comment by karol-kokoszka** [comment]
Thank you !

**Comment by Annamikhlin** [comment]
@tzach - need to update the site with version `manager-3.3` and new gpg key `A43E06657BAC99E3`
the latest version on the site is `manager-3.2` - https://www.scylladb.com/download/?platform=ubuntu-22.04&version=manager-3.2#manager

**Comment by karol-kokoszka** [comment]
I confirm that it works for me as well.

**Comment by mykaul** [comment]
@mikliapko , @rayakurl - we need to add post release tests, to ensure we catch such issues faster. Could be an 'artifacts' tests post release.

**Comment by rayakurl** [comment]
> @mikliapko , @rayakurl - we need to add post release tests, to ensure we catch such issues faster. Could be an 'artifacts' tests post release.

@mikliapko thanks for opening the issue, we can discuss the priority after the restore effort is over.

**Comment by aleksbykov** [comment]
Issue still reproduced with job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2-hight-load/

**Comment by yaronkaikov** [comment]
> Issue still reproduced with job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/Serverless_v2/job/perf-regression-elasticity-test-serverless-v2-hight-load/

Please verify that this branch you are working on is rebased, it should have https://github.com/scylladb/scylla-cluster-tests/pull/8173/commits/7b9a46e3dbac2a9f104a732ae6b6a1649a4fe075 otherwise it will not work

**Comment by tzach** [comment]
> @tzach - need to update the site with version manager-3.3 and new gpg key A43E06657BAC99E3 for 3.3.1
> the latest version on the site is manager-3.2 - https://www.scylladb.com/download/?platform=ubuntu-22.04&version=manager-3.2#manager

Done. Please validate.

**Comment by yaronkaikov** [comment]
> > @tzach - need to update the site with version manager-3.3 and new gpg key A43E06657BAC99E3 for 3.3.1
> > the latest version on the site is manager-3.2 - https://www.scylladb.com/download/?platform=ubuntu-22.04&version=manager-3.2#manager
> 
> Done. Please validate.

Looks good :-)

**Comment by mikliapko** [comment]
AFAIU we faced this issue because of the problem in `promote` job, right?
In current approach we trigger tests in `build` job and use the link to .repo/.list file from unstable. That's why we missed this problem. 
I wonder if we can extend promote pipeline to trigger simple test that installs Manager from official source (`https://downloads.scylladb.com/deb/ubuntu/scylladb-manager-3.3.list`, for example) after promotion stage?

@yaronkaikov @Annamikhlin What do you think?

**Comment by yaronkaikov** [comment]
> AFAIU we faced this issue because of the problem in `promote` job, right? In current approach we trigger tests in `build` job and use the link to .repo/.list file from unstable. That's why we missed this problem. I wonder if we can extend promote pipeline to trigger simple test that installs Manager from official source (`https://downloads.scylladb.com/deb/ubuntu/scylladb-manager-3.3.list`, for example) after promotion stage?
> 
> @yaronkaikov @Annamikhlin What do you think?

sure we can

I suggest to open an issue in scylla-pkg with details about the test you wish to trigger

**Comment by mikliapko** [comment]
> > AFAIU we faced this issue because of the problem in `promote` job, right? In current approach we trigger tests in `build` job and use the link to .repo/.list file from unstable. That's why we missed this problem. I wonder if we can extend promote pipeline to trigger simple test that installs Manager from official source (`https://downloads.scylladb.com/deb/ubuntu/scylladb-manager-3.3.list`, for example) after promotion stage?
> > @yaronkaikov @Annamikhlin What do you think?
> 
> sure we can
> 
> I suggest to open an issue in scylla-pkg with details about the test you wish to trigger

Issued the PR 
https://github.com/scylladb/scylla-pkg/pull/4302

**Comment by mykaul** [comment]
I think this issue is solved. What's left here?

**Comment by yaronkaikov** [comment]
> I think this issue is solved. What's left here?

Only merging https://github.com/scylladb/scylla-pkg/pull/4302
Probably will be done today

**Comment by yaronkaikov** [comment]
> > I think this issue is solved. What's left here?
> 
> Only merging [scylladb/scylla-pkg#4302](https://github.com/scylladb/scylla-pkg/pull/4302) Probably will be done today

Once merge this issue will be closed
