### ISSUE TITLE
[QA] SCT test to validate restore with L&S outside of Scylla Manager

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3993]
As per quick check on `scylla-cluster-test` repo, it seems that we have test validating if it's possible to do the restore using `nodetool refresh` capabilities.
https://github.com/scylladb/scylla-cluster-tests/blob/4ff526a2f249ab9291cb41af6d3a6381903aafcf/mgmt_cli_test.py#L149-L176

We want to validate the following:
- do the restore with `nodetool refresh` as it is now done with this test, but including validation of the restore correctness (if the all data is here). Possibly it doesn't restore it correctl as according to https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool-commands/refresh.html 

> ScyllaDB node will ignore the partitions in the sstables which are not assigned to this node. For example, if sstable are copied from a different node.

...and we cannot assure that partitions are the same.

- do the restore with `nodetool refresh`, but including `--load-and-stream` + `--primary-replica-only` flags. The test is downloading and then refreshing, so it will test the nodetool behavior when then batch is basically the whole data of the given node.

The cluster cannot be 1 node size, but it must be multi node cluster (exactly the same as used to benchmark restore with SM).
The amount of data must be the same as we use in benchmarking restore done with SM.

These tests will help us to understand if the L&S feature is efficient enough when doing the restore of the full cluster.

cc: @mikliapko

**Comment by mikliapko** [comment]
@karol-kokoszka 
Current approach does `nodetool refresh` node by node and table by table sequentially:
https://github.com/scylladb/scylla-cluster-tests/blob/4ff526a2f249ab9291cb41af6d3a6381903aafcf/mgmt_cli_test.py#L163-L176

Do we need to make it parallel? And if yes - parallel for nodes only or for tables as well?

**Comment by karol-kokoszka** [comment]
We can proceed with node by node, table by table for the moment.
Let's just have some results from the nodetool refresh with L&S.

Nodes could be parallelized as a part of experiment.

**Comment by mikliapko** [comment]
@karol-kokoszka 
Do we have have any alternatives to `sctool backup files` now?

I've seen that the command is deprecated but it still returns valid info for some of snapshots.
As far as I understood, it works well for snapshots that were created on the same cluster because when I try to run it with some  snapshots from another cluster I get nothing:
```
ubuntu@manager-restore-out-of-manager-miki-monitor-node-bd4f72e9-1:~$ sctool -c mgr_cluster1 backup files --snapshot-tag sm_20240812100424UTC --location s3:manager-backup-tests-permanent-snapshots-us-east-1
Command "files" is deprecated, use sctool restore instead, see https://manager.docs.scylladb.com/stable/restore/index.html.

ubuntu@manager-restore-out-of-manager-miki-monitor-node-bd4f72e9-1:~$ echo $?
0
```

**Comment by karol-kokoszka** [comment]
I understand the goal is to list all the files belonging to the given snapshot.
It works fine but for snapshots of the cluster that is managed by the current manager server.

**Comment by karol-kokoszka** [comment]
It worked for me when I used:
```
sctool backup files --snapshot_tag <tag> --all-clusters -L s3:<locatiom>
```

**Comment by karol-kokoszka** [comment]
btw, this is useful command, I'll "undeprecate" it.

**Comment by mikliapko** [comment]
> It worked for me when I used:
> 
> ```
> sctool backup files --snapshot_tag <tag> --all-clusters -L s3:<locatiom>
> ```

`--all-clusters` flag helped me, thanks

**Comment by mikliapko** [comment]
The first run results:
- `nodetool refresh` 
https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/manager-master/job/backup-restore-outside-manager/15/
- `nodetool refresh --load-and-stream --primary-replica-only` 
https://jenkins.scylladb.com/job/scylla-staging/job/mikita/job/manager-master/job/backup-restore-outside-manager/16/
