### ISSUE TITLE
"Undeprecate" `sctool backup files` command and provide the documentation

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3996]
As per topic

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka what is the motivation?

**Comment by karol-kokoszka** [comment]
> @karol-kokoszka what is the motivation?

There are questions from time to time, "Is it possible to get the list and paths to the files included into the given snapshot ?".
Using this CLI is much more comfort than checking and aggregating the contents of manifest files.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka ok, but then it should be backported to 3.2 as well.

**Comment by karol-kokoszka** [comment]
> @karol-kokoszka ok, but then it should be backported to 3.2 as well.

Hmmmm, yes it can. Although these are mostyl documentation changes. The CLI is available even if it's deprecated.
