### ISSUE TITLE
Add a test for 1-node cluster

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4003]
In release 3.3.1 we missed the regression issue which is relevant only for 1-node cluster (see details https://github.com/scylladb/scylla-manager/issues/3989).

We need to cover this cluster setup with test.

**Comment by karol-kokoszka** [comment]
Connected to https://github.com/scylladb/scylla-manager/issues/4030

The issue is valid only if we see troubles in integrating with operator tests.

**Comment by mykaul** [comment]
In a way, it's better to ensure operator are testing with a pre-release of manager - as they are the only users of a single node cluster in manager...

**Comment by karol-kokoszka** [comment]
https://github.com/scylladb/scylla-manager/issues/4030
