### ISSUE TITLE
docs: Issue on page Specification

### ISSUE THREAD

**Issue by regevran** [scylladb/scylla-manager#4009]
I would like to report an issue on page https://manager.docs.scylladb.com/branch-3.3/backup/specification

### Problem
1. `meta`, `schema` and `sst` _exact_ directory structure is not clear.

2. It seems that the path for schema is incorrect (no `schema` directory):
`meta/cluster/<cluster ID>/task_<task ID>_tag_<snapshot tag>_schema_with_internals.json.gz`

###  Suggest a fix
Make both the line and the drawing of the directories explicitly start from root (`/`).
e.g:
`/meta/schema/cluster/<cluster ID>/task_<task ID>_tag_<snapshot tag>_schema_with_internals.json.gz`

**Comment by Michal-Leszczynski** [comment]
Thanks for reporting!
The `schema` path is indeed incorrect, it should be `/schema/cluster/<cluster ID>/task_<task ID>_tag_<snapshot tag>_schema_with_internals.json.gz`. I can also change paths to start from root.

**Comment by regevran** [comment]
>  I can also change paths to start from root.
I think this is the best approach when possible.
If it is not hard-coded from root, and there is a prefix, then _this prefix_ should be mentioned after the root -
e.g. `/{prefix}/meta/scema.....`
