### ISSUE TITLE
auto upgrade agents

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-manager#4015]
I think when the manager is upgraded it could automatically have a feature to upgrade agents as well
(a job perhaps?)

It would make maintaining the cluster much easier.

**Comment by karol-kokoszka** [comment]
Scylla-manager-server doesn't have the full control over the servers where the agents are running. The communication is done via consuming agent's HTTP API. There is no SSH.

We cannot trigger automatic upgrade of agents.
