### ISSUE TITLE
Metrics from changed ip address nodes

### ISSUE THREAD

**Issue by ddimanss** [scylladb/scylla-manager#4017]
Problem with scylla-manager.
He returns "scylla_manager_healthcheck_cql_status{} = -1" for scylladb nodes in k8s where the pod was restarted and the IP address was changed. In Database he have all correct ip address in table scylla-manager.cluster

SM   "version": "3.4.0-dev-0.20240822.0ad5692f0"

**Comment by Michal-Leszczynski** [comment]
@ddimanss does the "scylla_manager_healthcheck_cql_status{} = -1" goes away after some time (e.g. 15min), or does is persist?

@karol-kokoszka I thought that healtcheck was supposed to delete metric entries for nodes removed from the cluster.
Could you take a look?

**Comment by ddimanss** [comment]
persist and out if restart SM

**Comment by ddimanss** [comment]
scylla_manager_healthcheck_cql_rtt_ms is affected by restarting the K8S pod.  Real cluster = 3 nodes with RF 3. all pods reboot and change IP. SM says there are 6 nodes in the cluster, 3 have cql failures and avg (scylla_manager_healthcheck_cql_rtt_ms{}) has ~500ms. After restarting SM scylla_manager_healthcheck_cql_rtt_ms -> 5-6 ms and the cluster becomes, according to SM, with 3 nodes with cql prode in working condition

**Comment by ddimanss** [comment]
My other cluster is 2 nodes per one replica. I got a restart of 3 nodes out of 6. So I see this
<img width="841" alt="image" src="https://github.com/user-attachments/assets/efba084f-64c7-4fc3-bc63-14ad05a63070">
and this 
<img width="887" alt="image" src="https://github.com/user-attachments/assets/159e7c6a-d8f6-4370-8e30-997ef73b4082">

**Comment by Michal-Leszczynski** [comment]
Pasted from slack from @SergeiMalkov:
> I have a question related to metrics being exposed by Scylla Manager.
Let's say we have a single-DC cluster with 12 (real node count doesn't matter here, just an arbitrary value) running recent Scylla Enterprise and Manager 3.3.3 and Monitoring stack 4.8.0
Based on some field observation we (Support/SRE/Devops) notice from time to time that data in the Manager dashboard is being incorrect for the count of alive nodes. Probably it has a correlation with nodes replacement (to be verified yet, so far we know that "all nodes amount" shown could be more than actual node count in the cluster and nodes that were replaced seem to be "counted in")
Sure thing, if we restart the scylla-manager.service (which has an impact on exposed metrics), the values get back to correct values and match actual cluster topology.

It confirms that something is wrong with SM metrics.
