### ISSUE TITLE
Helm Chart Dependency Issue

### ISSUE THREAD

**Issue by pggb25** [scylladb/scylla-manager#4025]
### Description:

I encountered an issue when using the scylla-manager Helm chart to install Scylla Manager.
	•	Helm version: v3.15.4
	•	Scylla-Manager chart version: v1.13.0

When running the following command:

```
helm dependency list scylla-manager
```

I get the following output:

```
NAME  	VERSION	REPOSITORY      	STATUS
scylla	1.0.0  	file://../scylla	wrong version
```

with the status showing wrong version.

Additionally, running:
```
helm dependency update scylla-manager
```

returns the error:

```
Error: directory scylla not found
```

### Workaround:

I was able to resolve the issue by modifying the dependencies section in the Chart.yaml file:
	•	I changed the version to 0.0.0 (as this is the version of scylla in the charts/scylla directory).
	•	I also updated the repository path to file://charts/scylla.

After making these changes, both commands succeed without errors.

### Question:

Could you confirm whether this is a problem with the chart dependencies configuration, or if it is a misunderstanding on my side?

**Comment by karol-kokoszka** [comment]
@pggb25 Please report this issue to https://github.com/scylladb/scylla-operator/
They are the owners of these helm charts.

**Comment by karol-kokoszka** [comment]
Not related to SM.
