### ISSUE TITLE
[SCT] Report backup/restore duration metrics to Argus

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4027]
Experiment with the suggestion [here](https://github.com/scylladb/scylla-cluster-tests/pull/8565#pullrequestreview-2285137872) and, if it works well for Manager, implement metrics reporting to Argus for Manager backup/restore benchmark tests.

**Comment by mikliapko** [comment]
Example of Argus implementation of graphs:
https://argus.scylladb.com/test/1edac104-c90b-4126-9328-ba466981af52/runs?additionalRuns%5B%5D=41e27241-1535-4875-b7c5-ae20e1150dae

**Comment by mikliapko** [comment]
@karol-kokoszka @Michal-Leszczynski 
I would like to hear your opinion about default backup size and restore configuration for such restore benchmark job (the test that would be run release by release and check we didn't degrade in terms of restore speed).
I'm about to choose 1TB ICS backup. 
What do you think about batch-size and parallel? Should we go with default values of them or set some specific values?

**Comment by Michal-Leszczynski** [comment]
1TB seems reasonable for a "quick" test.
In terms of the restore flags, let's use the defaults. Default '--parallel' already restores as fast as possible, and we p[lan to do the same](https://github.com/scylladb/scylla-manager/issues/3979#issuecomment-2337585029) with `--batch-size`.
New flags (e.g. `--transfers`) will also be set to max by default.
