### ISSUE TITLE
Interrupting restore targeting view tables is broken

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#4037]
This was the case in https://github.com/scylladb/scylla-enterprise/issues/4707.

View restoration happens by:
- saving view description in SM DB
- dropping the view from the cluster
- restoring view base table
- re-creating view from the saved description

SM re-calculates which tables should be ignored during restore at the beginning of each the task execution.
The problem is when SM restore task is interrupted after it already dropped the view tables.
SM has no way to difference view table from a regular one except for querying `system_schema.views` table, which won't contain information about already dropped views. Even though SM saved the views description in its DB, it does not use it (and it should) for checking if backed up table is a view that is restored in a different way.

**Comment by Michal-Leszczynski** [comment]
Actually, backups made with SM 3.3.1 or above won't encounter this issue during restore, as the views are not backed up in the first place (see #3771).

**Comment by karol-kokoszka** [comment]
As per refinement, the solution is to:
> Even though SM saved the views description in its DB, it does not use it (and it should) for checking if backed up table is a view that is restored in a different way.

^^^ check if SSTables are part of the view using already preserved data from SM db
