### ISSUE TITLE
`sctool progress ...` for restore task returns the same `Duration`, `Start time` and `End time` values for post-restore repair as for the whole process

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4046]
I suppose `Duration`, `Start time` and `End time` values should be different for **post-restore repair process** and show the info specific for this process only.

Here we have the same values for the **whole restore** and **post-restore repair**.

![image](https://github.com/user-attachments/assets/35b03473-4bcf-41bc-b42a-51658a7ed934)

**Comment by karol-kokoszka** [comment]
It clearly shows that the repair time is just taken from the restore.
This is a definitely a bug.

We must show the elapsed time of a post-repair instead.
