### ISSUE TITLE
Extend restore benchmark tests

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4048]
Currently we have one restore benchmark test that runs on 3-nodes cluster and restore 1tb_ics_1table backup snapshot (see in [Argus](https://argus.scylladb.com/workspace?state=WyIxZTRjZDc0My1hN2U0LTQ0M2EtYjAzMy03Y2EyOWFiMGZlOWIiXQ)).

I suppose we may think about some extension and new tests addition like:
- running on 9-nodes cluster (see some details in conversation [here](https://docs.google.com/document/d/1r0B5xm7rUE0Sxn7EFtnrpQ_rP6DOMotmW8D6C6gtqDA/edit?disco=AAABVunUCsU));
- dataset with several tables;
- different from ICS compaction strategy.

**Comment by karol-kokoszka** [comment]
> running on 9-nodes cluster (see some details in conversation [here](https://docs.google.com/document/d/1r0B5xm7rUE0Sxn7EFtnrpQ_rP6DOMotmW8D6C6gtqDA/edit?disco=AAABVunUCsU));
dataset with several tables;
different from ICS compaction strategy.

Let's agree that it's worth to proceed with:
- running the restore on 9 nodes cluster
- more than 1 table
- default compaction strategy
