### ISSUE TITLE
Invalid column name labels because it conflicts with an existing column

### ISSUE THREAD

**Issue by coolbaluk** [scylladb/scylla-manager#4053]
Hello!

I need some assistance.

This just started happening and I'm at a loss at how to fix it, what is the column labels ?

The manager is supposed to be at 3.3.0, yet I get this error:

`STARTUP ERROR: db init: apply migration "v3.3.1.cql": statement 1: Invalid column name labels because it conflicts with an existing column`

No changes have been made, it looks like it happened after a restart. It pulled a new image perhaps ?

[must-gather.zip](https://github.com/user-attachments/files/17216775/must-gather.zip)

**Comment by Michal-Leszczynski** [comment]
Hi, in the past we had a problem where we accidentally overwritten the 3.3.0 image with 3.3.1 image, although it should be reversed by now (@Annamikhlin). Can you try running SM 3.3.3 and see if it solves the issue? If not, then you can fix the schema in SM DB manually when SM is down by running the following CQL commands:
```
USE scylla_manager;
ALTER TABLE cluster DROP labels;
ALTER TABLE scheduler_task ADD tags set<text>;
ALTER TABLE scheduler_task DROP labels;
DELETE FROM gocqlx_migrate where name='v3.3.1.cql';
```
Don't worry if some of those statements result in a "not found" error.
After doing so, start SM 3.3.3 and it should regenerate schema changes introduced in SM 3.3.1 without problems.

**Comment by coolbaluk** [comment]
Hey,


Just pushing to SM 3.3.3 did not solve the issue on its own.

This particular command from your suggestion was the one that did the trick:

> ALTER TABLE cluster DROP labels;

After running it and scaling the manager back up it did start correctly.

Thank you for the help!

I will be closing this issue.
