### ISSUE TITLE
function to find backup available in location

### ISSUE THREAD

**Issue by nopzdk** [scylladb/scylla-manager#4067]
today when performing a restore it requires me to review the folder structure to find snapshot IDs, it would be nice if i can use something like
sctool backup list --find -L s3:docker to find the available snapshots from that location, instead of having to find it manually.
it is very useful if I am restoring a backup into a new cluster.

**Comment by Michal-Leszczynski** [comment]
Please take a look at [sctool backup list docs](https://manager.docs.scylladb.com/stable/sctool/backup.html#backup-list).
```
backup list

This command allow you to list backups from given locations. The command works per cluster and all the locations listed with the –location flag must be accessible from the cluster specified with the –cluster flag. This cluster serves as the coordinator for all these checks. If the Scylla Manager Agent’s of given cluster is not able to reach the location, the command will fail.
Syntax

sctool backup list --cluster <id|name> [flags]

Command options
--all-clusters

Shows backups for all clusters. Useful for listing clusters that are no longer available locally but are backed up in the past to remote location.
```

Does `--all-clusters` flag solve your problem?

**Comment by nopzdk** [comment]
@Michal-Leszczynski that does what I was looking for, just a bit counter intuative that I have to add --cluster xxx --all-clusters
Thanks you.
