### ISSUE TITLE
SCT fails installing awscli python package to Scylla OS 6.1 and 6.2 nodes

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4105]
~~**Steps to reproduce:**~~
~~1. Populate the cluster with some data
2. Do backup
3. Truncate the table
4. Restore data via `sctool restore`:~~
```
sctool restore -c adbbc2ee-81d0-42f8-9925-ef29d1c117a8 --restore-tables --location s3:manager-backup-tests-us-east-1  --snapshot-tag sm_20241106131138UTC
```
~~5. Wait for task DONE status
6. Check the cluster data restored~~

~~**Actual result:**~~
~~The cluster **is missing** any data after restore despite the fact that the sctool task completed with **DONE status**.~~
```
cqlsh> select * from keyspace1.standard1;

 key | C0 | C1 | C2 | C3 | C4
-----+----+----+----+----+----

(0 rows)
```

~~**Expected result:**~~
~~All data from backup restored successfully.~~

_**It turned out to be a test configuration issue described in https://github.com/scylladb/scylla-manager/issues/4105#issuecomment-2460147793.**_

**Environment:**
- Scylla version - OSS 6.1.2; OSS 6.2.0 (both with enabled by default tablets feature)
- Not reproduced for Scylla 6.0
- Manager - reproduced for both 3.3.3 and 3.4.0 (looks like not related to specific Manager version)

**Test artifacts:**
Jenkins job - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/mikita/job/manager-master/job/ubuntu22-sanity-test/29
Argus - https://argus.scylladb.com/tests/scylla-cluster-tests/e4fda521-9df9-484d-841a-b5783992c4ef

**Comment by Michal-Leszczynski** [comment]
@mikliapko it looks like backup `sm_20241106131138UTC` does not contain any data for `keyspace1.standard1`:
```
Nov 06 13:11:40 manager-regression-oss-mana-monitor-node-e4fda521-1 scylla-manager[9444]: {"L":"INFO","T":"2024-11-06T13:11:40.276Z","N":"backup.upload","M":"Table is empty skipping","host":"10.12.1.195","keyspace":"keyspace1","table":"standard1","_trace_id":"JOkH6R9jTxOuqG0mSRgq5w"}
```
So it's not a problem with restore.
On the other hand, we can also see that:
```
14:11:44  < t:2024-11-06 13:11:43,984 f:mgmt_cli_test.py l:255  c:MgmtCliTest          p:INFO  > running truncate on keyspace1.standard1
```
In general, from SM logs we can see the following:
- backups task 1 runs and back ups non empty `keyspace1.standard1`
- backups task 2 runs and back ups empty `keyspace1.standard1`
- restore task runs and restores backup task 2 resulting in not restoring any data from `keyspace1.standard1`

**Comment by mikliapko** [comment]
> [@mikliapko](https://github.com/mikliapko) it looks like backup `sm_20241106131138UTC` does not contain any data for `keyspace1.standard1`:
> 
> ```
> Nov 06 13:11:40 manager-regression-oss-mana-monitor-node-e4fda521-1 scylla-manager[9444]: {"L":"INFO","T":"2024-11-06T13:11:40.276Z","N":"backup.upload","M":"Table is empty skipping","host":"10.12.1.195","keyspace":"keyspace1","table":"standard1","_trace_id":"JOkH6R9jTxOuqG0mSRgq5w"}
> ```
> 
> So it's not a problem with restore. On the other hand, we can also see that:
> 
> ```
> 14:11:44  < t:2024-11-06 13:11:43,984 f:mgmt_cli_test.py l:255  c:MgmtCliTest          p:INFO  > running truncate on keyspace1.standard1
> ```
> 
> In general, from SM logs we can see the following:
> 
> * backups task 1 runs and back ups non empty `keyspace1.standard1`
> * backups task 2 runs and back ups empty `keyspace1.standard1`
> * restore task runs and restores backup task 2 resulting in not restoring any data from `keyspace1.standard1`

Hm, that's strange the `keyspace1.standard1` is empty before running backup 2.
It may be related to tests sequence, at first we run pretty the same test but restore via `nodetool refresh` (it's related to backup 1). And there the post-restore c-s read passes. Okay, let me check the test once again.

**Comment by Michal-Leszczynski** [comment]
> And there the post-restore c-s read passes. Okay, let me check the test once again.

How did you check that it passes?

**Comment by mikliapko** [comment]
> > And there the post-restore c-s read passes. Okay, let me check the test once again.
> 
> How did you check that it passes?

Good question, I'm relying on the test - it should have failed if verification read fails.
But now I'm not sure.

**Comment by mikliapko** [comment]
@Michal-Leszczynski 
Ah, alright, I was confused with the fact that Argus displayed only the latest c-s verification errors but not all.
In fact, it fails for both this tests and as you already mentioned the reason is the first restore we do via `nodetool refresh`.

**Comment by mikliapko** [comment]
Alright, the actual reason - the test fails to install dependencies required for backup files downloading via `aws s3 cp ...`:
```
2024-11-06 10:13:30.734: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=a678c60a-c782-494b-bc8e-76a7e1afa8d5, source=MgmtCliTest.test_manager_sanity (mgmt_cli_test.MgmtCliTest) [Basic Backup Test]() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 426, in test_manager_sanity
self.test_basic_backup(ks_names=ks_names)
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 631, in test_basic_backup
self.verify_backup_success(mgr_cluster=mgr_cluster, backup_task=backup_task, ks_names=ks_names)
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 261, in verify_backup_success
self.restore_backup_from_backup_task(mgr_cluster=mgr_cluster, backup_task=backup_task,
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 241, in restore_backup_from_backup_task
self.restore_backup_without_manager(mgr_cluster=mgr_cluster, snapshot_tag=snapshot_tag,
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 217, in restore_backup_without_manager
install_dependencies(node=node)
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 129, in install_awscli_dependencies
self._run_cmd_with_retry(executor=node.remoter.sudo, cmd=shell_script_cmd(cmd))
File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 108, in _run_cmd_with_retry
executor(cmd)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
return self.run(cmd=cmd,
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 653, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 644, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 577, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 625, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 660, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\napt update\napt install -y python3-pip\npip install awscli==1.18.140\n"'
Exit code: 1
Stdout:
Setting up gcc (4:13.2.0-7ubuntu1) ...
Setting up python3-dev (3.12.3-0ubuntu2) ...
Setting up g++-x86-64-linux-gnu (4:13.2.0-7ubuntu1) ...
Setting up g++-13 (13.2.0-23ubuntu4) ...
Setting up g++ (4:13.2.0-7ubuntu1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/c++.1.gz because associated file /usr/share/man/man1/g++.1.gz (of link group c++) doesn't exist
Setting up build-essential (12.10ubuntu1) ...
Processing triggers for systemd (255.4-1ubuntu8.4) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
Stderr:
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

@Michal-Leszczynski Sorry for false alarm and thanks for your help with investigation. I'll update the issue.
