### ISSUE TITLE
Possibility to query instance metadata for Azure

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#4129]
https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#access-azure-instance-metadata-service

**Comment by karol-kokoszka** [comment]
@d-helios Do we have an access to Azure for the developers ? We need to check the cloud provider in SM. To do that, we need to query for instance metadata. To do the last one and test it we need to create it on Azure.

**Comment by d-helios** [comment]
no it should be integrated with Okta and so ...
you can ask direct access by writing email to it@scylladb.com
if it is something that is required for entire team let me know how urgent it is

**Comment by karol-kokoszka** [comment]
> if it is something that is required for entire team let me know how urgent it is

It's not urgent, but is needed for SM development. So @VAveryanov8 @karol-kokoszka @Michal-Leszczynski .
I can send the request to IT.
