### ISSUE TITLE
Control throttling of Scylla backup API

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#4135]
Ref: https://github.com/scylladb/scylladb/issues/21095

**Comment by regevran** [comment]
According to recent discussion - there is no need in throttling Scylla when it is backing up.

@Michal-Leszczynski  - do you need to open another issue to _remove_ this functionality (used to be done by `rclone` api) from scylla manager?

**Comment by regevran** [comment]
Yes. I understand your point - setting a rate limit is just `rclone` API - and has nothing to do with backup anymore.
Please close this issue then.
