### ISSUE TITLE
Control throttling of Scylla restore API

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#4136]
Ref: https://github.com/scylladb/scylladb/issues/20868

**Comment by karol-kokoszka** [comment]
As of 2.12.2024 -> it's not part of the current scylla open source master.

**Comment by regevran** [comment]
According to recent discussion - there is no need in throttling Scylla when it is restoring.

@Michal-Leszczynski  - do you need to open another issue to _remove_ this functionality (used to be done by `rclone` api) from scylla manager?

**Comment by Michal-Leszczynski** [comment]
Same as https://github.com/scylladb/scylla-manager/issues/4135#issuecomment-2527266642.
